Repository openware/peatio, pull requests merged in 2018-08, with the labels that each got.

#1484 Remove Unwanted Code From Currency MVC
  app/api/api_v2/entities/currency.rb
  app/controllers/admin/currencies_controller.rb
  app/models/blockchain.rb
  app/models/currency.rb
  app/models/deposits/coin.rb
  app/models/payment_address.rb
  app/models/wallet.rb
  app/models/withdraws/coin.rb
  app/views/admin/blockchains/show.html.erb
  app/views/admin/currencies/show.html.erb
  config/templates/seed/currencies.yml.erb
  spec/api/api_v2/currencies_spec.rb
  spec/controllers/admin/currencies_controller_spec.rb
  spec/factories/currencies.rb
Labels: PR: Changes needed, PR: Review

#1501 Updates for admin panel
  app/assets/javascripts/funds/models/currency.js.coffee
  app/controllers/admin/currencies_controller.rb
  app/controllers/admin/wallets_controller.rb
  app/models/currency.rb
  app/models/deposits/coin.rb
  app/models/wallet.rb
  app/models/withdraws/coin.rb
  app/views/admin/blockchains/show.html.erb
  app/views/admin/currencies/show.html.erb
  app/views/admin/wallets/show.html.erb
  config/templates/seed/blockchains.yml.erb
  db/migrate/20180803144827_remove_urls_from_currencies.rb
  db/schema.rb
  spec/controllers/admin/currencies_controller_spec.rb
  spec/factories/currencies.rb
Labels: v1.9

#1493 Add more details for the API docs
  app/api/api_v2/currencies.rb
  app/api/api_v2/entities/currency.rb
  app/api/api_v2/mount.rb
Labels: PR: Review, v1.9

#1459 Include PublishToRabbitMQ GenerateJWT Event API middlewares by default
  config/initializers/event_api.rb
  config/templates/application.yml.erb
  spec/spec_helper.rb
Labels: PR: Approved, v1.8

#1465 Add icon url to currency (closes #1449)
  app/api/api_v2/entities/currency.rb
  app/controllers/admin/currencies_controller.rb
  app/helpers/currency_helper.rb
  app/models/currency.rb
  app/views/admin/currencies/show.html.erb
  db/migrate/20180720165705_add_icon_url_to_currency.rb
  db/schema.rb
Labels: v1.9

#1526 Change Currency Id And Market Id Limit (closes #1499)
  app/models/market.rb
  app/models/order.rb
  app/models/order_ask.rb
  app/models/order_bid.rb
  app/models/trade.rb
  app/models/wallet.rb
  db/migrate/20180813105100_change_limit_of_currency_id_and_market_id.rb
  db/schema.rb
Labels: PR: Approved, v1.9

#1527 Change Currency Id And Market Id Limit (closes #1499)
  app/models/market.rb
  app/models/order.rb
  app/models/order_ask.rb
  app/models/order_bid.rb
  app/models/trade.rb
  db/migrate/20180813105100_change_limit_of_currency_id_and_market_id.rb
  db/schema.rb
Labels: PR: Approved, v1.8

#1529 Code polish and minor bugfix (closes #1531)
  app/api/api_v2/entities/deposit.rb
  app/api/api_v2/entities/withdraw.rb
  app/models/blockchain.rb
  app/models/currency.rb
  app/models/wallet.rb
  app/models/withdraw.rb
  app/services/wallet_service.rb
  app/services/wallet_service/bitcoind.rb
  app/services/wallet_service/bitgo.rb
  app/services/wallet_service/geth.rb
  app/views/admin/blockchains/index.html.erb
  app/views/admin/blockchains/show.html.erb
  app/views/admin/wallets/_bitgo_form.html.erb
  app/views/admin/wallets/_default_form.html.erb
  app/views/admin/wallets/index.html.erb
  app/views/admin/wallets/show.html.erb
  config/templates/seed/blockchains.yml.erb
  config/templates/seed/wallets.yml.erb
  db/migrate/20180718113111_replace_deposit_confirmations_with_min_confirmations.rb
  lib/blockchain_client/bitcoin.rb
  lib/blockchain_client/ethereum.rb
  lib/tasks/seed.rake
  lib/wallet_client/bitcoincashd.rb
  lib/wallet_client/bitcoind.rb
  lib/wallet_client/bitgo.rb
  lib/wallet_client/dashd.rb
  lib/wallet_client/geth.rb
  lib/wallet_client/litecoind.rb
  spec/controllers/admin/wallets_controller_spec.rb
  spec/models/wallet_spec.rb
  spec/services/blockchain_service/ethereum_spec.rb
Labels: PR: Approved, v1.9

#1530 Add Bitgo Wallet ID And Remove Wallet Address In Wallet Model
  app/controllers/admin/wallets_controller.rb
  app/models/wallet.rb
  app/views/admin/wallets/_bitgo_form.html.erb
  config/templates/seed/wallets.yml.erb
  lib/wallet_client/bitgo.rb
Labels: PR: Approved, v1.9

#1517 Improved updation of blockchain height
  app/services/blockchain_service.rb
  app/services/blockchain_service/bitcoin.rb
  app/services/blockchain_service/ethereum.rb
Labels: PR: Approved, v1.9

#1533 Edit comments in templates for wallets.yml
  config/templates/seed/wallets.yml.erb
Labels: PR: Approved, v1.9

#1541 Fixed rake db:seed failure (closes #1539)
  config/templates/seed/blockchains.yml.erb
  config/templates/seed/currencies.yml.erb
Labels: PR: Approved, v1.9

#1534 Improved updation of blockchain height and exception handling mechanism (closes #1548, #1545)
  app/services/blockchain_service.rb
  app/services/blockchain_service/bitcoin.rb
  app/services/blockchain_service/ethereum.rb
Labels: PR: Approved, v1.9

#1542 Updated xit Specs
  spec/controllers/admin/wallets_controller_spec.rb
  spec/factories/wallet.rb
  spec/models/withdraw_spec.rb
  spec/spec_helper.rb
Labels: PR: Approved, v1.9

#1543 Do not allow to disable last enabled market (closes #1548)
  app/models/currency.rb
  app/models/market.rb
  config/templates/seed/currencies.yml.erb
  spec/models/currency_spec.rb
  spec/models/market_spec.rb
Labels: PR: Approved, v1.9

#1546 Ability to see Transaction ID in user interface
  config/locales/client.en.yml
  public/templates/funds/_coin_withdraw.html
Labels: PR: Approved, v1.9

#1550 Do not allow to disable last enabled market (related to #1548)
  app/models/currency.rb
  app/models/market.rb
  spec/models/currency_spec.rb
  spec/models/market_spec.rb
Labels: PR: Approved, v1.8

#1551 [ci skip] Update Readme
  README.md
  config/backend.yml
Labels: PR: WIP, v1.9

#1552 Fixed wallet secret not being saved from admin panel
  app/views/admin/wallets/_default_form.html.erb
Labels: v1.9

#1559 Added validation to restrict display currency to be disabled
  app/models/currency.rb
  spec/models/currency_spec.rb
Labels: PR: Approved, v1.9

#1561 Fix BitGo Wallet Transactions Query Parameter Incorrect (closes #1365)
  lib/coin_api/bit_go.rb
Labels: PR: Approved, v1.8

#1562 Fix BitGo Wallet Transactions Query Parameter Incorrect (#1365)
  lib/coin_api/bit_go.rb
Labels: PR: Approved, v1.7

#1563 Fix BitGo Wallet Transactions Query Parameter Incorrect (#1365)
  lib/coin_api/bit_go.rb
Labels: PR: Approved, v1.6

#1564 Fix BitGo Wallet Transactions Query Parameter Incorrect (#1365)
  lib/coin_api/bit_go.rb
Labels: PR: Approved, v1.5

#1567 Update docs about authenticating in management api
  docs/api/authenticating_in_management_api_v1.md
Labels: PR: Approved, v1.9

#1579 Rename missing spec files (#1395)
  spec/lib/coin_api/bit_go_spec.rb
Labels: PR: Approved, v1.6

#1578 Rename missing spec files (#1395)
  spec/lib/coin_api/bit_go_spec.rb
Labels: PR: Approved, v1.7

#1577 Rename missing spec files (#1395)
  spec/lib/coin_api/bit_go_spec.rb
Labels: PR: Approved, v1.8

#1586 Remove Features Specs #1585
  Gemfile
  Gemfile.lock
  spec/features/admin/withdraw_spec.rb
  spec/features/market_spec.rb
  spec/features/market_trade_history_spec.rb
  spec/spec_helper.rb
  spec/support/capybara.rb
  spec/support/cookie_helper.rb
  spec/support/inject_session.rb
  spec/support/member_helper.rb
Labels: v1.9

#1587 Added _spec in spec file
  spec/lib/coin_api/bit_go_spec.rb
Labels: v1.5

#1598 Remove websocket stuff (closes #1597)
  Gemfile
  Gemfile.lock
  app/api/api_v2/web_socket_protocol.rb
  config/templates/application.yml.erb
  lib/daemons/websocket_api.rb
  spec/api/api_v2/websocket_protocol_spec.rb
  spec/support/socket_helper.rb
Labels: PR: Approved, v1.9

#1592 Confirmation can't be negative (closes #1581)
  app/models/deposits/coin.rb
  app/models/withdraws/coin.rb
Labels: PR: Approved, v1.9

#1565 Informative message when POST /api/v2/orders with wrong volume (closes #1438)
  app/api/api_v2/errors.rb
  app/api/api_v2/helpers.rb
  app/api/api_v2/named_params.rb
  spec/api/api_v2/orders_spec.rb
Labels: PR: Approved, v1.9

#1575 Add rc tag for master releases in ci/bump.rb
  .travis.yml
  bin/bump
  bin/gendocs
  ci/bump.rb
  lib/peatio/version.rb
Labels: Category: CI, PR: WIP, v1.9

#1603 Remove peatio-trading-ui and dependencies from CI (closes #1601)
  .travis.yml
  ci/nginx/server.conf
Labels: Category: CI, PR: Approved, v1.9

#1556 Integrate peatio-core Peatio::Auth::JWTAuthenticator to APIv2 (#1555)
  Gemfile
  Gemfile.lock
  app/api/api_v2/auth/jwt_authenticator.rb
  app/api/api_v2/auth/middleware.rb
  app/api/api_v2/errors.rb
  app/api/api_v2/helpers.rb
  spec/api/api_v2/auth/jwt_authenticator_spec.rb
  spec/api/api_v2/auth/middleware_spec.rb
  spec/api/api_v2/error_spec.rb
  spec/api/api_v2/helpers_spec.rb
  spec/api/api_v2/trades_spec.rb
  spec/spec_helper.rb
Labels: PR: Approved, v1.9

#1616 Update bump script to support «rc» in tag
  bin/bump
Labels: Category: CI, PR: Approved

#1588 Support Cash Address format
  app/controllers/admin/currencies_controller.rb
  app/models/currency.rb
  app/models/deposits/coin.rb
  app/models/payment_address.rb
  app/models/wallet.rb
  app/models/withdraws/coin.rb
  config/templates/seed/currencies.yml.erb
  lib/blockchain_client.rb
  lib/blockchain_client/bitcoincash.rb
  lib/wallet_client/bitcoincashd.rb
  lib/wallet_client/bitgo.rb
  lib/wallet_client/geth.rb
  spec/controllers/admin/currencies_controller_spec.rb
  spec/factories/currencies.rb
  spec/services/blockchain_service/bitcoincash_spec.rb
Labels: PR: Approved, v1.9

#1599 Removed webhook controller and dependencies
  app/controllers/webhooks_controller.rb
  config/routes.rb
  config/templates/application.yml.erb
Labels: PR: Approved, v1.9

#1606 Fix swagger doc for APIv2 (closes #1605)
  app/api/api_v2/entities/currency.rb
Labels: PR: Approved, v1.9

#1600 Update websocket_api doc now we use ranger
  docs/api/assets/scheme_ranger_private_channels.png
  docs/api/assets/scheme_ranger_public_channels.png
  docs/api/websocket_api.md
Labels: PR: Approved, v1.9

#1612 Added Swagger docs healthiness spec #1607
  spec/api/swagger_spec.rb
Labels: PR: Approved, v1.9
