Repository openware/peatio, pull requests merged in 2018-05, with the labels that each got.

#935 Add API calls for getting all possible fees (resolves #852)
  app/api/api_v2/fees.rb
  app/api/api_v2/mount.rb
  spec/api/api_v2/fees_spec.rb
Labels: PR: Approved, v1.8

#998 Submit withdraw after creation via API (closes #997)
  app/api/api_v2/withdraws.rb
  spec/api/api_v2/withdraws_spec.rb
Labels: PR: Approved, v1.8

#1002 Submit withdraw after creation via API
  app/api/api_v2/withdraws.rb
  spec/api/api_v2/withdraws_spec.rb
Labels: PR: Approved, v1.6

#1004 Submit withdraw after creation via API
  app/api/api_v2/withdraws.rb
  spec/api/api_v2/withdraws_spec.rb
Labels: PR: Approved, v1.7

#1007 Add missing «withdraw_fee» & «deposit_confirmations» to config/seed/currencies.yml.erb
  config/templates/seed/currencies.yml.erb
Labels: PR: Approved, v1.7

#1008 Add «deposit_confirmations» to config/seed/currencies.yml.erb
  config/templates/seed/currencies.yml.erb
Labels: PR: Approved, v1.8

#1014 Fix disappearing security_configuration when module reloads
  app/api/management_api_v1/jwt_authentication_middleware.rb
  config/initializers/jwt.rb
  spec/support/api_helper.rb
Labels: PR: Approved, v1.8

#1018 Fix disappearing security_configuration when module reloads
  app/api/management_api_v1/jwt_authentication_middleware.rb
  config/initializers/jwt.rb
  spec/support/api_helper.rb
Labels: PR: Approved, v1.7

#1012 Permit transactions between internal recipients
  app/models/withdraws/coin.rb
  lib/coin_api/bit_go.rb
  lib/coin_api/btc.rb
  lib/coin_api/eth.rb
  lib/coin_api/xrp.rb
  spec/lib/coin_api/eth_spec.rb
  spec/lib/coin_api/xrp_spec.rb
  spec/models/withdraw_spec.rb
Labels: PR: Approved, v1.8

#1016 Fix disappearing security_configuration when module reloads
  app/api/management_api_v1/jwt_authentication_middleware.rb
  config/initializers/jwt.rb
  spec/support/api_helper.rb
Labels: PR: Approved, v1.6

#1027 Add logging to Grape APIs
  Gemfile
  Gemfile.lock
  app/api/api_v2/mount.rb
  app/api/management_api_v1/exceptions/base.rb
  app/api/management_api_v1/mount.rb
  spec/api/api_v2/mount_spec.rb
Labels: PR: Approved, v1.8

#913 Add support for ERC20
  Gemfile
  Gemfile.lock
  app/models/currency.rb
  app/models/deposit.rb
  app/models/deposits/coin.rb
  app/models/deposits/fiat.rb
  app/models/market.rb
  app/models/payment_address.rb
  app/models/withdraw.rb
  app/models/withdraws/coin.rb
  app/models/withdraws/fiat.rb
  config/templates/seed/currencies.yml.erb
  config/templates/seed/markets.yml.erb
  db/migrate/20180501082703_normalize_addresses_and_transactions.rb
  db/migrate/20180501141718_case_sensitive_data.rb
  db/schema.rb
  docs/peatio/erc20.md
  docs/peatio/testnet/erc20.md
  lib/coin_api.rb
  lib/coin_api/bch.rb
  lib/coin_api/bit_go.rb
  lib/coin_api/btc.rb
  lib/coin_api/erc20.rb
  lib/coin_api/eth.rb
  lib/coin_api/xrp.rb
  spec/api/api_v2/entities/member_spec.rb
  spec/api/api_v2/fees_spec.rb
  spec/api/api_v2/members_spec.rb
  spec/factories/currencies.rb
  spec/lib/coin_api/erc20_spec.rb
  spec/spec_helper.rb
Labels: PR: Approved, v1.8

#1033 Proposal for API to expose for account balance.
  app/api/management_api_v1/accounts.rb
  app/api/management_api_v1/entities/balance.rb
  app/api/management_api_v1/mount.rb
  spec/api/management_api_v1/accounts_spec.rb
  spec/api/management_api_v1/entities/balance_spec.rb
Labels: PR: Approved, v1.8

#1028 Tweak lib/daemons/coins.rb for stability
  lib/coin_api/bit_go.rb
  lib/coin_api/btc.rb
  lib/coin_api/eth.rb
  lib/coin_api/xrp.rb
  lib/daemons/coins.rb
Labels: PR: Approved, v1.8

#1037 Replace state to action in withdraws (Management API v1)
  app/api/management_api_v1/withdraws.rb
  spec/api/management_api_v1/withdraws_spec.rb
Labels: PR: Approved, v1.8

#1026 Release Peatio 1.8.0
  bin/bump
  ci/bump.rb
  docs/api/management_api_v1.md
  docs/api/member_api_v2.md
  docs/releases/1.8.0.md
  lib/peatio/version.rb
Labels: PR: Approved, v1.8

#1055 Fix trade execution errors
  app/models/matching/executor.rb
  app/models/worker/trade_executor.rb
Labels: PR: Approved, v1.8

#1057 Don't upcase TID (keep it as is)
  app/models/concerns/tid_identifiable.rb
  spec/models/deposit_spec.rb
  spec/models/withdraw_spec.rb
Labels: PR: Approved, v1.8

#1049 Support sendmany Bitcoin transaction which contain recipient address not belonging to Peatio (fixes #1040).
  app/services/services/blockchain_transaction_handler.rb
  lib/daemons/coins.rb
  spec/models/worker/deposit_coin_spec.rb
  spec/services/blockchain_transaction_handler_spec.rb
Labels: PR: Approved, v1.8

#1060 Touch accounts after creating new currency
  app/models/currency.rb
Labels: PR: Approved, v1.8

#1066 Disable unsupported order type and don't expose internal exceptions to outer world (fixes #1051).
  app/api/api_v2/errors.rb
  app/api/api_v2/named_params.rb
  spec/api/api_v2/orders_spec.rb
Labels: PR: Approved, v1.8

#1065 Touch accounts after creating new currency (fixes #1059)
  app/models/currency.rb
Labels: PR: Approved, v1.5

#1064 Touch accounts after creating new currency (fixes #1059)
  app/models/currency.rb
Labels: PR: Approved, v1.7

#1063 Touch accounts after creating new currency (fixes #1059)
  app/models/currency.rb
Labels: PR: Approved, v1.6

#1061 Add case_sensitive & erc20_contract_address to currency rubric in admin panel
  app/controllers/admin/currencies_controller.rb
  app/views/admin/currencies/show.html.erb
Labels: PR: Approved, v1.8

#1070 Fix trade execution errors
  app/models/matching/executor.rb
  app/models/worker/trade_executor.rb
Labels: PR: Approved, v1.7

#1071 Fix trade execution errors
  app/models/matching/executor.rb
  app/models/worker/trade_executor.rb
Labels: PR: Approved, v1.6

#1053 Add market events to Event API
  app/models/order.rb
  app/models/trade.rb
  app/serializers/serializers/event_api/order_canceled.rb
  app/serializers/serializers/event_api/order_completed.rb
  app/serializers/serializers/event_api/order_created.rb
  app/serializers/serializers/event_api/order_event.rb
  app/serializers/serializers/event_api/order_updated.rb
  app/serializers/serializers/event_api/trade_completed.rb
  docs/specs/event_api.md
  spec/api/api_v2/entities/account_spec.rb
  spec/factories/account.rb
  spec/factories/orders.rb
  spec/factories/trade.rb
  spec/models/account_spec.rb
  spec/models/order_spec.rb
  spec/serializers/serializers/event_api/order_canceled_spec.rb
  spec/serializers/serializers/event_api/order_completed_spec.rb
  spec/serializers/serializers/event_api/order_created_spec.rb
  spec/serializers/serializers/event_api/order_updated_spec.rb
  spec/serializers/serializers/event_api/trade_completed_spec.rb
  spec/services/blockchain_transaction_handler_spec.rb
  spec/services/ordering_spec.rb
Labels: PR: Approved, v1.8

#1072 Disable unsupported order type and don't expose internal exceptions to outer world (fixes #1051).
  app/api/api_v2/errors.rb
  app/api/api_v2/named_params.rb
  spec/api/api_v2/orders_spec.rb
Labels: PR: Approved, v1.7

#1073 Disable unsupported order type and don't expose internal exceptions to outer world (fixes #1051).
  app/api/api_v2/errors.rb
  app/api/api_v2/named_params.rb
  spec/api/api_v2/orders_spec.rb
Labels: PR: Approved, v1.6

#1074 Disable unsupported order type and don't expose internal exceptions to outer world (fixes #1051).
  app/api/api_v2/errors.rb
  app/api/api_v2/named_params.rb
  spec/api/api_v2/orders_spec.rb
Labels: PR: Approved, v1.5

#1075 Fix trade executor errors
  app/models/matching/executor.rb
  app/models/worker/trade_executor.rb
Labels: PR: Approved, v1.5

#1081 Ability to configure log level via environment variable LOG_LEVEL (closes #1079).
  .travis.yml
  app/api/api_v2/helpers.rb
  app/api/api_v2/websocket_protocol.rb
  app/models/account.rb
  app/models/matching/engine.rb
  app/models/matching/order_book.rb
  app/models/withdraws/coin.rb
  app/models/worker/deposit_coin.rb
  app/models/worker/market_ticker.rb
  app/models/worker/matching.rb
  app/models/worker/order_processor.rb
  app/models/worker/slave_book.rb
  app/models/worker/stats.rb
  app/models/worker/top_stats.rb
  app/models/worker/wallet_stats.rb
  config/environments/shared/logger.rb
  config/initializers/exception_reporting.rb
  config/templates/application.yml.erb
  lib/daemons/amqp_daemon.rb
  lib/daemons/coins.rb
  lib/daemons/hot_wallets.rb
  lib/daemons/k.rb
  lib/daemons/stats.rb
  lib/daemons/websocket_api.rb
  lib/tasks/solvency.rake
Labels: PR: Approved, v1.7

#1086 Update ci/bump.rb: add logging, add pagination for GitHub API (fixes bumping for older branches).
  ci/bump.rb
Labels: PR: Approved, v1.7

#1084 Update ci/bump.rb: add logging, add pagination for GitHub API (fixes bumping for older branches).
  ci/bump.rb
Labels: PR: Approved, v1.8

#1085 Update ci/bump.rb: add logging, add pagination for GitHub API (fixes bumping for older branches).
  ci/bump.rb
Labels: PR: Approved, v1.6

#1080 Ability to configure log level via environment variable LOG_LEVEL (closes #1079).
  .travis.yml
  app/api/api_v2/helpers.rb
  app/api/api_v2/mount.rb
  app/api/api_v2/websocket_protocol.rb
  app/api/management_api_v1/mount.rb
  app/models/account.rb
  app/models/matching/engine.rb
  app/models/matching/order_book.rb
  app/models/withdraws/coin.rb
  app/models/worker/deposit_coin.rb
  app/models/worker/market_ticker.rb
  app/models/worker/matching.rb
  app/models/worker/order_processor.rb
  app/models/worker/slave_book.rb
  app/models/worker/stats.rb
  app/models/worker/top_stats.rb
  app/models/worker/wallet_stats.rb
  app/services/services/blockchain_transaction_handler.rb
  config/environments/shared/logger.rb
  config/initializers/exception_reporting.rb
  config/templates/application.yml.erb
  lib/daemons/amqp_daemon.rb
  lib/daemons/hot_wallets.rb
  lib/daemons/k.rb
  lib/daemons/stats.rb
  lib/daemons/websocket_api.rb
  lib/tasks/solvency.rake
Labels: PR: Approved, v1.8

#1082 Ability to configure log level via environment variable LOG_LEVEL (closes #1079).
  .travis.yml
  app/api/api_v2/helpers.rb
  app/api/api_v2/websocket_protocol.rb
  app/models/account.rb
  app/models/amqp_queue.rb
  app/models/matching/engine.rb
  app/models/matching/order_book.rb
  app/models/withdraws/coin.rb
  app/models/worker/deposit_coin.rb
  app/models/worker/market_ticker.rb
  app/models/worker/matching.rb
  app/models/worker/order_processor.rb
  app/models/worker/slave_book.rb
  app/models/worker/stats.rb
  app/models/worker/top_stats.rb
  app/models/worker/wallet_stats.rb
  config/environments/shared/logger.rb
  config/initializers/exception_reporting.rb
  config/templates/application.yml.erb
  lib/daemons/amqp_daemon.rb
  lib/daemons/coins.rb
  lib/daemons/hot_wallets.rb
  lib/daemons/k.rb
  lib/daemons/stats.rb
  lib/daemons/websocket_api.rb
  lib/tasks/solvency.rake
Labels: PR: Approved, v1.6

#1089 Use existing Rails logger with preconfigured level, log device etc (don't create new)
  lib/daemons/amqp_daemon.rb
  lib/daemons/k.rb
  lib/daemons/stats.rb
  lib/daemons/websocket_api.rb
Labels: PR: Approved, v1.7

#1094 Ability to configure log level via environment variable LOG_LEVEL (closes #1079).
  .travis.yml
  app/api/api_v2/helpers.rb
  app/api/api_v2/websocket_protocol.rb
  app/models/account.rb
  app/models/amqp_queue.rb
  app/models/concerns/withdraws/coinable.rb
  app/models/matching/engine.rb
  app/models/matching/order_book.rb
  app/models/worker/deposit_coin.rb
  app/models/worker/market_ticker.rb
  app/models/worker/matching.rb
  app/models/worker/order_processor.rb
  app/models/worker/slave_book.rb
  app/models/worker/stats.rb
  app/models/worker/top_stats.rb
  app/models/worker/wallet_stats.rb
  config/environments/shared/logger.rb
  config/initializers/exception_reporting.rb
  config/templates/application.yml.erb
  lib/daemons/amqp_daemon.rb
  lib/daemons/hot_wallets.rb
  lib/daemons/k.rb
  lib/daemons/stats.rb
  lib/daemons/websocket_api.rb
  lib/tasks/solvency.rake
Labels: PR: QA, v1.3

#1100 Specs for CoinAPI::BCH (closes #1046)
  spec/api/api_v2/entities/member_spec.rb
  spec/api/api_v2/fees_spec.rb
  spec/api/api_v2/members_spec.rb
  spec/factories/currencies.rb
  spec/lib/coin_api/bch_spec.rb
  spec/models/account_spec.rb
  spec/spec_helper.rb
Labels: PR: Approved, v1.8

#1062 Update documentation (issue #325)
  README.md
  docs/peatio/currency.md
  docs/setup-osx.md
  docs/setup-ubuntu.md
Labels: PR: Approved, v1.8

#1093 Specs for CoinAPI::BTC (closes #970)
  lib/coin_api/btc.rb
  spec/lib/coin_api/btc_spec.rb
Labels: PR: Approved, v1.8

#1102 Drop config/initializers/abstract_mysql2_adapter.rb
  config/initializers/abstract_mysql2_adapter.rb
Labels: PR: Approved, v1.8

#1130 Fix «NoMethodError: undefined method `[]=' for nil:NilClass in Worker::MarketTicker line 26» (closes #1118).
  app/models/worker/market_ticker.rb
Labels: PR: Approved, v1.8

#1127 Don't expose sensitive data in /api/v2/deposit_address?currency=btc
  app/api/api_v2/deposits.rb
  spec/api/api_v2/deposits_spec.rb
Labels: PR: Approved, v1.5

#1143 Ignore errors when generating deposit address (prevent working nodes from being skipped, fixes #1119).
  app/models/worker/deposit_coin_address.rb
Labels: PR: Approved, v1.7

#1136 Add correct validation for XRP addresses with destination tags (fixes #1125).
  lib/coin_api/xrp.rb
  spec/lib/coin_api/xrp_spec.rb
Labels: PR: Approved, v1.8

#1137 Add correct validation for XRP addresses with destination tags (fixes #1125).
  lib/coin_api/xrp.rb
  spec/lib/coin_api/xrp_spec.rb
Labels: PR: Approved, v1.6

#1138 Add correct validation for XRP addresses with destination tags (fixes #1125).
  lib/coin_api/xrp.rb
  spec/lib/coin_api/xrp_spec.rb
Labels: PR: Approved, v1.5

#1139 Add correct validation for XRP addresses with destination tags (fixes #1125).
  lib/coin_api/xrp.rb
  spec/lib/coin_api/xrp_spec.rb
Labels: PR: Approved, v1.7

#1144 Return 422 for fiats when calling GET /api/v2/deposit_address?currency=FIAT (closes #1135).
  app/api/api_v2/deposits.rb
  spec/api/api_v2/deposits_spec.rb
Labels: PR: Approved, v1.8

#1129 Don't expose sensitive data in /api/v2/deposit_address?currency=btc
  app/api/api_v2/deposits.rb
  spec/api/api_v2/deposits_spec.rb
Labels: PR: Approved, v1.6

#1149 Send CORS headers from API v2 ever on error (closes #1113).
  app/api/api_v2/cors/middleware.rb
  config/initializers/cors.rb
  spec/api/api_v2/cors_spec.rb
Labels: PR: Approved, v1.6

#1148 Send CORS headers from API v2 ever on error (closes #1113).
  app/api/api_v2/cors/middleware.rb
  config/initializers/cors.rb
  spec/api/api_v2/cors_spec.rb
Labels: PR: Approved, v1.5

#1146 Send CORS headers from API v2 ever on error
  app/api/api_v2/cors/middleware.rb
  config/initializers/cors.rb
  spec/api/api_v2/cors_spec.rb
Labels: PR: Approved, v1.8

#1150 Send CORS headers from API v2 ever on error (closes #1113).
  app/api/api_v2/cors/middleware.rb
  config/initializers/cors.rb
  spec/api/api_v2/cors_spec.rb
Labels: PR: Approved, v1.7

#1169 Add missing order type (fixes #1168).
  app/api/api_v2/named_params.rb
Labels: PR: Approved, v1.8

#1166 Output «reason» for API v2 exceptions & «debug_message» for Management API v1 exceptions (closes #1156).
  app/api/api_v2/errors.rb
  app/api/management_api_v1/exceptions/base.rb
  app/api/management_api_v1/mount.rb
  spec/api/api_v2/error_spec.rb
  spec/api/management_api_v1/error_spec.rb
Labels: PR: Approved, v1.6

#1164 Enqueue address generation if address is blank in GET /api/v2/deposit_address (issue #1157).
  app/controllers/private/deposits_controller.rb
  app/controllers/private/funds_controller.rb
  app/models/account.rb
  app/models/payment_address.rb
Labels: PR: Approved, v1.6

#1160 Output «reason» for API v2 exceptions & «debug_message» for Management API v1 exceptions (closes #1156).
  app/api/api_v2/errors.rb
  app/api/management_api_v1/exceptions/base.rb
  app/api/management_api_v1/mount.rb
  spec/api/api_v2/error_spec.rb
  spec/api/management_api_v1/error_spec.rb
Labels: PR: Approved, v1.8

#1161 Output «reason» for API v2 exceptions & «debug_message» for Management API v1 exceptions (closes #1156).
  app/api/api_v2/errors.rb
  app/api/management_api_v1/exceptions/base.rb
  app/api/management_api_v1/mount.rb
  spec/api/api_v2/error_spec.rb
  spec/api/management_api_v1/error_spec.rb
Labels: PR: Approved, v1.7

#1154 Validate new Bitcoin Cash CashAddr format and prevent errors like «Could not determine address version» (fixes #1151).
  app/controllers/admin/currencies_controller.rb
  app/models/currency.rb
  app/models/deposits/coin.rb
  app/models/market.rb
  app/models/payment_address.rb
  app/models/withdraws/coin.rb
  app/views/admin/currencies/show.html.erb
  config/templates/seed/currencies.yml.erb
  db/migrate/20180522105709_add_field_supports_cash_addr_format_to_currencies.rb
  db/schema.rb
  spec/factories/currencies.rb
  spec/models/withdraw_spec.rb
Labels: PR: Approved, v1.8

#1181 Add POST /api/v2/pusher/auth
  app/api/api_v2/mount.rb
  app/api/api_v2/pusher.rb
  spec/api/api_v2/pusher_spec.rb
Labels: PR: Approved, v1.8

#1174 Remove AccountVersion
  app/api/management_api_v1/withdraws.rb
  app/controllers/admin/members_controller.rb
  app/controllers/private/account_versions_controller.rb
  app/grids/account_versions_grid.rb
  app/models/account.rb
  app/models/account_version.rb
  app/models/deposit.rb
  app/models/market.rb
  app/models/order.rb
  app/models/withdraw.rb
  app/services/ordering.rb
  app/views/admin/members/show.html.erb
  app/views/private/account_versions/index.html.erb
  config/locales/server.en.yml
  config/locales/server.ru.yml
  config/routes.rb
  db/migrate/20180522165830_drop_account_versions.rb
  db/schema.rb
  spec/factories/withdraw.rb
  spec/models/account_spec.rb
  spec/models/account_version_spec.rb
  spec/models/matching/executor_spec.rb
  spec/models/order_spec.rb
  spec/models/withdraw_spec.rb
Labels: PR: Approved, v1.8

#1179 Make checkboxes work in admin panel (fixes #1158).
  app/controllers/admin/currencies_controller.rb
  app/controllers/admin/markets_controller.rb
Labels: PR: Approved, v1.8

#1185 Revert "Add PUSHER_CLUSTER"
  config/initializers/pusher.rb
  config/templates/application.yml.erb
Labels: PR: Approved, v1.8

#1191 Add Scout APM
  Gemfile
  Gemfile.lock
  config/application.rb
  config/environments/development.rb
  config/environments/test.rb
  config/scout_apm.yml
  config/templates/application.yml.erb
  spec/spec_helper.rb
Labels: PR: QA, v1.8

#855 Add support for Currency#enabled (aka #visible, closes #818)
  app/api/api_v2/deposits.rb
  app/api/api_v2/entities/member.rb
  app/api/api_v2/fees.rb
  app/api/api_v2/helpers.rb
  app/api/api_v2/markets.rb
  app/api/api_v2/solvency.rb
  app/api/api_v2/withdraws.rb
  app/assets/stylesheets/layouts/_header.scss
  app/controllers/admin/currencies_controller.rb
  app/controllers/admin/markets_controller.rb
  app/controllers/application_controller.rb
  app/controllers/concerns/order_creation.rb
  app/controllers/private/assets_controller.rb
  app/controllers/private/deposits_controller.rb
  app/controllers/private/funds_controller.rb
  app/controllers/private/markets_controller.rb
  app/controllers/private/withdraws_controller.rb
  app/models/account.rb
  app/models/currency.rb
  app/models/market.rb
  app/views/admin/currencies/index.html.erb
  app/views/admin/currencies/show.html.erb
  app/views/admin/markets/index.html.erb
  app/views/admin/markets/show.html.erb
  app/views/private/assets/_liability_tabs.html.erb
  app/views/private/assets/index.html.erb
  app/workers/worker/matching.rb
  config/templates/seed/currencies.yml.erb
  config/templates/seed/markets.yml.erb
  db/migrate/20180517084245_currency_visible_to_enabled.rb
  db/migrate/20180522121046_market_visible_to_enabled.rb
  db/schema.rb
  spec/api/api_v2/fees_spec.rb
  spec/api/api_v2/members_spec.rb
  spec/api/api_v2/sessions_spec.rb
  spec/api/api_v2/solvency_spec.rb
  spec/api/api_v2/withdraws_spec.rb
  spec/controllers/admin/currencies_controller_spec.rb
  spec/controllers/admin/markets_controller_spec.rb
  spec/factories/market.rb
  spec/models/account_spec.rb
  spec/models/market_spec.rb
Labels: PR: Approved, v1.8

#1200 Remove some extra queries when creating order. Improve indexes.
  app/api/api_v2/helpers.rb
  app/api/api_v2/named_params.rb
  app/models/account.rb
  app/models/currency.rb
  app/models/order.rb
  app/models/trade.rb
  db/migrate/20180524170927_improve_indexes.rb
  db/schema.rb
Labels: PR: Approved, v1.8

#1203 Protect sensitive information in admin panel (closes #1034)
  app/controllers/admin/currencies_controller.rb
  app/controllers/admin/markets_controller.rb
  app/models/currency.rb
  app/models/market.rb
  app/views/admin/currencies/show.html.erb
  app/views/admin/markets/show.html.erb
  db/migrate/20180525101406_improve_defaults_for_market.rb
  db/schema.rb
  spec/controllers/admin/currencies_controller_spec.rb
  spec/controllers/admin/markets_controller_spec.rb
  spec/factories/market.rb
  spec/models/market_spec.rb
  spec/models/order_spec.rb
  spec/services/ordering_spec.rb
Labels: PR: Approved, v1.8

#1195 Remove calls to Pusher, AMQP and other out from DB transactions. Refactor all Pusher#trigger_async calls! (closes #1188).
  app/controllers/application_controller.rb
  app/models/account.rb
  app/models/concerns/belongs_to_currency.rb
  app/models/deposit.rb
  app/models/member.rb
  app/models/order.rb
  app/models/order_ask.rb
  app/models/order_bid.rb
  app/models/trade.rb
  app/models/withdraw.rb
  app/services/ordering.rb
  app/trading/global.rb
  app/trading/matching/executor.rb
  app/workers/worker/deposit_coin_address.rb
  app/workers/worker/pusher_market.rb
  app/workers/worker/pusher_member.rb
  lib/daemons/global_state.rb
  spec/models/order_spec.rb
  spec/services/ordering_spec.rb
  spec/support/pusher.rb
Labels: PR: Approved, v1.8

#1202 Bring back legacy Peatio benchmarks (closes #1189)
  lib/benchmark/amqp_mock.rb
  lib/benchmark/execution.rb
  lib/benchmark/helpers.rb
  lib/benchmark/integration.rb
  lib/benchmark/matching.rb
  lib/benchmark/sweat_factory.rb
  lib/tasks/benchmark.rake
Labels: PR: Approved, v1.8

#1215 Use scope ordered instead of default_scope for Markets (closes #1115)
  app/api/api_v2/fees.rb
  app/api/api_v2/markets.rb
  app/api/api_v2/named_params.rb
  app/api/api_v2/tickers.rb
  app/controllers/admin/markets_controller.rb
  app/controllers/application_controller.rb
  app/controllers/private/markets_controller.rb
  app/models/market.rb
  lib/daemons/global_state.rb
  spec/controllers/admin/markets_controller_spec.rb
Labels: PR: Approved, v1.8

#1221 Make parameter «price» in API v2 order creation to be not mandatory (fixes #1213)
  app/api/api_v2/named_params.rb
Labels: PR: Approved, v1.7

#1220 Make parameter «price» in API v2 order creation to be not mandatory (fixes #1213)
  app/api/api_v2/named_params.rb
Labels: PR: Approved, v1.8

#1216 Member use uid instead of authentications.barong.first.uid (closes #1204)
  app/api/management_api_v1/entities/balance.rb
  app/api/management_api_v1/entities/deposit.rb
  app/api/management_api_v1/entities/withdraw.rb
  spec/api/management_api_v1/entities/deposit_spec.rb
  spec/api/management_api_v1/entities/withdraw_spec.rb
Labels: PR: Approved, v1.8

#1228 Use Member#uid instead of authentications.barong.first.uid (closes #1204)
  app/api/management_api_v1/entities/deposit.rb
  app/api/management_api_v1/entities/withdraw.rb
  app/api/management_api_v1/entities/withdraw_destination.rb
  app/models/member.rb
  spec/api/management_api_v1/entities/deposit_spec.rb
  spec/api/management_api_v1/entities/withdraw_destination_spec.rb
  spec/api/management_api_v1/entities/withdraw_spec.rb
Labels: PR: Approved, v1.6

#1227 Use Member#uid instead of authentications.barong.first.uid (closes #1204)
  app/api/management_api_v1/entities/deposit.rb
  app/api/management_api_v1/entities/withdraw.rb
  spec/api/management_api_v1/entities/deposit_spec.rb
  spec/api/management_api_v1/entities/withdraw_spec.rb
Labels: PR: Approved, v1.7

#1226 Make parameter «price» in API v2 order creation to be not mandatory (fixes #1213)
  app/api/api_v2/named_params.rb
Labels: PR: Approved, v1.5

#1224 Make parameter «price» in API v2 order creation to be not mandatory (fixes #1213)
  app/api/api_v2/named_params.rb
Labels: PR: Approved, v1.6
