Repository openware/peatio, pull requests merged in 2018-10, with the labels that each got.

#1711 K line daemon & API fix & specs improvement
  app/api/api_v2/helpers.rb
  app/api/api_v2/k.rb
  app/services/k_line_service.rb
  lib/daemons/k.rb
  spec/api/api_v2/k_spec.rb
Labels: PR: Approved, v1.9

#1718 Add env for secure ranger connection
  app/controllers/application_controller.rb
  config/templates/application.yml.erb
Labels: PR: Approved, v1.9

#1755 Remove warning from event api initializer
  config/initializers/event_api.rb
Labels: PR: Approved

#1724 [Security] Bump nokogiri from 1.8.4 to 1.8.5
  Gemfile.lock
Labels: PR: Review

#1717 Bump rack-attack from 5.2.0 to 5.4.1
  Gemfile
  Gemfile.lock
Labels: PR: Approved, v1.9

#1773 Added new table 'operations' & field 'code' to account model
  app/models/account.rb
  app/models/operation.rb
  db/migrate/20181023073145_add_code_to_accounts.rb
  db/migrate/20181023073457_create_operations.rb
  db/schema.rb
Labels: Feature: Accounting, PR: Approved

#1759 Expose ask_id & order_id in trade event of websocket API
  app/models/trade.rb
  docs/api/websocket_api.md
  spec/models/trade_spec.rb
Labels: PR: Approved, v1.8

#1782 Updating Ruby and Gems
  .gitignore
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
  spec/factories/authentications.rb
  spec/factories/blockchains.rb
  spec/factories/currencies.rb
  spec/factories/market.rb
  spec/factories/member.rb
  spec/factories/orders.rb
  spec/factories/wallet.rb
  spec/factories/withdraw.rb
Labels: PR: Approved, v1.9

#1722 Updated websocket api doc
  docs/api/websocket_api.md
Labels: PR: Changes needed, PR: WIP, v1.9
