Repository openware/peatio, pull requests merged in 2018-06, with the labels that each got.

#1233 Disable linked markets when currency is disabled (closes #1109).
  app/models/currency.rb
  spec/api/api_v2/fees_spec.rb
  spec/api/api_v2/markets_spec.rb
  spec/factories/market.rb
  spec/models/currency_spec.rb
  spec/models/market_spec.rb
  spec/models/worker/matching_spec.rb
Labels: PR: Approved, v1.8

#1236 Fix management API withdraw cancelation bug in 1.7 (closes #1232)
  app/api/management_api_v1/withdraws.rb
Labels: PR: Approved, v1.7

#1197 Add readiness & liveness probes
  app/controllers/public/health_controller.rb
  app/services/services/health_checker.rb
  config/routes.rb
Labels: PR: Approved, v1.8

#1244 Add missing index for authentication which is important for API v2 performance (closes #1237)
  app/models/authentication.rb
  db/migrate/20180605104154_add_missing_index_for_authentications.rb
  db/schema.rb
Labels: PR: Approved, v1.8

#1229 Fully support field Market#enabled (related to #817)
  app/api/api_v2/helpers.rb
  app/api/api_v2/tickers.rb
  app/controllers/application_controller.rb
  app/controllers/private/markets_controller.rb
  app/models/order.rb
  app/trading/matching/executor.rb
  app/trading/matching/limit_order.rb
  app/trading/matching/market_order.rb
  app/workers/worker/market_ticker.rb
  app/workers/worker/matching.rb
  app/workers/worker/slave_book.rb
  lib/daemons/global_state.rb
  lib/daemons/k.rb
  lib/market_constraint.rb
  spec/api/api_v2/fees_spec.rb
  spec/api/api_v2/markets_spec.rb
  spec/models/worker/matching_spec.rb
Labels: PR: Approved, v1.8

#1262 Expand db:setup command due to Rails bug (closes #1104)
  bin/setup
Labels: PR: Approved, v1.5

#1261 Expand db:setup command due to Rails bug (closes #1104)
  bin/setup
Labels: PR: Approved, v1.6

#1260 Expand db:setup command due to Rails bug (closes #1104)
  bin/setup
Labels: PR: Approved, v1.7

#1259 Expand db:setup command due to Rails bug (closes #1104)
  bin/setup
Labels: PR: Approved, v1.8

#1258 Don't accept deposits in case if deposit_confirmations set to zero (fixes #1248)
  app/models/worker/deposit_coin.rb
  lib/daemons/payment_transaction.rb
Labels: PR: Approved, v1.7

#1257 Don't accept deposits in case if deposit_confirmations set to zero (fixes #1248)
  app/workers/worker/deposit_coin.rb
  lib/daemons/payment_transaction.rb
Labels: PR: Approved, v1.8

#1269 Cache JWT key (don't initialize it at every request)
  app/api/api_v2/auth/utils.rb
  config/initializers/jwt.rb
  spec/support/api_helper.rb
Labels: PR: Approved, v1.8

#1263 Don't expose sensitive data from Faraday::Response#describe (closes #1155)
  config/initializers/faraday.rb
Labels: PR: Approved, v1.8

#1222 Add support for Barong 1.8 dynamic levels (closes #1134)
  app/api/api_v2/auth/jwt_authenticator.rb
  app/api/api_v2/deposits.rb
  app/api/api_v2/helpers.rb
  app/api/api_v2/orders.rb
  app/api/api_v2/trades.rb
  app/api/api_v2/withdraws.rb
  app/controllers/application_controller.rb
  app/controllers/private/base_controller.rb
  app/controllers/private/deposits_controller.rb
  app/controllers/private/funds_controller.rb
  app/controllers/private/withdraws_controller.rb
  app/enums/member/levels.rb
  app/models/member.rb
  config/initializers/member_levels.rb
  config/locales/server.en.yml
  config/templates/application.yml.erb
  db/migrate/20180530122201_change_members_level_type.rb
  db/schema.rb
  lib/peatio/feeders/member_feeder.rb
  lib/tasks/barong.rake
  spec/api/api_v2/auth/jwt_authenticator_spec.rb
  spec/api/api_v2/auth/middleware_spec.rb
  spec/api/api_v2/cors_spec.rb
  spec/api/api_v2/deposits_spec.rb
  spec/api/api_v2/entities/member_spec.rb
  spec/api/api_v2/helpers_spec.rb
  spec/api/api_v2/members_spec.rb
  spec/api/api_v2/orders_spec.rb
  spec/api/api_v2/pusher_spec.rb
  spec/api/api_v2/sessions_spec.rb
  spec/api/api_v2/solvency_spec.rb
  spec/api/api_v2/trades_spec.rb
  spec/api/api_v2/withdraws_spec.rb
  spec/api/management_api_v1/jwt_authentication_middleware_spec.rb
  spec/controllers/private/assets_controller_spec.rb
  spec/controllers/private/markets_controller_spec.rb
  spec/controllers/private/order_asks_controller_spec.rb
  spec/controllers/private/order_bids_controller_spec.rb
  spec/controllers/private/settings_controller_spec.rb
  spec/controllers/private/withdraws_controller_spec.rb
  spec/controllers/sessions_controller_spec.rb
  spec/factories/deposits.rb
  spec/factories/member.rb
  spec/factories/payment_addresses.rb
  spec/factories/withdraw.rb
  spec/features/admin/withdraw_spec.rb
  spec/features/market_spec.rb
  spec/features/market_trade_history_spec.rb
  spec/models/audit/transfer_audit_log_spec.rb
  spec/models/member_spec.rb
  spec/models/payment_address_spec.rb
  spec/models/trade_spec.rb
  spec/observers/transfer_observer_spec.rb
  spec/serializers/serializers/event_api/order_canceled_spec.rb
  spec/serializers/serializers/event_api/order_completed_spec.rb
  spec/serializers/serializers/event_api/order_created_spec.rb
  spec/serializers/serializers/event_api/order_updated_spec.rb
  spec/serializers/serializers/event_api/trade_completed_spec.rb
  spec/support/matching_helper.rb
Labels: PR: Approved, v1.8

#1256 Add documentation for Websocket API
  docs/api/websocket_api.md
Labels: PR: Review, v1.8

#1245 Ensure orders are put back to matching daemon order book (fixes disappearing orders, fixes order cancelation problem, optimizes number of queries to markets)
  app/models/order.rb
  app/trading/matching/constants.rb
  app/trading/matching/engine.rb
  app/trading/matching/executor.rb
  app/trading/matching/limit_order.rb
  app/trading/matching/market_order.rb
  app/trading/matching/price_level.rb
  app/workers/worker/market_ticker.rb
  app/workers/worker/matching.rb
  app/workers/worker/order_processor.rb
  app/workers/worker/slave_book.rb
  spec/models/matching/limit_order_spec.rb
Labels: PR: Approved, v1.8

#1286 Add missing input for ERC20 contract address
  app/views/admin/currencies/show.html.erb
Labels: PR: Approved, v1.8

#1284 Remove deprecated POST /api/v2/withdraws (closes #1178)
  app/api/api_v2/withdraws.rb
  spec/api/api_v2/withdraws_spec.rb
Labels: PR: Approved, v1.8

#1288 Fix Bunny errors which make WS API broken (closes #1279)
  app/api/api_v2/websocket_protocol.rb
  app/models/member.rb
Labels: PR: Approved, v1.7

#1283 Fix Bunny errors which make WS API broken (closes #1279)
  app/api/api_v2/websocket_protocol.rb
Labels: PR: Approved, v1.8

#1294 Fix Bunny errors which make WS API broken v1.5 (closes #1279)
  app/api/api_v2/websocket_protocol.rb
  app/models/member.rb
Labels: PR: Approved, v1.5

#1295 Handle missing Redis values in GET /api/v2/k (fixes #1281)
  app/api/api_v2/helpers.rb
  spec/api/api_v2/k_spec.rb
Labels: PR: Approved, v1.8

#1296 Handle missing Redis values in GET /api/v2/k (fixes #1281)
  app/api/api_v2/helpers.rb
  spec/api/api_v2/k_spec.rb
Labels: PR: Approved, v1.5

#1297 Handle missing Redis values in GET /api/v2/k (fixes #1281)
  app/api/api_v2/helpers.rb
  spec/api/api_v2/k_spec.rb
Labels: PR: Approved, v1.7

#1298 Handle missing Redis values in GET /api/v2/k (fixes #1281)
  app/api/api_v2/helpers.rb
  spec/api/api_v2/k_spec.rb
Labels: PR: Approved, v1.6

#1300 Fix Figaro warnings
  config/templates/application.yml.erb
Labels: PR: Approved, v1.8

#1301 Fix Google auth error (Error: invalid_request) which breaks local sign in for development
  .travis.yml
  ci/nginx/server.conf
  config/templates/application.yml.erb
  docs/setup-osx.md
  docs/setup-ubuntu.md
Labels: PR: Approved, v1.8

#1302 Fix Google auth error (Error: invalid_request) which breaks local sign in for development
  .travis.yml
  ci/nginx/server.conf
  config/templates/application.yml.erb
Labels: PR: Approved, v1.7

#1304 Fix Google auth error (Error: invalid_request) which breaks local sign in for development
  .travis.yml
  ci/nginx/server.conf
  config/templates/application.yml.erb
Labels: PR: Approved, v1.5

#1305 Fix Google auth error (Error: invalid_request) which breaks local sign in for development
  .travis.yml
  ci/nginx/server.conf
  config/templates/application.yml.erb
Labels: PR: Approved, v1.6

#1306 Prevent race conditions in withdraw worker + add rich logging.
  app/workers/worker/withdraw_coin.rb
Labels: PR: Approved, v1.8

#1307 Prevent race conditions in withdraw worker + add rich logging.
  app/models/worker/withdraw_coin.rb
Labels: PR: Approved, v1.7

#1308 Prevent race conditions in withdraw worker + add rich logging.
  app/models/worker/withdraw_coin.rb
Labels: PR: Approved, v1.5

#1309 Prevent race conditions in withdraw worker + add rich logging.
  app/models/worker/withdraw_coin.rb
Labels: PR: Approved, v1.6

#1310 Handle race conditions when registering member + add useful logging for OmniAuth sequence.
  app/api/api_v2/auth/jwt_authenticator.rb
  app/models/member.rb
Labels: PR: Approved, v1.8

#1312 Handle race conditions when registering member + add useful logging for OmniAuth sequence.
  app/api/api_v2/auth/jwt_authenticator.rb
  app/models/member.rb
Labels: PR: Approved, v1.5

#1313 Handle race conditions when registering member + add useful logging for OmniAuth sequence.
  app/api/api_v2/auth/jwt_authenticator.rb
  app/models/member.rb
Labels: PR: Approved, v1.7

#1314 Handle race conditions when registering member + add useful logging for OmniAuth sequence.
  app/api/api_v2/auth/jwt_authenticator.rb
  app/models/member.rb
Labels: PR: Approved, v1.6

#1299 Handle missing member & currency as validation errors preventing NoMethodError (closes #1272)
  app/models/concerns/fee_chargeable.rb
  app/models/withdraw.rb
  spec/models/withdraw_spec.rb
Labels: PR: Approved, v1.8

#1254 Improvements for legacy benchmark tools (closes #1249)
  Gemfile
  Gemfile.lock
  lib/benchmark/profiling.rb
  lib/benchmark/profiling/execution.rb
  lib/benchmark/profiling/matching.rb
  lib/tasks/benchmark.rake
Labels: PR: Review, v1.8

#1321 Add missing GET /api/v2/member_levels
  app/api/api_v2/member_levels.rb
  app/api/api_v2/mount.rb
  spec/api/api_v2/member_levels_spec.rb
Labels: PR: Approved, v1.8

#1344 Fix startup problems in benchmark (fixes #1329)
  lib/benchmark/helpers.rb
  lib/benchmark/sweat_factory.rb
Labels: PR: Approved, v1.8

#1355 Added ability to configure production db name from env
  config/database.yml
Labels: PR: Approved, v1.8

#1349 Add missing error messages in APIv2 (closes #1333)
  app/api/api_v2/helpers.rb
  spec/api/api_v2/deposits_spec.rb
  spec/api/api_v2/orders_spec.rb
  spec/api/api_v2/trades_spec.rb
  spec/api/api_v2/withdraws_spec.rb
Labels: PR: Approved, v1.7

#1348 Add missing error messages in APIv2 (closes #1333)
  app/api/api_v2/helpers.rb
  spec/api/api_v2/deposits_spec.rb
  spec/api/api_v2/orders_spec.rb
  spec/api/api_v2/trades_spec.rb
  spec/api/api_v2/withdraws_spec.rb
Labels: PR: Approved, v1.6

#1347 Add missing error messages in APIv2 (closes #1333)
  app/api/api_v2/helpers.rb
  spec/api/api_v2/deposits_spec.rb
  spec/api/api_v2/orders_spec.rb
  spec/api/api_v2/trades_spec.rb
  spec/api/api_v2/withdraws_spec.rb
Labels: PR: Approved, v1.5

#1343 Add missing error messages in APIv2 (closes #1333)
  app/api/api_v2/helpers.rb
  spec/api/api_v2/deposits_spec.rb
  spec/api/api_v2/orders_spec.rb
  spec/api/api_v2/trades_spec.rb
  spec/api/api_v2/withdraws_spec.rb
Labels: PR: Approved, v1.8

#1332 Fix XRP destination tag bug which breaks XRP withdraws (closes #1311)
  lib/coin_api/xrp.rb
  spec/lib/coin_api/xrp_spec.rb
Labels: PR: Approved, v1.8

#1339 Fix XRP destination tag bug which breaks XRP withdraws (closes #1311)
  lib/coin_api/xrp.rb
  spec/lib/coin_api/xrp_spec.rb
Labels: PR: Approved, v1.5

#1340 Fix XRP destination tag bug which breaks XRP withdraws (closes #1311)
  lib/coin_api/xrp.rb
  spec/lib/coin_api/xrp_spec.rb
Labels: PR: Approved, v1.6

#1322 Specs for WS protocol API
  Gemfile
  Gemfile.lock
  app/api/api_v2/web_socket_protocol.rb
  lib/daemons/websocket_api.rb
  spec/api/api_v2/websocket_protocol_spec.rb
  spec/support/socket_helper.rb
Labels: PR: Approved, v1.8

#1341 Fix XRP destination tag bug which breaks XRP withdraws (closes #1311)
  lib/coin_api/xrp.rb
  spec/lib/coin_api/xrp_spec.rb
Labels: PR: Approved, v1.7
