Repository openware/peatio, pull requests merged in 2018-04, with the labels that each got.

#771 Handle «state», «level» from Barong via OmniAuth (#724)
  app/models/member.rb
  spec/controllers/sessions_controller_spec.rb
  spec/spec_helper.rb
Labels: PR: Approved

#777 Remove unused config/templates/markets.yml
  config/templates/markets.yml.erb
Labels: PR: Approved

#773 Release 1.6.0
  docs/releases/1.6.0.md
  lib/peatio/version.rb
Labels: PR: Approved

#791 Fix «NoMethodError: undefined method `fetch' for #<OpenSSL::PKey::RSA>»
  config/initializers/jwt.rb
Labels: PR: Approved, PR: v1.6 and up

#783 Fix typos and update details for Ubuntu installation instruction
  docs/setup-ubuntu.md
Labels: PR: Approved

#762 Add gem «bullet»
  Gemfile
  Gemfile.lock
  config/environments/development.rb
  config/environments/test.rb
  spec/spec_helper.rb
Labels: PR: Approved, PR: v1.7 and up

#769 Add missing step for installation with PostgreSQL
  docs/databases/postgresql.md
Labels: PR: Approved, PR: v1.7 and up

#815 Set member API version to match Peatio version (fixes #810)
  app/api/api_v2/mount.rb
Labels: PR: Approved, PR: v1.7 and up

#807 Page should not be reloaded after creation of withdraw (fixes #798)
  app/assets/javascripts/funds/controllers/withdraw_hitstory_controller.js.coffee
  app/assets/javascripts/funds/controllers/withdraws_controller.js.coffee
Labels: PR: Approved, PR: v1.7 and up

#806 Get rid of errors «Undefined method may_*?» for deposits and withdraws (fixes #795).
  app/controllers/admin/deposits/fiats_controller.rb
  app/controllers/admin/withdraws/coins_controller.rb
  app/controllers/admin/withdraws/fiats_controller.rb
  app/models/deposits/fiat.rb
  app/models/withdraw.rb
  app/views/admin/deposits/fiats/new.html.erb
  app/views/admin/deposits/fiats/show.html.erb
  app/views/admin/withdraws/coins/show.html.erb
  app/views/admin/withdraws/fiats/show.html.erb
Labels: PR: Approved, PR: v1.6 and up

#751 Hide «unsecure protocol» warning from Bundler
  Gemfile
  Gemfile.lock
Labels: PR: Approved, PR: v1.7 and up

#781 Ability to manage market pairs using admin panel
  app/controllers/admin/markets_controller.rb
  app/models/admin/ability.rb
  app/models/market.rb
  app/views/admin/markets/index.html.erb
  app/views/admin/markets/show.html.erb
  app/views/layouts/admin.html.erb
  config/routes/admin.rb
  spec/controllers/admin/markets_controller_spec.rb
  spec/models/market_spec.rb
Labels: PR: Approved, PR: v1.7 and up

#832 Ignore .yarnrc and .cache
  .gitignore
Labels: PR: Approved, PR: v1.7 and up

#820 Remove Deposit#fund_extra, Deposit#fund_uid and usages (fixes #803)
  app/assets/javascripts/funds/models/deposit.js.coffee
  app/controllers/admin/deposits/fiats_controller.rb
  app/models/deposit.rb
  app/models/deposits/coin.rb
  app/models/deposits/fiat.rb
  app/views/admin/deposits/fiats/_table.html.erb
  app/views/admin/deposits/fiats/new.html.erb
  app/views/admin/deposits/fiats/show.html.erb
  config/locales/server.en.yml
  db/migrate/20180407082641_remove_fund_uid_extra_from_deposit.rb
  db/schema.rb
  public/templates/funds/deposit_fiat.html
  spec/factories/deposits.rb
Labels: PR: Approved, PR: v1.7 and up

#796 Fix failing specs with seed 59081 & 39808 (Capybara + DatabaseCleaner issue)
  Gemfile
  Gemfile.lock
  spec/spec_helper.rb
Labels: PR: Approved, PR: v1.7 and up

#816 Remove Withdraw#sn and all usages (fixes #802)
  app/assets/javascripts/funds/models/withdraw.js.coffee
  app/models/withdraw.rb
  app/models/withdraws/coin.rb
  app/models/withdraws/fiat.rb
  app/views/admin/withdraws/coins/show.html.erb
  app/views/admin/withdraws/fiats/show.html.erb
  config/locales/server.en.yml
  db/migrate/20180406185130_remove_sn_from_withdraw.rb
  db/schema.rb
  spec/models/withdraw_spec.rb
Labels: PR: Approved, PR: v1.7 and up

#797 Fixes & specs for updated BitGo API
  Gemfile.lock
  config/initializers/faraday.rb
  lib/coin_api/bit_go.rb
  spec/lib/coin_api/bit_go.rb
Labels: PR: Approved, PR: v1.5 and up

#833 Add ability to set uid and gid as docker build args
  Dockerfile
Labels: PR: Approved, PR: v1.7 and up

#794 Remove trading UI leftovers in Peatio
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js.coffee
  app/assets/javascripts/component_data/place_order.js.coffee
  app/assets/javascripts/component_mixin/item_list.js.coffee
  app/assets/javascripts/component_mixin/notification.js.coffee
  app/assets/javascripts/component_mixin/order_input.js.coffee
  app/assets/javascripts/component_ui/auto_window.js.coffee
  app/assets/javascripts/component_ui/flash_message.js.coffee
  app/assets/javascripts/component_ui/key_bind.js.coffee
  app/assets/javascripts/component_ui/order_price.js.coffee
  app/assets/javascripts/component_ui/order_total.js.coffee
  app/assets/javascripts/component_ui/order_volume.js.coffee
  app/assets/javascripts/component_ui/push_button.js.coffee
  app/assets/javascripts/component_ui/range_switch.js.coffee
  app/assets/javascripts/component_ui/switch.js.coffee
  app/assets/javascripts/funds.js.coffee
  app/assets/javascripts/helpers/formatter.js.coffee
  app/assets/javascripts/highcharts/config.js.coffee
  app/assets/javascripts/highcharts/technical_indicators.js
  app/assets/javascripts/lib/notifier.js.coffee
  app/assets/javascripts/lib/sfx.js.coffee
  app/assets/javascripts/templates/flash_message.jst.ejs
  app/assets/javascripts/templates/hint_order_success.jst.ejs
  app/assets/javascripts/templates/hint_order_warning.jst.ejs
  app/assets/javascripts/templates/market_trade.jst.ejs
  app/assets/javascripts/templates/my_trade.jst.ejs
  app/assets/javascripts/templates/order_active.jst.ejs
  app/assets/javascripts/templates/order_book_ask.jst.ejs
  app/assets/javascripts/templates/order_book_bid.jst.ejs
  app/assets/javascripts/templates/order_done.jst.ejs
  app/assets/javascripts/templates/tooltip.jst.ejs
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/api_v2.scss
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/custom/market.scss
  app/assets/stylesheets/features/_market.scss
  app/assets/stylesheets/features/_market_chart.scss
  app/assets/stylesheets/layouts/_header.scss
  app/assets/stylesheets/market_light.scss
  app/assets/stylesheets/vars/_bootstrap_market.scss
  app/assets/stylesheets/vars/_custom.scss
  app/assets/stylesheets/vars/_market.scss
  app/assets/stylesheets/vars/_market_light.scss
  app/views/shared/_header.html.erb
  app/views/shared/_header_account_balance.html.erb
  app/views/shared/market/_chart.html.erb
  app/views/shared/market/_market_sel.html.erb
  app/views/shared/market/_ticker.html.erb
  vendor/assets/javascripts/bootstrap-switch.min.js
  vendor/assets/stylesheets/bootstrap-switch.min.css
Labels: PR: Approved, PR: v1.7 and up

#839 Add missing Private::DepositsController#destroy action (couldn't cancel deposit)
  app/controllers/private/deposits_controller.rb
  config/locales/client.en.yml
  config/routes.rb
Labels: PR: Approved, PR: v1.5 and up

#856 Enqueue new matching engine after market create (closes #840 #841)
  app/models/market.rb
  app/models/worker/matching.rb
Labels: PR: Approved, PR: WIP

#844 Remove custom swagger UI leftovers
  app/assets/javascripts/api_v2.js
  app/assets/stylesheets/api_v2.scss
  app/assets/stylesheets/swagger-ui/highlight.default.css
  app/assets/stylesheets/swagger-ui/screen.css
  app/controllers/documents_controller.rb
  app/views/layouts/api_v2.html.erb
  config/initializers/assets.rb
  config/routes.rb
Labels: PR: Approved, PR: v1.7 and up

#874 Don't create payment addresses for fiat currency. Additional checks for address generation.
  app/controllers/private/deposits_controller.rb
  app/controllers/private/funds_controller.rb
  app/models/account.rb
  app/models/payment_address.rb
  app/models/worker/deposit_coin_address.rb
  spec/models/account_spec.rb
Labels: PR: Approved, PR: v1.5 and up

#870 Fix some typos in README.
  README.md
Labels: PR: Approved, PR: v1.7 and up

#836 Remove gem Slim
  Gemfile
  Gemfile.lock
  app/views/documents/websocket_api.html.slim
Labels: PR: Approved, PR: v1.7 and up

#860 Finish Capybara tests in features/admin/withdraw_spec.rb
  config/locales/server.en.yml
  spec/features/admin/withdraw_spec.rb
Labels: PR: Approved, PR: v1.7 and up

#825 Ability to manage currencies using admin panel
  app/controllers/admin/currencies_controller.rb
  app/models/admin/ability.rb
  app/models/currency.rb
  app/views/admin/currencies/index.html.erb
  app/views/admin/currencies/show.html.erb
  app/views/layouts/admin.html.erb
  config/routes/admin.rb
  spec/controllers/admin/currencies_controller_spec.rb
  spec/controllers/admin/markets_controller_spec.rb
Labels: PR: Approved, PR: v1.7 and up

#850 Remove mailing stuff from Peatio (closes #758)
  app/helpers/mailer_helper.rb
  app/mailers/base_mailer.rb
  app/mailers/deposit_mailer.rb
  app/mailers/system_mailer.rb
  app/mailers/withdraw_mailer.rb
  app/models/amqp_queue.rb
  app/models/deposit.rb
  app/models/withdraw.rb
  app/models/worker/email_notification.rb
  app/models/worker/order_processor.rb
  app/models/worker/trade_executor.rb
  app/views/deposit_mailer/accepted.html.erb
  app/views/layouts/mailers/application.html.erb
  app/views/layouts/mailers/system.html.erb
  app/views/system_mailer/balance_warning.text.erb
  app/views/system_mailer/daily_stats.html.erb
  app/views/system_mailer/order_processor_error.text.erb
  app/views/system_mailer/trade_execute_error.text.erb
  app/views/withdraw_mailer/processing.html.erb
  app/views/withdraw_mailer/submitted.html.erb
  app/views/withdraw_mailer/succeed.html.erb
  app/views/withdraw_mailer/withdraw_state.html.erb
  config/amqp.yml
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/email_validator.rb
  config/locales/server.en.yml
  config/templates/application.yml.erb
  docs/peatio/mailer.md
  lib/daemons/daemons.god
  lib/peatio/tasks/mailer.rake
  lib/tasks/stats.rake
  spec/mailers/deposit_mailer_spec.rb
  spec/mailers/withdraw_mailer_spec.rb
Labels: PR: Approved, PR: v1.7 and up

#826 Multi-fiat support
  app/api/api_v2/entities/market.rb
  app/assets/javascripts/funds/controllers/deposits_controller.js.coffee
  app/assets/javascripts/funds/controllers/withdraws_controller.js.coffee
  app/controllers/application_controller.rb
  app/models/currency.rb
  app/views/private/assets/_fiat_assets.html.erb
  app/views/private/history/trades.html.erb
  config/initializers/display_currency.rb
  config/locales/server.en.yml
  config/templates/application.yml.erb
  lib/benchmark/helpers.rb
  lib/benchmark/sweat_factory.rb
  lib/peatio.rb
  lib/tasks/emu.rake
  lib/tasks/order.rake
  lib/tasks/replay.rake
  lib/tasks/stats.rake
  public/templates/funds/deposit.html
  public/templates/funds/deposit_fiat.html
  public/templates/funds/withdraw.html
  public/templates/funds/withdraw_fiat.html
  spec/spec_helper.rb
Labels: PR: Approved, PR: v1.7 and up

#880 Various UI fixes (Bootstrap 4 migration)
  app/assets/javascripts/admin.js
  app/assets/javascripts/sidebar.js
  app/assets/javascripts/theme/sidebar.js
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/admin/sidebar.scss
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/theme/layout.scss
  app/assets/stylesheets/theme/theme.scss
  app/views/admin/deposits/fiats/show.html.erb
  app/views/admin/members/show.html.erb
  app/views/admin/withdraws/coins/show.html.erb
  app/views/layouts/_admin_header.html.erb
  app/views/layouts/_admin_sidebar.html.erb
  app/views/layouts/admin.html.erb
  app/views/layouts/application.html.erb
  app/views/shared/admin/_account.html.erb
  app/views/shared/admin/_member.html.erb
  package-lock.json
  package.json
  yarn.lock
Labels: PR: Approved, PR: v1.7 and up

#887 Update sidebar.js (remove ES6 syntax)
  app/assets/javascripts/theme/sidebar.js
Labels: PR: Approved, PR: v1.7 and up

#881 Embed «DepositChannel» in «Currency»
  .gitignore
  app/assets/javascripts/funds/controllers/deposits_controller.js.coffee
  app/assets/javascripts/funds/funds.js.coffee
  app/assets/javascripts/funds/models/account.js.coffee
  app/assets/javascripts/funds/models/deposit_channel.js.coffee
  app/controllers/admin/currencies_controller.rb
  app/controllers/private/funds_controller.rb
  app/models/currency.rb
  app/models/deposit.rb
  app/models/deposit_channel.rb
  app/models/worker/deposit_coin.rb
  app/views/admin/currencies/show.html.erb
  app/views/layouts/_admin_sidebar.html.erb
  app/views/private/funds/index.json.jbuilder
  config/locales/server.en.yml
  config/templates/deposit_channels.yml.erb
  db/migrate/20180417085823_migrate_deposit_channels_to_currency.rb
  db/schema.rb
  lib/daemons/coins.rb
  lib/daemons/payment_transaction.rb
  spec/factories/currencies.rb
  spec/fixtures/deposit_channels.yml
  spec/models/deposit_channel_spec.rb
Labels: PR: Approved, PR: v1.7 and up

#884 Embed «WithdrawChannel» in «Currency»
  .gitignore
  app/assets/javascripts/funds/controllers/withdraws_controller.js.coffee
  app/assets/javascripts/funds/funds.js.coffee
  app/assets/javascripts/funds/models/account.js.coffee
  app/assets/javascripts/funds/models/withdraw_channel.js.coffee
  app/controllers/admin/currencies_controller.rb
  app/controllers/private/funds_controller.rb
  app/models/currency.rb
  app/models/withdraw.rb
  app/models/withdraw_channel.rb
  app/views/admin/currencies/show.html.erb
  app/views/layouts/_admin_sidebar.html.erb
  app/views/private/funds/index.json.jbuilder
  config/locales/server.en.yml
  config/templates/withdraw_channels.yml.erb
  db/migrate/20180417111305_migrate_withdraw_channels_to_currency.rb
  db/schema.rb
  spec/controllers/admin/currencies_controller_spec.rb
  spec/factories/currencies.rb
  spec/fixtures/withdraw_channels.yml
Labels: PR: Approved, PR: v1.7 and up

#892 Fix error in OrderBook entity caused by class loading order bug in Grape
  app/api/api_v2/entities/order_book.rb
Labels: PR: Approved, PR: v1.5 and up

#895 Add ability to set uid and gid as docker build args (#833)
  Dockerfile
Labels: PR: Approved

#885 Gemfile optimization: eventmachine & em-websocket
  Gemfile
  lib/daemons/websocket_api.rb
Labels: PR: Approved, PR: v1.7 and up

#901 Add missing «Currencies» rubric at admin panel
  app/views/layouts/_admin_sidebar.html.erb
Labels: PR: Approved, PR: v1.7 and up

#879 Store fee in order model
  app/models/order.rb
  app/models/order_ask.rb
  app/models/order_bid.rb
  db/migrate/20180416160438_add_fee_to_orders.rb
  db/schema.rb
  spec/models/order_spec.rb
Labels: PR: Approved, PR: v1.7 and up

#909 Add rspec-retry (attempting to resolve timeout issue #878)
  Gemfile
  Gemfile.lock
  spec/spec_helper.rb
Labels: PR: Approved, PR: v1.5

#898 Update omniauth-barong version
  Gemfile
  Gemfile.lock
Labels: PR: Approved, PR: v1.6

#917 Various design fixes (Bootstrap 4 migration)
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/vars/_bootstrap.scss
  app/views/admin/currencies/index.html.erb
  app/views/admin/currencies/show.html.erb
  app/views/admin/members/index.html.erb
  app/views/admin/members/show.html.erb
  app/views/shared/_header.html.erb
  app/views/shared/_header_profile_setting.html.erb
  app/views/shared/admin/_account.html.erb
  app/views/shared/admin/_member_accounts.html.erb
Labels: PR: Approved, PR: v1.7 and up

#956 Limit trading fee to 50%
  app/models/market.rb
  db/migrate/20180425094920_limit_trading_fee.rb
  db/schema.rb
Labels: PR: Approved, v1.8

#955 Limit trading fee to 50%
  app/models/market.rb
  db/migrate/20180425094920_limit_trading_fee.rb
  db/schema.rb
Labels: PR: Approved, v1.7

#954 Limit trading fee to 50%
  app/models/market.rb
  db/migrate/20180425094920_limit_trading_fee.rb
  db/schema.rb
Labels: PR: Approved, v1.6

#968 Add missing translations for withdraw states
  config/locales/client.en.yml
  config/locales/client.ru.yml
  config/locales/server.en.yml
Labels: PR: Approved, v1.6

#966 Add missing translations for withdraw states
  config/locales/client.en.yml
  config/locales/client.ru.yml
  config/locales/server.en.yml
Labels: PR: Approved, v1.7

#965 Add missing «Prepared» translation (closes #875)
  config/locales/client.en.yml
  config/locales/client.ru.yml
  config/locales/server.en.yml
Labels: PR: Approved, v1.8

#963 Submit amounts as strings, update String#to_d to match Rails behaviour, add specs for extremely precise amounts (fixes issue #911, 0.00000001 problem).
  config/initializers/string.rb
  public/templates/funds/_coin_withdraw.html
  public/templates/funds/withdraw_fiat.html
  spec/api/management_api_v1/deposits_spec.rb
  spec/api/management_api_v1/withdraws_spec.rb
  spec/controllers/private/withdraws_controller_spec.rb
Labels: PR: Approved, v1.6

#962 Submit amounts as strings, update String#to_d to match Rails behaviour, add specs for extremely precise amounts (fixes issue #911, 0.00000001 problem).
  config/initializers/string.rb
  public/templates/funds/_coin_withdraw.html
  public/templates/funds/withdraw_fiat.html
  spec/api/management_api_v1/deposits_spec.rb
  spec/api/management_api_v1/withdraws_spec.rb
  spec/controllers/private/withdraws_controller_spec.rb
Labels: PR: Approved, v1.7

#961 Retry on all Capybara errors in tests (issue #957)
  spec/spec_helper.rb
Labels: PR: Approved, v1.8

#960 Retry on all Capybara errors in tests (issue #957)
  spec/spec_helper.rb
Labels: PR: Approved, v1.7

#959 Retry on all Capybara errors in tests (issue #957)
  spec/spec_helper.rb
Labels: PR: Approved, v1.6

#958 Submit amounts as strings, update String#to_d to match Rails behaviour, add specs for extremely precise amounts (fixes issue #911).
  config/initializers/string.rb
  public/templates/funds/_coin_withdraw.html
  public/templates/funds/withdraw_fiat.html
  spec/api/management_api_v1/deposits_spec.rb
  spec/api/management_api_v1/withdraws_spec.rb
  spec/controllers/private/withdraws_controller_spec.rb
Labels: PR: Approved, v1.8

#969 Always use legacy Bitcoin Cash addresses (fixes #704)
  Gemfile
  Gemfile.lock
  db/migrate/20180425152420_convert_to_legacy_bitcoin_cash_addresses.rb
  db/schema.rb
  lib/coin_api/bch.rb
  lib/coin_api/btc.rb
Labels: PR: Approved, v1.8

#971 Always use legacy Bitcoin Cash addresses (fixes #704)
  Gemfile
  Gemfile.lock
  db/migrate/20180425152420_convert_to_legacy_bitcoin_cash_addresses.rb
  db/schema.rb
  lib/coin_api/bch.rb
  lib/coin_api/btc.rb
Labels: PR: Approved, v1.5

#972 Always use legacy Bitcoin Cash addresses (fixes #704)
  Gemfile
  Gemfile.lock
  db/migrate/20180425152420_convert_to_legacy_bitcoin_cash_addresses.rb
  db/schema.rb
  lib/coin_api/bch.rb
  lib/coin_api/btc.rb
Labels: PR: Approved, v1.6

#973 Always use legacy Bitcoin Cash addresses (fixes #704)
  Gemfile
  Gemfile.lock
  db/migrate/20180425152420_convert_to_legacy_bitcoin_cash_addresses.rb
  db/schema.rb
  lib/coin_api/bch.rb
  lib/coin_api/btc.rb
Labels: PR: Approved, v1.7

#976 Remove «--depth=1» from git clone in bin/install_plugins (fixes #975)
  bin/install_plugins
Labels: PR: Approved, v1.8

#977 Remove «--depth=1» from git clone in bin/install_plugins (fixes #975)
  bin/install_plugins
Labels: PR: Approved, v1.7

#978 Remove «--depth=1» from git clone in bin/install_plugins (fixes #975)
  bin/install_plugins
Labels: PR: Approved, v1.6

#979 Remove «--depth=1» from git clone in bin/install_plugins (fixes #975)
  bin/install_plugins
Labels: PR: Approved, v1.5

#989 Typos in docs/specs/event_api
  docs/specs/event_api.md
Labels: PR: Approved, v1.8

#988 Remove ActiveYAML stuff
  Gemfile
  Gemfile.lock
  app/helpers/application_helper.rb
  app/models/active_yaml_base.rb
  app/models/trade.rb
  config/initializers/activerecord.rb
Labels: PR: Approved, v1.8

#986 Experimental fix for BitGo ETH address generation
  app/models/worker/deposit_coin_address.rb
  db/migrate/20180425224307_change_wallet_id_to_address_id.rb
  lib/coin_api.rb
  lib/coin_api/bit_go.rb
  lib/coin_api/btc.rb
  lib/coin_api/eth.rb
  lib/coin_api/xrp.rb
  spec/lib/coin_api/bit_go.rb
Labels: PR: Approved, v1.6

#985 Experimental fix for BitGo ETH address generation
  app/models/worker/deposit_coin_address.rb
  db/migrate/20180425224307_change_wallet_id_to_address_id.rb
  lib/coin_api.rb
  lib/coin_api/bit_go.rb
  lib/coin_api/btc.rb
  lib/coin_api/eth.rb
  lib/coin_api/xrp.rb
  spec/lib/coin_api/bit_go.rb
Labels: PR: Approved, v1.7

#984 Experimental fix for BitGo ETH address generation
  app/models/worker/deposit_coin_address.rb
  db/migrate/20180425224307_change_wallet_id_to_address_id.rb
  lib/coin_api.rb
  lib/coin_api/bit_go.rb
  lib/coin_api/btc.rb
  lib/coin_api/eth.rb
  lib/coin_api/xrp.rb
  spec/lib/coin_api/bit_go.rb
Labels: PR: Approved, v1.8

#983 Update API docs
  docs/api/management_api_v1.md
  docs/api/member_api_v2.md
Labels: PR: Approved, v1.7

#982 Update API docs
  app/api/api_v2/mount.rb
  docs/api/management_api_v1.md
  docs/api/member_api_v2.md
Labels: PR: Approved, v1.6

#980 Ability to establish cookie-based session using API
  app/api/api_v2/cors/middleware.rb
  app/api/api_v2/sessions.rb
  app/controllers/concerns/session_utils.rb
  config/initializers/redis_store.rb
  config/initializers/session_store.rb
  config/templates/application.yml.erb
  docs/api/management_api_v1.md
  docs/api/member_api_v2.md
  spec/api/api_v2/sessions_spec.rb
Labels: PR: Approved, v1.8

#933 Experimental fix for BitGo ETH address generation
  app/models/worker/deposit_coin_address.rb
  db/migrate/20180425224307_change_wallet_id_to_address_id.rb
  db/schema.rb
  lib/coin_api.rb
  lib/coin_api/bit_go.rb
  lib/coin_api/btc.rb
  lib/coin_api/eth.rb
  lib/coin_api/xrp.rb
  spec/lib/coin_api/bit_go.rb
Labels: PR: Approved, v1.5

#994 Fix UI issues (master)
  app/assets/stylesheets/admin.scss
  app/views/admin/markets/show.html.erb
Labels: PR: Approved, v1.8

#993 Fix UI issues (1.7)
  app/assets/stylesheets/admin.scss
  app/views/admin/markets/show.html.erb
Labels: PR: Approved, v1.7

#992 #883 Unexpected URL for fiat deposit page v1.8
  app/controllers/admin/deposits/fiats_controller.rb
  app/views/admin/deposits/fiats/new.html.erb
Labels: PR: Approved, v1.8

#991 #883 Unexpected URL for fiat deposit page v1.7
  app/controllers/admin/deposits/fiats_controller.rb
  app/views/admin/deposits/fiats/new.html.erb
Labels: PR: Approved, v1.7

#915 Deposit fee feature (closes #886)
  app/controllers/admin/currencies_controller.rb
  app/models/concerns/fee_chargeable.rb
  app/models/currency.rb
  app/models/deposit.rb
  app/models/withdraw.rb
  app/views/admin/currencies/show.html.erb
  config/templates/seed/currencies.yml.erb
  db/migrate/20180419122223_add_deposit_fee_to_currencies.rb
  db/schema.rb
  public/templates/funds/_deposit_coin_history.html
  public/templates/funds/deposit_fiat.html
  spec/controllers/admin/currencies_controller_spec.rb
  spec/models/currency_spec.rb
  spec/models/deposit_spec.rb
  spec/models/withdraw_spec.rb
Labels: PR: Approved, v1.8
