Repository openware/peatio, pull requests merged in 2018-07, with the labels that each got.

#1370 Validate market param (closes #1353)
  app/api/api_v2/named_params.rb
  spec/api/api_v2/order_books_spec.rb
  spec/api/api_v2/orders_spec.rb
  spec/api/api_v2/trades_spec.rb
Labels: PR: Approved, v1.8

#1335 Optimizations for trade executor
  app/models/account.rb
  app/models/order.rb
  app/models/order_ask.rb
  app/models/order_bid.rb
  app/trading/matching/constants.rb
  app/trading/matching/executor.rb
  config/initializers/mysql2.rb
  spec/models/order_spec.rb
Labels: PR: Approved, v1.8

#1377 Document every daemon
  docs/daemons.md
Labels: PR: Approved, v1.9

#1386 Update sprockets gem
  Gemfile.lock
Labels: PR: Approved

#1390 Remove solvency feature
  Gemfile
  Gemfile.lock
  app/api/api_v2/entities/solvency/partial_tree.rb
  app/api/api_v2/entities/solvency/proof.rb
  app/api/api_v2/mount.rb
  app/api/api_v2/solvency.rb
  app/controllers/admin/proofs_controller.rb
  app/controllers/private/assets_controller.rb
  app/grids/proofs_grid.rb
  app/helpers/private/assets_helper.rb
  app/models/account.rb
  app/models/admin/ability.rb
  app/models/partial_tree.rb
  app/models/proof.rb
  app/views/admin/proofs/edit.html.erb
  app/views/admin/proofs/index.html.erb
  app/views/layouts/_admin_sidebar.html.erb
  app/views/private/assets/_coin_assets.html.erb
  app/views/private/assets/_fiat_assets.html.erb
  app/views/private/assets/_liability_data.html.erb
  app/views/private/assets/_liability_proof.html.erb
  app/views/private/assets/_liability_tabs.html.erb
  app/views/private/assets/index.html.erb
  app/views/shared/_header.html.erb
  bin/setup
  config/initializers/datagrid/filters/date_time_filter.rb
  config/locales/server.en.yml
  config/routes.rb
  config/routes/admin.rb
  db/migrate/20180704103131_remove_solvency.rb
  db/schema.rb
  docs/ops/deploy/ubuntu.md
  docs/setup-osx.md
  docs/setup-ubuntu.md
  lib/datagrid/column_i18n.rb
  lib/datagrid/naming.rb
  lib/tasks/solvency.rake
  spec/api/api_v2/solvency_spec.rb
  spec/controllers/private/assets_controller_spec.rb
  spec/factories/partial_trees.rb
  spec/factories/proofs.rb
  spec/helpers/private/assets_helper_spec.rb
  spec/models/partial_tree_spec.rb
  spec/models/proof_spec.rb
Labels: PR: Approved

#1393 Update ffi to 1.9.25
  Gemfile.lock
Labels: PR: Approved

#1368 Add 24 hours currency trades API endpoint (closes #1356)
  app/api/api_v2/currencies.rb
  app/api/api_v2/mount.rb
  app/models/market.rb
  app/models/trade.rb
  spec/api/api_v2/currencies_spec.rb
  spec/api/api_v2/markets_spec.rb
  spec/factories/market.rb
  spec/models/market_spec.rb
  spec/spec_helper.rb
Labels: PR: Approved, v1.9

#1420 Added 24 hours currency trades API endpoint (#1368)
  app/api/api_v2/currencies.rb
  app/api/api_v2/mount.rb
  app/models/market.rb
  app/models/trade.rb
  app/trading/global.rb
  spec/api/api_v2/currencies_spec.rb
  spec/api/api_v2/markets_spec.rb
  spec/factories/market.rb
  spec/models/market_spec.rb
  spec/spec_helper.rb
Labels: v1.8

#1391 Remove auditing system (you have to use Event API to do audits now)
  Gemfile
  Gemfile.lock
  app/models/audit/audit_log.rb
  app/models/audit/transfer_audit_log.rb
  app/models/deposit.rb
  app/models/withdraw.rb
  app/observers/audit_observer.rb
  app/observers/transfer_observer.rb
  app/workers/worker/withdraw_coin.rb
  config/application.rb
  db/migrate/20180704115110_remove_auditing.rb
  db/schema.rb
  spec/models/audit/transfer_audit_log_spec.rb
  spec/observers/transfer_observer_spec.rb
Labels: PR: Approved

#1451 Change Default Domain To peatio.tech
  .travis.yml
  ci/nginx/server.conf
  config/templates/application.yml.erb
  docs/releases/1.5.0.md
Labels: PR: Approved, v1.5

#1454 Change Default Domain To peatio.tech
  .travis.yml
  ci/nginx/server.conf
  config/templates/application.yml.erb
  docs/api/authenticating_in_management_api_v1.md
  docs/releases/1.5.0.md
  docs/setup-osx.md
  docs/setup-ubuntu.md
Labels: PR: Approved, v1.8

#1453 Change Default Domain To peatio.tech
  .travis.yml
  ci/nginx/server.conf
  config/templates/application.yml.erb
  docs/api/authenticating_in_management_api_v1.md
  docs/releases/1.5.0.md
Labels: PR: Approved, v1.7

#1452 Change Default Domain To peatio.tech
  .travis.yml
  ci/nginx/server.conf
  config/templates/application.yml.erb
  docs/api/authenticating_in_management_api_v1.md
  docs/releases/1.5.0.md
Labels: PR: Approved, v1.6

#1450 Change Default Domain To peatio.tech (closes #1443)
  .travis.yml
  ci/nginx/server.conf
  config/templates/application.yml.erb
  docs/api/authenticating_in_management_api_v1.md
  docs/releases/1.5.0.md
  docs/setup-osx.md
  docs/setup-ubuntu.md
Labels: PR: Approved, v1.9

#1433 Add API endpoint for currencies
  app/api/api_v2/currencies.rb
  app/api/api_v2/entities/currency.rb
  docs/api/member_api_v2.md
  spec/api/api_v2/currencies_spec.rb
Labels: PR: Approved, v1.9

#1458 Include PublishToRabbitMQ GenerateJWT Event API middlewares by default (closes #1457)
  config/initializers/event_api.rb
  config/templates/application.yml.erb
  spec/spec_helper.rb
Labels: PR: Approved, v1.9

#1442 Event API serializers imporvements (closes #1376, #1396)
  app/models/account.rb
  app/serializers/serializers/event_api/order_event.rb
  app/serializers/serializers/event_api/trade_completed.rb
  docs/specs/event_api.md
  spec/serializers/serializers/event_api/order_canceled_spec.rb
  spec/serializers/serializers/event_api/order_completed_spec.rb
  spec/serializers/serializers/event_api/order_created_spec.rb
  spec/serializers/serializers/event_api/order_updated_spec.rb
  spec/serializers/serializers/event_api/trade_completed_spec.rb
Labels: PR: Approved, v1.8

#1462 Add API endpoint for currencies (#1433)
  app/api/api_v2/currencies.rb
  app/api/api_v2/entities/currency.rb
  docs/api/member_api_v2.md
  spec/api/api_v2/currencies_spec.rb
Labels: PR: Approved, v1.8

#1444 Bitcoin Blockchain Service
  app/services/blockchain_service.rb
  app/services/blockchain_service/bitcoin.rb
  app/services/blockchain_service/ethereum.rb
  config/templates/seed/blockchains.yml.erb
  config/templates/seed/currencies.yml.erb
  lib/client/bitcoin.rb
  lib/daemons/blockchain.rb
  spec/factories/blockchains.rb
  spec/factories/currencies.rb
  spec/resources/bitcoin-data/1354419-1354420.json
  spec/resources/bitcoin-data/1354649-1354651.json
  spec/services/blockchain_service/bitcoin_spec.rb
  spec/spec_helper.rb
Labels: Feature: BlockchainService, PR: Approved, v1.9

#1474 Improve BlockchainService logger. Wallet & Blockchain bugfixes
  app/models/wallet.rb
  app/services/blockchain_service/bitcoin.rb
  app/services/blockchain_service/ethereum.rb
  lib/daemons/blockchain.rb
Labels: Feature: BlockchainService, PR: Approved

#1473 Add blockchain key in currency
  app/controllers/admin/currencies_controller.rb
  app/views/admin/blockchains/show.html.erb
  app/views/admin/currencies/show.html.erb
  app/views/admin/wallets/show.html.erb
Labels: Feature: BlockchainService, PR: Approved, v1.9

#1476 Remove CoinAPI & daemons. Rename Client to BlockchainClient
  app/models/currency.rb
  app/models/withdraws/coin.rb
  app/services/blockchain_service.rb
  app/workers/worker/deposit_coin.rb
  app/workers/worker/deposit_coin_address.rb
  app/workers/worker/withdraw_coin.rb
  lib/blockchain_client.rb
  lib/blockchain_client/bitcoin.rb
  lib/blockchain_client/ethereum.rb
  lib/coin_api/bch.rb
  lib/coin_api/bit_go.rb
  lib/coin_api/btc.rb
  lib/coin_api/dash.rb
  lib/coin_api/erc20.rb
  lib/coin_api/eth.rb
  lib/coin_api/ltc.rb
  lib/coin_api/xrp.rb
  lib/daemons/coins.rb
  lib/daemons/hot_wallets.rb
  lib/daemons/payment_transaction.rb
  spec/lib/coin_api/bch_spec.rb
  spec/lib/coin_api/bit_go.rb
  spec/lib/coin_api/btc_spec.rb
  spec/lib/coin_api/erc20_spec.rb
  spec/lib/coin_api/eth_spec.rb
  spec/lib/coin_api/xrp_spec.rb
  spec/models/withdraw_spec.rb
  spec/models/worker/deposit_coin_spec.rb
  spec/services/blockchain_service/bitcoin_spec.rb
  spec/services/blockchain_service/ethereum_spec.rb
  spec/workers/deposit_coin_address.rb
Labels: Feature: BlockchainService, PR: QA, v1.9

#1478 Add gateway & max_balance to wallets
  app/models/wallet.rb
  config/templates/seed/wallets.yml.erb
  db/migrate/20180726110440_add_max_deposit_and_gateway_to_wallets.rb
  db/schema.rb
  lib/daemons/blockchain.rb
  spec/controllers/admin/wallets_controller_spec.rb
Labels: Feature: BlockchainService, PR: Review, v1.9

#1482 Improvements in Deposit coin address daemon
  app/models/blockchain.rb
  app/models/wallet.rb
  app/workers/worker/deposit_coin_address.rb
  config/templates/seed/wallets.yml.erb
  db/migrate/20180727054453_add_blockchain_key_to_wallet.rb
  db/schema.rb
Labels: Feature: BlockchainService, PR: Approved

#1402 Fix migration multiple_deposit_addresses
  db/migrate/20180613140856_multiple_deposit_addresses.rb
Labels: PR: Approved, v1.9

#1485 Withdraw Coin Daemon
  app/models/concerns/belongs_to_currency.rb
  app/models/deposit.rb
  app/services/wallet_service/bitcoind.rb
  app/services/wallet_service/geth.rb
  app/workers/worker/withdraw_coin.rb
  lib/wallet_client.rb
  lib/wallet_client/bitcoind.rb
  lib/wallet_client/geth.rb
Labels: Feature: BlockchainService, PR: Approved

#1479 WalletService module and WalletService::Base class
  app/models/blockchain.rb
  app/models/concerns/belongs_to_currency.rb
  app/models/deposit.rb
  app/models/wallet.rb
  app/services/blockchain_service/bitcoin.rb
  app/services/blockchain_service/ethereum.rb
  app/services/wallet_service.rb
  app/services/wallet_service/bitcoind.rb
  app/services/wallet_service/geth.rb
  app/workers/worker/deposit_coin_address.rb
  app/workers/worker/deposit_collection.rb
  app/workers/worker/withdraw_coin.rb
  config/amqp.yml
  config/templates/seed/wallets.yml.erb
  db/migrate/20180727054453_add_blockchain_key_to_wallet.rb
  db/schema.rb
  lib/coin_api.rb
  lib/wallet_client.rb
  lib/wallet_client/bitcoind.rb
  lib/wallet_client/geth.rb
Labels: Feature: BlockchainService, PR: Approved
