Repository openware/peatio, pull requests merged in 2018-12, with the labels that each got.

#1861 Return 200 on successful pusher auth
  app/api/api_v2/pusher.rb
  spec/api/api_v2/pusher_spec.rb
Labels: PR: Approved, v1.8

#1832 Massive gem updates
  Gemfile.lock
Labels: PR: Approved, v1.9

#1826 Fix global state updating for asks and bids
  app/workers/worker/slave_book.rb
  spec/models/worker/slave_book_spec.rb
Labels: PR: Approved, v1.8

#1901 Add missing method for geth wallet client
  lib/wallet_client/geth.rb
Labels: PR: Approved, v1.9

#1763 Add opportunity to define minimum amount for trade
  app/controllers/admin/markets_controller.rb
  app/models/market.rb
  app/models/order.rb
  app/models/order_ask.rb
  app/models/order_bid.rb
  app/views/admin/markets/index.html.erb
  app/views/admin/markets/show.html.erb
  config/templates/seed/markets.yml.erb
  db/migrate/20181213135712_add_min_amount_to_market.rb
  db/schema.rb
  spec/controllers/admin/markets_controller_spec.rb
  spec/factories/market.rb
  spec/models/order_ask_spec.rb
  spec/models/order_bid_spec.rb
Labels: PR: Approved, v1.9

#1762 Add opportunity to define minimum amount for trade
  app/controllers/admin/markets_controller.rb
  app/models/market.rb
  app/models/order.rb
  app/models/order_ask.rb
  app/models/order_bid.rb
  app/views/admin/markets/index.html.erb
  app/views/admin/markets/show.html.erb
  config/templates/seed/markets.yml.erb
  db/migrate/20181212150113_add_min_amount_to_market.rb
  db/schema.rb
  spec/controllers/admin/markets_controller_spec.rb
  spec/factories/market.rb
  spec/features/market_spec.rb
  spec/features/market_trade_history_spec.rb
  spec/models/order_ask_spec.rb
  spec/models/order_bid_spec.rb
Labels: PR: Approved, v1.8

#1911 Store Currency options as JSON and define accessors
  app/assets/javascripts/admin.js
  app/assets/stylesheets/admin.scss
  app/controllers/admin/currencies_controller.rb
  app/models/currency.rb
  app/views/admin/currencies/show.html.erb
  config/templates/seed/currencies.yml.erb
  spec/controllers/admin/currencies_controller_spec.rb
  spec/factories/currencies.rb
  vendor/assets/javascripts/jsoneditor.min.js
Labels: PR: Approved, v1.9

#1848 JSON Editor For Currency options
  app/assets/javascripts/admin.js
  app/assets/stylesheets/admin.scss
  app/controllers/admin/currencies_controller.rb
  app/models/currency.rb
  app/views/admin/currencies/show.html.erb
  config/templates/seed/currencies.yml.erb
  spec/controllers/admin/currencies_controller_spec.rb
  spec/factories/currencies.rb
  vendor/assets/javascripts/jsoneditor.min.js
Labels: PR: Approved, v2.0

#1880 Improve deposit collection daemon logs and add ability to reject fiat deposit from admin panel
  app/controllers/admin/deposits/coins_controller.rb
  app/controllers/admin/deposits/fiats_controller.rb
  app/models/deposit.rb
  app/services/blockchain_service.rb
  app/services/wallet_service.rb
  app/views/admin/deposits/coins/_table.html.erb
  app/views/admin/deposits/coins/index.html.erb
  app/views/admin/deposits/fiats/show.html.erb
  app/workers/worker/deposit_collection.rb
Labels: PR: Approved, v2.0

#1908 Improve deposit collection daemon and add ability to reject fiat deposit
  app/controllers/admin/deposits/coins_controller.rb
  app/controllers/admin/deposits/fiats_controller.rb
  app/models/deposit.rb
  app/services/blockchain_service.rb
  app/services/wallet_service.rb
  app/views/admin/deposits/coins/_table.html.erb
  app/views/admin/deposits/coins/index.html.erb
  app/views/admin/deposits/fiats/show.html.erb
  app/workers/worker/deposit_collection.rb
Labels: PR: Approved, v1.9

#1869 Ability to set custom gas_limit & gas_price per currency.
  app/models/currency.rb
  app/services/wallet_service/geth.rb
  config/templates/seed/currencies.yml.erb
  lib/wallet_client/geth.rb
  spec/factories/currencies.rb
  spec/services/wallet_service/geth_spec.rb
Labels: PR: Approved, v1.9

#1914 Add opportunity to define minimum amount for trade
  app/controllers/admin/markets_controller.rb
  app/models/market.rb
  app/models/order.rb
  app/models/order_ask.rb
  app/models/order_bid.rb
  app/views/admin/markets/index.html.erb
  app/views/admin/markets/show.html.erb
  db/migrate/20181219133822_add_min_amount_to_market.rb
  db/schema.rb
  spec/controllers/admin/markets_controller_spec.rb
  spec/factories/market.rb
  spec/models/order_ask_spec.rb
  spec/models/order_bid_spec.rb
Labels: PR: Approved, v2.0

#1887 Ability to set custom gas_limit & gas_price per currency.
  app/models/currency.rb
  app/services/wallet_service/geth.rb
  config/templates/seed/currencies.yml.erb
  db/schema.rb
  lib/wallet_client/geth.rb
  spec/factories/currencies.rb
  spec/services/wallet_service/geth_spec.rb
Labels: PR: Approved, v2.0

#1913 Fixed Market Type should not appear on Trading-ui
  app/models/order.rb
  app/trading/matching/executor.rb
Labels: PR: Changes needed, PR: WIP, v1.9

#1921 Don't trigger pusher events on market order update
  app/models/order.rb
  app/trading/matching/executor.rb
Labels: PR: Pre-approved, v1.9

#1924 Trigger limit order update events
  app/models/order.rb
  app/trading/matching/executor.rb
  spec/services/ordering_spec.rb
Labels: PR: Approved, v1.8
