Repository openware/peatio, pull requests merged in 2019-08, with the labels that each got.

#2287 Add rake task for load users and balances
  docs/tasks/import.md
  lib/tasks/import.rake
Labels: PR: Approved, v2.2

#2289 [ci skip] Finalize 2-2 release docs
  CHANGELOG.md
  Gemfile.plugin
  docs/coins/plugins.md
  docs/releases/2.2.0.md
Labels: PR: Approved, v2.2

#2283 Add RevShare model. Add state to Trade
  app/models/revenue_share.rb
  app/models/trade.rb
  app/trading/matching/executor.rb
  db/migrate/20190729124305_add_state_to_trade.rb
  db/migrate/20190730091236_create_revenue_shares.rb
  db/schema.rb
  spec/factories/revenue_share.rb
  spec/factories/trade.rb
  spec/models/revenue_share_spec.rb
  spec/support/rspec_matchers.rb
Labels: PR: Approved, v2.3

#2278 Market & Currency admin forms corrections & improvements
  app/controllers/admin/markets_controller.rb
  app/models/application_record.rb
  app/models/currency.rb
  app/models/market.rb
  app/views/admin/deposits/coins/_table.html.erb
  app/views/admin/deposits/fiats/_table.html.erb
  app/views/admin/markets/index.html.erb
  app/views/admin/markets/show.html.erb
  app/views/admin/withdraws/coins/_pending_table.html.erb
  app/views/admin/withdraws/coins/_table.html.erb
  app/views/admin/withdraws/coins/index.html.erb
  app/views/admin/withdraws/coins/show.html.erb
  app/views/admin/withdraws/fiats/_table.html.erb
  app/views/admin/withdraws/fiats/index.html.erb
  spec/controllers/admin/markets_controller_spec.rb
  spec/models/market_spec.rb
Labels: PR: Approved, v2.3

#2298 Update peatio-ripple gem version
  Gemfile.lock
  Gemfile.plugin
Labels: PR: Approved, v2.3

#2285 Add GET API for Operations and Members
  app/api/v2/admin/blockchain_params.rb
  app/api/v2/admin/blockchains.rb
  app/api/v2/admin/currencies.rb
  app/api/v2/admin/currency_params.rb
  app/api/v2/admin/deposit_params.rb
  app/api/v2/admin/deposits.rb
  app/api/v2/admin/entities/base.rb
  app/api/v2/admin/entities/blockchain.rb
  app/api/v2/admin/entities/currency.rb
  app/api/v2/admin/entities/deposit.rb
  app/api/v2/admin/entities/market.rb
  app/api/v2/admin/entities/member.rb
  app/api/v2/admin/entities/operation.rb
  app/api/v2/admin/entities/order.rb
  app/api/v2/admin/entities/trade.rb
  app/api/v2/admin/entities/wallet.rb
  app/api/v2/admin/entities/withdraw.rb
  app/api/v2/admin/helpers.rb
  app/api/v2/admin/market_params.rb
  app/api/v2/admin/markets.rb
  app/api/v2/admin/members.rb
  app/api/v2/admin/mount.rb
  app/api/v2/admin/operations.rb
  app/api/v2/admin/order_params.rb
  app/api/v2/admin/orders.rb
  app/api/v2/admin/params_helpers.rb
  app/api/v2/admin/trade_params.rb
  app/api/v2/admin/trades.rb
  app/api/v2/admin/wallet_params.rb
  app/api/v2/admin/wallets.rb
  app/api/v2/admin/withdraw_params.rb
  app/api/v2/admin/withdraws.rb
  app/api/v2/auth/middleware.rb
  app/api/v2/entities/order.rb
  app/api/v2/entities/order_book.rb
  app/api/v2/helpers.rb
  app/models/blockchain.rb
  docs/api/peatio_user_api_v2.md
  spec/api/v2/admin/blockchains_spec.rb
  spec/api/v2/admin/currencies_spec.rb
  spec/api/v2/admin/deposits_spec.rb
  spec/api/v2/admin/members_spec.rb
  spec/api/v2/admin/operations_spec.rb
  spec/api/v2/admin/orders_spec.rb
  spec/api/v2/admin/trades_spec.rb
  spec/api/v2/admin/wallets_spec.rb
  spec/api/v2/admin/withdraws_spec.rb
  spec/controllers/admin/blockchains_controller_spec.rb
  spec/factories/blockchains.rb
  spec/models/blockchain_spec.rb
Labels: Feature: Admin API, PR: Approved

#2303 Market & Currency admin forms corrections & improvements
  app/controllers/admin/markets_controller.rb
  app/models/application_record.rb
  app/models/currency.rb
  app/models/market.rb
  app/views/admin/deposits/coins/_table.html.erb
  app/views/admin/deposits/fiats/_table.html.erb
  app/views/admin/markets/index.html.erb
  app/views/admin/markets/show.html.erb
  app/views/admin/withdraws/coins/_pending_table.html.erb
  app/views/admin/withdraws/coins/_table.html.erb
  app/views/admin/withdraws/coins/index.html.erb
  app/views/admin/withdraws/coins/show.html.erb
  app/views/admin/withdraws/fiats/_table.html.erb
  app/views/admin/withdraws/fiats/index.html.erb
  spec/controllers/admin/markets_controller_spec.rb
  spec/models/market_spec.rb
Labels: PR: Approved, v2.2

#2300 Update gendocs script
  app/api/v2/admin/deposits.rb
  app/api/v2/admin/members.rb
  app/api/v2/admin/operations.rb
  app/api/v2/admin/orders.rb
  app/api/v2/admin/trades.rb
  app/api/v2/admin/withdraws.rb
  bin/gendocs
Labels: Feature: Admin API, PR: Approved

#2305 Update API doc files structure and naming
  app/api/v2/admin/mount.rb
  app/api/v2/management/mount.rb
  app/api/v2/mount.rb
  bin/gendocs
  docs/api/peatio_admin_api_v2.md
  docs/api/peatio_management_api_v2.md
  docs/api/peatio_user_api_v2.md
  docs/api/swagger/admin_api.json
  docs/api/swagger/management_api.json
  docs/api/swagger/user_api.json
Labels: Feature: Admin API, PR: Approved

#2306 Update peatio-ripple gem version
  Gemfile.lock
  Gemfile.plugin
Labels: PR: Approved, v2.2

#2295 Add parity wallet gataway and use it instead of peth. Deprecate peth
  config/initializers/wallet_api.rb
  spec/factories/wallet.rb
  spec/spec_helper.rb
Labels: PR: Approved, v2.3

#2307 Update management/transfers
  app/api/v2/management/helpers.rb
  app/api/v2/management/operations.rb
  app/api/v2/management/transfers.rb
  app/models/transfer.rb
  spec/api/v2/management/entities/transfer_spec.rb
  spec/api/v2/management/operations_spec.rb
  spec/api/v2/management/transfers_spec.rb
  spec/factories/operations.rb
  spec/factories/transfer.rb
  spec/models/transfer_spec.rb
Labels: Feature: Revenue Sharing, PR: Approved

#2282 Drop step from blockchain model
  app/controllers/admin/blockchains_controller.rb
  app/models/blockchain.rb
  app/services/blockchain_service.rb
  app/views/admin/blockchains/show.html.erb
  app/workers/daemons/blockchain.rb
  config/backend.yml
  db/migrate/20190726161540_drop_step_from_blockchain.rb
  db/schema.rb
  spec/controllers/admin/blockchains_controller_spec.rb
  spec/models/deposit_spec.rb
  spec/services/blockchain_service_spec.rb
Labels: PR: Approved, v2.2

#2310 Use Vault transit engine for storing Wallet & PaymentAddress sensitive data
  Gemfile
  Gemfile.lock
  app/models/payment_address.rb
  app/models/wallet.rb
  bin/init_vault
  config/initializers/vault.rb
  db/migrate/20190807092706_add_encrypted_secret_to_payment_address.rb
  db/schema.rb
  lib/peatio/vault/totp.rb
  spec/models/payment_address_spec.rb
  spec/models/wallet_spec.rb
Labels: PR: Approved, v2.3

#2301 Upgrade Transfer model. Add gross Revenue account
  app/api/v2/management/helpers.rb
  app/api/v2/management/operations.rb
  app/api/v2/management/transfers.rb
  app/models/operation.rb
  app/models/trade.rb
  app/models/transfer.rb
  config/templates/seed/accounts.yml.erb
  spec/api/v2/management/entities/transfer_spec.rb
  spec/api/v2/management/operations_spec.rb
  spec/api/v2/management/transfers_spec.rb
  spec/factories/operations.rb
  spec/factories/operations_account.rb
  spec/factories/transfer.rb
  spec/models/trade_spec.rb
  spec/models/transfer_spec.rb
  spec/spec_helper.rb
Labels: Feature: Revenue Sharing, PR: Approved

#2316 Change run Peatio::Application to Rails.application in config.ru
  config.ru
Labels: PR: Approved, v2.3

#2293 Prepare management API for Revenue Share
  app/api/v2/management/entities/revenue_share.rb
  app/api/v2/management/mount.rb
  app/api/v2/management/revenue_shares.rb
  app/models/revenue_share.rb
  config/templates/management_api_v1.yml.erb
  spec/api/v2/management/entities/revenue_share_spec.rb
  spec/api/v2/management/revenue_shares_spec.rb
Labels: PR: Approved, v2.3

#2292 Switch to maker-taker fee model. Major Trade model rework
  app/api/v2/entities/market.rb
  app/api/v2/entities/trade.rb
  app/api/v2/management/entities/trade.rb
  app/api/v2/management/trades.rb
  app/controllers/admin/markets_controller.rb
  app/models/market.rb
  app/models/member.rb
  app/models/order.rb
  app/models/order_ask.rb
  app/models/order_bid.rb
  app/models/trade.rb
  app/serializers/serializers/event_api/order_event.rb
  app/serializers/serializers/event_api/trade_completed.rb
  app/trading/global.rb
  app/trading/matching/constants.rb
  app/trading/matching/engine.rb
  app/trading/matching/executor.rb
  app/views/admin/markets/index.html.erb
  app/views/admin/markets/show.html.erb
  app/workers/amqp/matching.rb
  app/workers/amqp/pusher_market.rb
  app/workers/daemons/k.rb
  config/templates/seed/markets.yml.erb
  db/migrate/20190813121822_update_markets_ask_fee_bid_fee.rb
  db/schema.rb
  docs/api/websocket_api.md
  spec/api/v2/entities/order_spec.rb
  spec/api/v2/entities/trade_spec.rb
  spec/api/v2/management/entities/trade_spec.rb
  spec/api/v2/management/trades_spec.rb
  spec/api/v2/market/orders_spec.rb
  spec/api/v2/market/trades_spec.rb
  spec/api/v2/public/markets_spec.rb
  spec/controllers/admin/markets_controller_spec.rb
  spec/factories/market.rb
  spec/factories/trade.rb
  spec/models/global_spec.rb
  spec/models/market_spec.rb
  spec/models/member_spec.rb
  spec/models/trade_spec.rb
  spec/serializers/serializers/event_api/order_canceled_spec.rb
  spec/serializers/serializers/event_api/order_completed_spec.rb
  spec/serializers/serializers/event_api/order_created_spec.rb
  spec/serializers/serializers/event_api/order_updated_spec.rb
  spec/serializers/serializers/event_api/trade_completed_spec.rb
  spec/trading/accounting_spec.rb
  spec/trading/matching/engine_spec.rb
  spec/trading/matching/executor_spec.rb
  spec/workers/matching_spec.rb
Labels: PR: Approved, v2.3

#2175 Add specs for Operations::Account validations
  app/models/operations/account.rb
  spec/models/operations/account_spec.rb
Labels: PR: Approved, v2.2

#2189 Add attr_readonly to some Order attributes
  app/models/order.rb
  spec/models/order_spec.rb
  spec/workers/matching_spec.rb
Labels: PR: Approved, v2.2

#2198 Remove legacy withdraw factories
  spec/api/v2/account/balances_spec.rb
  spec/api/v2/account/withdraws_spec.rb
  spec/api/v2/management/entities/withdraw_spec.rb
  spec/api/v2/management/withdraws_spec.rb
  spec/factories/withdraw.rb
  spec/models/withdraw_spec.rb
  spec/trading/accounting_spec.rb
  spec/workers/withdraw_coin_spec.rb
Labels: PR: Approved, v2.2

#2302 Fail ethereum withdrawal in case of fail status in blockchain
  app/services/blockchain_service.rb
  lib/peatio/ethereum/blockchain.rb
  spec/lib/ethereum/blockchain_spec.rb
  spec/resources/ethereum-data/rinkeby/2621840-2621842.json
  spec/resources/ethereum-data/rinkeby/transaction-receipts/2621840-2621842.json
  spec/services/blockchain_service_spec.rb
Labels: PR: Approved, v2.3

#2324 Don't use validations for updating database in migrations
  db/migrate/20190711114027_update_markets_min_amount_and_price.rb
Labels: PR: Approved, v2.3

#2327 Fail ethereum withdrawal in case of fail status in blockchain
  app/services/blockchain_service.rb
  lib/peatio/ethereum/blockchain.rb
  spec/lib/ethereum/blockchain_spec.rb
  spec/resources/ethereum-data/rinkeby/2621840-2621842.json
  spec/resources/ethereum-data/rinkeby/transaction-receipts/2621840-2621842.json
  spec/services/blockchain_service_spec.rb
Labels: PR: Approved, v2.2

#2328 Add ability to bump & tag stable branches
  lib/tasks/release.rake
Labels: PR: Approved, v2.3

#2329 Add ability to bump & tag stable branches
  lib/tasks/release.rake
Labels: PR: Approved, v2.2

#2330 Add ability to bump & tag stable branches
  Gemfile.lock
  lib/tasks/release.rake
Labels: PR: Approved, v2.1

#2264 Admin API module for tower
  Gemfile
  Gemfile.lock
  app/api/v2/admin/blockchains.rb
  app/api/v2/admin/currencies.rb
  app/api/v2/admin/deposits.rb
  app/api/v2/admin/entities/blockchain.rb
  app/api/v2/admin/entities/currency.rb
  app/api/v2/admin/entities/deposit.rb
  app/api/v2/admin/entities/market.rb
  app/api/v2/admin/entities/member.rb
  app/api/v2/admin/entities/operation.rb
  app/api/v2/admin/entities/order.rb
  app/api/v2/admin/entities/trade.rb
  app/api/v2/admin/entities/wallet.rb
  app/api/v2/admin/entities/withdraw.rb
  app/api/v2/admin/helpers.rb
  app/api/v2/admin/markets.rb
  app/api/v2/admin/members.rb
  app/api/v2/admin/mount.rb
  app/api/v2/admin/operations.rb
  app/api/v2/admin/orders.rb
  app/api/v2/admin/trades.rb
  app/api/v2/admin/wallets.rb
  app/api/v2/admin/withdraws.rb
  app/api/v2/auth/middleware.rb
  app/api/v2/entities/order.rb
  app/api/v2/entities/order_book.rb
  app/api/v2/exception_handlers.rb
  app/api/v2/helpers.rb
  app/api/v2/management/mount.rb
  app/api/v2/market/orders.rb
  app/api/v2/mount.rb
  app/models/blockchain.rb
  app/models/currency.rb
  app/models/order.rb
  app/models/trade.rb
  bin/gendocs
  lib/peatio/csv_formatter.rb
  spec/api/v2/admin/blockchains_spec.rb
  spec/api/v2/admin/currencies_spec.rb
  spec/api/v2/admin/deposits_spec.rb
  spec/api/v2/admin/markets_spec.rb
  spec/api/v2/admin/members_spec.rb
  spec/api/v2/admin/operations_spec.rb
  spec/api/v2/admin/orders_spec.rb
  spec/api/v2/admin/trades_spec.rb
  spec/api/v2/admin/wallets_spec.rb
  spec/api/v2/admin/withdraws_spec.rb
  spec/controllers/admin/blockchains_controller_spec.rb
  spec/factories/blockchains.rb
  spec/factories/member.rb
  spec/models/blockchain_spec.rb
  spec/models/currency_spec.rb
  spec/models/member_spec.rb
  spec/models/order_ask_spec.rb
  spec/support/rspec_matchers.rb
Labels: Feature: Admin API, PR: Approved, v2.3

#2331 Use update_attribute in migrations for skipping validations
  db/migrate/20190624102330_rename_market_fields.rb
  db/migrate/20190711114027_update_markets_min_amount_and_price.rb
Labels: PR: Approved, v2.3

#2158 Add validation specs for blockchain_key in Currency
  app/models/currency.rb
  spec/models/currency_spec.rb
Labels: PR: WIP, v2.2

#2332 Add missing -y for jq install in bin/gendocs
  bin/gendocs
Labels: PR: Approved, v2.3

#2321 Trading Fee Schedule based on Member group
  app/api/v2/admin/markets.rb
  app/api/v2/entities/market.rb
  app/api/v2/management/entities/member.rb
  app/api/v2/management/members.rb
  app/api/v2/management/mount.rb
  app/controllers/admin/markets_controller.rb
  app/models/concerns/precision_validator.rb
  app/models/market.rb
  app/models/member.rb
  app/models/order.rb
  app/models/trading_fee.rb
  config/templates/management_api_v1.yml.erb
  config/templates/seed/markets.yml.erb
  config/templates/seed/trading_fees.yml.erb
  db/migrate/20190814102636_create_trading_fees.rb
  db/migrate/20190816125948_add_group_to_member_drop_fees_from_market.rb
  db/schema.rb
  db/seeds.rb
  lib/tasks/seed.rake
  spec/api/v2/admin/markets_spec.rb
  spec/api/v2/management/members_spec.rb
  spec/api/v2/public/markets_spec.rb
  spec/controllers/admin/markets_controller_spec.rb
  spec/factories/market.rb
  spec/factories/member.rb
  spec/factories/trading_fees.rb
  spec/models/concerns/precision_validator_spec.rb
  spec/models/market_spec.rb
  spec/models/order_spec.rb
  spec/models/trade_spec.rb
  spec/models/tradinng_fee_spec.rb
  spec/spec_helper.rb
  spec/trading/matching/executor_spec.rb
Labels: PR: Approved, v2.3

#2335 Rewrite validation for buy and sell order in trade_executor
  app/trading/matching/executor.rb
  spec/trading/matching/executor_spec.rb
Labels: PR: Approved, v2.3

#2333 Remove jq package from gendocs
  bin/gendocs
Labels: v2.3

#2344 Use Faker::Blockchain::Bitcoin instead of Faker::Bitcoin
  lib/peatio/bench/factories.rb
Labels: PR: Approved, v2.2

#2343 Use Faker::Blockchain::Bitcoin instead of Faker::Bitcoin
  lib/peatio/bench/factories.rb
Labels: PR: Approved, v2.3

#2340 Update specs for swagger
  app/api/v2/admin/deposits.rb
  app/api/v2/admin/wallets.rb
  spec/api/swagger_spec.rb
Labels: PR: Approved, v2.3

#2339 Add endpoint to list all blockchain clients & provide access to disabled markets in Admin API
  app/api/v2/admin/blockchains.rb
  app/api/v2/admin/orders.rb
  app/api/v2/admin/trades.rb
  spec/api/v2/admin/blockchains_spec.rb
Labels: PR: Approved, v2.3

#2346 Remove uid length limit in members table
  app/models/member.rb
  db/migrate/20190829035814_remove_uid_limit_for_member.rb
  db/schema.rb
Labels: PR: Approved, v2.3

#2334 Add Admin and Management API for TradingFees
  app/api/v2/admin/entities/trading_fee.rb
  app/api/v2/admin/mount.rb
  app/api/v2/admin/trading_fees.rb
  app/api/v2/management/mount.rb
  app/api/v2/management/trading_fees.rb
  app/models/abilities/admin.rb
  app/models/abilities/superadmin.rb
  app/models/abilities/technical.rb
  app/views/admin/markets/index.html.erb
  app/views/admin/markets/show.html.erb
  spec/api/v2/admin/trading_fees_spec.rb
  spec/api/v2/management/trading_fees_spec.rb
Labels: PR: Approved, v2.3
