Repository openware/peatio, pull requests merged in 2019-02, with the labels that each got.

#2035 Improve pagination for /markets /public APIs
  Gemfile
  Gemfile.lock
  app/api/v2/account/deposits.rb
  app/api/v2/account/withdraws.rb
  app/api/v2/entities/trade.rb
  app/api/v2/market/orders.rb
  app/api/v2/market/trades.rb
  app/api/v2/named_params.rb
  app/api/v2/public/markets.rb
  app/controllers/private/markets_controller.rb
  app/models/trade.rb
  app/views/private/markets/show.json.jbuilder
  app/workers/worker/pusher_market.rb
  config/initializers/api_pagination.rb
  config/initializers/kaminari_config.rb
  spec/api/v2/account/deposits_spec.rb
  spec/api/v2/account/withdraws_spec.rb
  spec/api/v2/market/orders_spec.rb
  spec/api/v2/market/trades_spec.rb
  spec/api/v2/public/markets_spec.rb
  spec/models/trade_spec.rb
Labels: PR: Approved, v2.0

#2048 Fix for_notify in pusher_market daemon
  app/workers/worker/pusher_market.rb
Labels: v2.0

#2036 Add Drone CI
  .dockerignore
  .drone.yml
  .travis.yml
  README.md
  docs/ops/ci.md
  lib/tasks/release.rake
Labels: PR: Approved, v2.0

#2044 Speed up RSpec test (closes #1932)
  spec/api/v2/public/markets_spec.rb
  spec/models/payment_address_spec.rb
  spec/serializers/serializers/event_api/order_canceled_spec.rb
  spec/serializers/serializers/event_api/order_completed_spec.rb
  spec/serializers/serializers/event_api/order_created_spec.rb
  spec/serializers/serializers/event_api/order_updated_spec.rb
  spec/serializers/serializers/event_api/trade_completed_spec.rb
  spec/services/ordering_spec.rb
  spec/spec_helper.rb
Labels: PR: Approved, v2.0

#2058 Unify API errors for api/v2/market/*
  app/api/v2/errors.rb
  app/api/v2/helpers.rb
  app/api/v2/market/mount.rb
  app/api/v2/market/orders.rb
  app/api/v2/market/trades.rb
  app/api/v2/named_params.rb
  app/api/v2/new_exceptions_handlers.rb
  app/models/order.rb
  app/models/order_ask.rb
  spec/api/v2/account/deposits_spec.rb
  spec/api/v2/account/withdraws_spec.rb
  spec/api/v2/market/orders_spec.rb
  spec/api/v2/market/trades_spec.rb
  spec/api/v2/public/markets_spec.rb
  spec/models/order_ask_spec.rb
  spec/models/order_bid_spec.rb
Labels: PR: Approved, v2.0

#2043 Update setup-ubuntu.md [1.9]
  docs/setup-ubuntu.md
Labels: PR: Approved, v1.9

#2062 Add PR trigger to Drone CI
  .drone.yml
Labels: PR: Approved, v2.0

#2071 Move health probes to Grape API v2 (closes #2066)
  app/api/v2/public/tools.rb
  app/controllers/public/health_controller.rb
  config/routes.rb
  spec/api/v2/public/tools_spec.rb
Labels: PR: Approved, v2.0

#2061 Sort orders by updated_at column
  app/api/v2/entities/order.rb
  app/api/v2/market/orders.rb
  app/models/order.rb
  app/models/order_ask.rb
  app/models/order_bid.rb
  app/models/trade.rb
  db/migrate/20190213104708_add_missing_indexes_to_order_and_trade.rb
  db/schema.rb
  spec/api/v2/market/orders_spec.rb
Labels: PR: Approved, v2.0

#2063 Unify API errors for api/v2/account/* and api/v2/public/*
  app/api/v2/account/balances.rb
  app/api/v2/account/deposits.rb
  app/api/v2/account/mount.rb
  app/api/v2/account/withdraws.rb
  app/api/v2/management/withdraws.rb
  app/api/v2/named_params.rb
  app/api/v2/public/currencies.rb
  app/api/v2/public/markets.rb
  app/api/v2/public/mount.rb
  app/api/v2/validations.rb
  app/models/concerns/fee_chargeable.rb
  spec/api/v2/account/balances_spec.rb
  spec/api/v2/account/deposits_spec.rb
  spec/api/v2/account/withdraws_spec.rb
  spec/api/v2/management/withdraws_spec.rb
  spec/api/v2/public/currencies_spec.rb
  spec/api/v2/public/markets_spec.rb
  spec/models/withdraw_spec.rb
Labels: PR: WIP, v2.0

#2070 Rename entities fields for order and expose taker_type instead of maker_type
  app/api/v2/entities/order.rb
  app/api/v2/entities/trade.rb
  app/models/order.rb
  docs/api/websocket_api.md
  spec/api/v2/entities/order_spec.rb
  spec/api/v2/entities/trade_spec.rb
Labels: PR: Approved, v2.0

#2039 Prevent admin to create mirror market pairs. Update seeds
  app/models/market.rb
  config/templates/seed/markets.yml.erb
  spec/controllers/admin/markets_controller_spec.rb
  spec/models/market_spec.rb
Labels: PR: Approved, v2.0

#2079 Rewrite TODOs. Remove price difference check in Order
  app/api/v2/helpers.rb
  app/api/v2/mount.rb
  app/models/order.rb
  spec/models/order_ask_spec.rb
  spec/models/order_bid_spec.rb
Labels: PR: Approved, v2.0

#2080 Add errors.md
  app/api/v2/account/withdraws.rb
  app/api/v2/helpers.rb
  app/api/v2/market/named_params.rb
  docs/api/errors.md
  spec/api/v2/account/withdraws_spec.rb
Labels: PR: Review, v2.0

#2078 Update updated_at on trade executor (closes #2069)
  app/models/order.rb
  app/trading/matching/executor.rb
Labels: PR: Approved, v2.0

#2081 Revert Travis CI & Drop Drone CI
  .dockerignore
  .drone.yml
  .travis.yml
  README.md
  lib/tasks/release.rake
Labels: PR: Approved, v2.0

#2053 Unify API errors structure and messages
  app/api/v2/account/balances.rb
  app/api/v2/account/deposits.rb
  app/api/v2/account/withdraws.rb
  app/api/v2/errors.rb
  app/api/v2/exception_handlers.rb
  app/api/v2/helpers.rb
  app/api/v2/management/withdraws.rb
  app/api/v2/market/named_params.rb
  app/api/v2/market/orders.rb
  app/api/v2/market/trades.rb
  app/api/v2/mount.rb
  app/api/v2/named_params.rb
  app/api/v2/public/currencies.rb
  app/api/v2/public/markets.rb
  app/api/v2/validations.rb
  app/models/concerns/fee_chargeable.rb
  app/models/order.rb
  app/models/order_ask.rb
  docs/api/errors.md
  spec/api/v2/account/balances_spec.rb
  spec/api/v2/account/deposits_spec.rb
  spec/api/v2/account/withdraws_spec.rb
  spec/api/v2/auth/middleware_spec.rb
  spec/api/v2/helpers_spec.rb
  spec/api/v2/management/withdraws_spec.rb
  spec/api/v2/market/orders_spec.rb
  spec/api/v2/market/trades_spec.rb
  spec/api/v2/mount_spec.rb
  spec/api/v2/public/currencies_spec.rb
  spec/api/v2/public/markets_spec.rb
  spec/models/order_ask_spec.rb
  spec/models/order_bid_spec.rb
  spec/models/withdraw_spec.rb
  spec/support/rspec_matchers.rb
Labels: PR: Approved, v2.0

#2087 Change health checks request types for k8s
  app/api/v2/public/tools.rb
  spec/api/v2/public/tools_spec.rb
Labels: PR: Approved, v2.0

#2086 Ability to change VAULT_TOKEN
  bin/init_vault
  bin/setup
  config/backend.yml
Labels: PR: Approved, v2.0

#2088 Use strict variant of save in Member#from_payload
  app/api/v2/auth/jwt_authenticator.rb
  app/api/v2/auth/middleware.rb
  app/api/v2/helpers.rb
  app/models/member.rb
  spec/api/v2/auth/middleware_spec.rb
Labels: PR: Approved, v2.0

#2092 Modified command to start rails server on macOS
  README.md
Labels: PR: Approved, v2.1

#2091 Remove deprecated fees API (closes #2077)
  app/api/v2/public/fees.rb
  app/api/v2/public/mount.rb
  spec/api/v2/public/fees_spec.rb
Labels: PR: Approved, v2.1

#2090 Remove plugin API v1 (closes #2076)
  .gitignore
  .travis.yml
  bin/gendocs
  bin/install_plugins
  bin/uninstall_plugins
  config/application.rb
  config/plugins.rb
  config/templates/plugins.yml.erb
  vendor/plugins/.gitkeep
Labels: PR: Approved, v2.1
