Repository openware/peatio, pull requests merged in 2019-11, with the labels that each got.

#2402 Fix: move travis to openware repo
  lib/tasks/release.rake
Labels: v2.3

#2405 Feature: Update the CI to use SDK for version bumps
  .drone.yml
  .travis.yml
Labels: Category: CI, PR: WIP

#2207 Add deposits and withdraws history to one API endpoint
  app/api/v2/account/mount.rb
  app/api/v2/account/transactions.rb
  app/api/v2/entities/transactions.rb
  app/api/v2/mount.rb
  spec/api/v2/account/transactions_spec.rb
Labels: PR: Approved, v2.2

#2392 Add deposits and withdraws history to one API endpoint
  app/api/v2/account/mount.rb
  app/api/v2/account/transactions.rb
  app/api/v2/entities/transactions.rb
  app/api/v2/mount.rb
  spec/api/v2/account/transactions_spec.rb
Labels: PR: Approved, v2.3

#2393 Feature: Add tid to /account deposits endpoints
  app/api/v2/entities/deposit.rb
Labels: PR: Approved, v2.3

#2394 Add pagination to currencies markets & balances. Expose currency position
  app/api/v2/account/balances.rb
  app/api/v2/entities/currency.rb
  app/api/v2/param_helpers.rb
  app/api/v2/public/currencies.rb
  app/api/v2/public/markets.rb
  app/models/account.rb
  spec/api/v2/account/balances_spec.rb
  spec/api/v2/public/currencies_spec.rb
  spec/api/v2/public/markets_spec.rb
Labels: PR: Approved, v2.3

#2397 Allow filtering by multiple states in admin/withdraws
  app/api/v2/admin/withdraws.rb
  spec/api/v2/admin/withdraws_spec.rb
Labels: PR: Approved, v2.3

#2406 Fix of asks data
  app/api/v2/public/markets.rb
  spec/api/v2/public/markets_spec.rb
Labels: PR: Approved, v2.3

#2412 Feature: add ability to add note to withdraw by management api
  app/api/v2/management/entities/withdraw.rb
  app/api/v2/management/withdraws.rb
  spec/api/v2/management/entities/withdraw_spec.rb
  spec/api/v2/management/withdraws_spec.rb
Labels: PR: Approved, v2.3

#2413 Feature: add confirmations field to transactions API
  .drone.yml
  app/api/v2/account/transactions.rb
  app/api/v2/entities/transactions.rb
  spec/api/v2/account/transactions_spec.rb
  spec/factories/deposits.rb
Labels: PR: Approved, v2.3

#2416 Feature: update version of plugins
  Gemfile
  Gemfile.lock
  Gemfile.plugin
Labels: PR: Approved, v2.3

#2403 Do not expose wallet sensitive settings data on admin api
  app/api/v2/admin/entities/wallet.rb
  app/controllers/admin/wallets_controller.rb
  app/models/wallet.rb
  app/views/admin/wallets/_bitgo_form.html.erb
  app/views/admin/wallets/show.html.erb
  app/views/admin/wallets/show_client_info.js.erb
  spec/api/v2/admin/wallets_spec.rb
Labels: PR: Approved, v2.3

#2401 Add ability to set member group, select member by uid and get all exi…
  app/api/v2/admin/entities/member.rb
  app/api/v2/admin/members.rb
  app/models/abilities/admin.rb
  app/models/member.rb
  spec/api/v2/admin/members_spec.rb
  spec/models/abilities_spec.rb
  spec/support/api_helper.rb
Labels: PR: Approved, v2.3

#2417 Feature: update version of plugins
  Gemfile
  Gemfile.lock
  Gemfile.plugin
Labels: PR: Review

#2400 Feature: incremental order-book
  .drone.yml
  Gemfile
  Gemfile.lock
  Gemfile.plugin
  app/assets/config/manifest.js
  app/trading/matching/engine.rb
  app/trading/matching/order_book.rb
  app/trading/matching/price_level.rb
  app/workers/amqp/matching.rb
  app/workers/amqp/pusher_market.rb
  app/workers/amqp/pusher_member.rb
  app/workers/daemons/global_state.rb
  app/workers/daemons/k.rb
  docs/api/images/peatio/scheme_ranger_private_channels.png
  docs/api/images/peatio/scheme_ranger_public_channels.png
  docs/api/websocket_api.md
  spec/trading/matching/engine_spec.rb
  spec/trading/matching/order_book_spec.rb
Labels: 2.4, PR: Review

#2420 Don't use Vault in transit mode for encrypting and decrypting data in…
  config/initializers/vault.rb
Labels: v2.3
