Repository openware/peatio, pull requests merged in 2019-05, with the labels that each got.

#2192 Update Bitcoin::WalletClient with subtract fees
  app/services/wallet_service2.rb
  lib/peatio/bitcoin/wallet.rb
  lib/peatio/ethereum1/wallet.rb
  spec/lib/bitcoin/wallet_spec.rb
  spec/lib/ethereum/wallet_spec.rb
  spec/services/wallet_service2_spec.rb
Labels: PR: Changes needed

#2193 Update blockchain daemon with BlockchainService v2
  app/services/blockchain_service2.rb
  lib/daemons/blockchain.rb
  lib/peatio/ethereum1/blockchain.rb
Labels: PR: Approved

#2190 Make daemons compatible with WalletService v2
  app/models/deposit.rb
  app/models/deposits/coin.rb
  app/models/deposits/fiat.rb
  app/models/withdraws/coin.rb
  app/services/wallet_service2.rb
  app/workers/worker/deposit_coin_address.rb
  app/workers/worker/deposit_collection.rb
  app/workers/worker/deposit_collection_fees.rb
  app/workers/worker/withdraw_coin.rb
  config/initializers/wallet_api.rb
  db/migrate/20190426145506_add_spread_to_deposit.rb
  db/schema.rb
  spec/models/deposit_spec.rb
  spec/models/withdraw_spec.rb
  spec/workers/deposit_coin_address_spec.rb
  spec/workers/deposit_collection_fees_spec.rb
  spec/workers/deposit_collection_spec.rb
  spec/workers/withdraw_coin_spec.rb
Labels: PR: Approved

#2195 Local daemons bugfixing and improvements
  app/services/wallet_service2.rb
  app/workers/worker/deposit_coin_address.rb
  app/workers/worker/deposit_collection.rb
  app/workers/worker/deposit_collection_fees.rb
  app/workers/worker/withdraw_coin.rb
  lib/peatio/bitcoin/wallet.rb
  lib/peatio/ethereum1/wallet.rb
  lib/peatio/peatio/blockchain/error.rb
  lib/peatio/peatio/wallet/abstract.rb
  lib/peatio/peatio/wallet/error.rb
  spec/lib/bitcoin/wallet_spec.rb
  spec/lib/ethereum/wallet_spec.rb
  spec/workers/deposit_coin_address_spec.rb
  spec/workers/withdraw_coin_spec.rb
Labels: PR: Approved

#2201 Move core code to peatio gem
  Gemfile
  Gemfile.lock
  app/models/wallet.rb
  app/services/blockchain_service2.rb
  app/services/wallet_service2.rb
  config/initializers/blockchain_api.rb
  config/initializers/wallet_api.rb
  lib/peatio/peatio/block.rb
  lib/peatio/peatio/blockchain/abstract.rb
  lib/peatio/peatio/blockchain/error.rb
  lib/peatio/peatio/blockchain_api.rb
  lib/peatio/peatio/transaction.rb
  lib/peatio/peatio/wallet/abstract.rb
  lib/peatio/peatio/wallet/error.rb
  lib/peatio/peatio/wallet_api.rb
  spec/services/blockchain_service2_spec.rb
  spec/services/wallet_service2_spec.rb
  spec/workers/withdraw_coin_spec.rb
Labels: PR: Approved

#2194 Add :step column to blockchain model, update Blockchain daemon
  app/controllers/admin/blockchains_controller.rb
  app/models/blockchain.rb
  app/views/admin/blockchains/show.html.erb
  db/migrate/20190502103256_add_speed_to_blockchains.rb
  db/schema.rb
  lib/daemons/blockchain.rb
  spec/controllers/admin/blockchains_controller_spec.rb
Labels: PR: WIP

#2203 Blockchain & Wallet final refactoring
  .gitignore
  Gemfile.lock
  app/models/blockchain.rb
  app/models/currency.rb
  app/models/deposit.rb
  app/models/wallet.rb
  app/services/blockchain_service.rb
  app/services/wallet_service.rb
  app/workers/worker/deposit_coin_address.rb
  app/workers/worker/deposit_collection.rb
  app/workers/worker/deposit_collection_fees.rb
  app/workers/worker/withdraw_coin.rb
  config/initializers/blockchain_api.rb
  config/initializers/wallet_api.rb
  lib/daemons/blockchain.rb
  lib/peatio/ethereum/blockchain.rb
  lib/peatio/ethereum/client.rb
  lib/peatio/ethereum/wallet.rb
  spec/lib/ethereum/blockchain_spec.rb
  spec/lib/ethereum/wallet_spec.rb
  spec/models/deposit_spec.rb
  spec/services/blockchain_service_spec.rb
  spec/services/wallet_service_spec.rb
  spec/workers/deposit_coin_address_spec.rb
  spec/workers/deposit_collection_fees_spec.rb
  spec/workers/deposit_collection_spec.rb
  spec/workers/withdraw_coin_spec.rb
Labels: PR: Approved

#2206 Fix Bitgo WalletService & WalletClient build_raw_transaction
  app/services/wallet_service/bitgo.rb
  lib/peatio/wallet_client/bitgo.rb
  spec/services/wallet_service/bitgo_spec.rb
Labels: PR: Approved, v2.1

#2191 Update ruby version to 2.6.2
  README.md
Labels: PR: Approved, v2.2

#2205 Change order 'state' to int for order_processor
  app/api/v2/order_helpers.rb
Labels: PR: Approved, v2.2

#2182 Add management API endpoint for listing trades
  app/api/v2/management/entities/trade.rb
  app/api/v2/management/mount.rb
  app/api/v2/management/trades.rb
  spec/api/v2/management/entities/trade_spec.rb
  spec/api/v2/management/trades_spec.rb
Labels: PR: Approved, v2.2

#2210 Peatio-litecoin gem integration with minor updates. Coin plugin development doc
  Dockerfile
  Gemfile
  Gemfile.lock
  Gemfile.plugin
  README.md
  config/initializers/faraday.rb
  docs/coins/bitcoin/bitcoin.md
  docs/coins/development.md
  docs/coins/erc20/erc20.md
  docs/coins/ethereum/ethereum.md
  docs/coins/plugins.md
  docs/peatio/currency.md
  docs/peatio/erc20.md
  docs/peatio/ripple.md
  docs/peatio/testnet/ripple.md
Labels: PR: WIP

#2215 AMQP messages for third party trading engine integration
  app/api/v2/order_helpers.rb
  app/models/operations/liability.rb
  app/models/order.rb
  config/amqp.yml
  spec/api/v2/market/orders_spec.rb
  spec/models/operations/liability_spec.rb
  spec/services/blockchain_service_spec.rb
Labels: PR: QA, v2.2

#2220 Fix operations spec by saving timestamps in variables
  spec/api/v2/management/operations_spec.rb
Labels: PR: Approved, v2.2
