Repository openware/peatio, pull requests merged in 2019-01, with the labels that each got.

#1955 Freeze bundler version in 1.16.6
  .travis.yml
Labels: PR: Approved, v1.8

#1954 Freeze bundler version in 1.17.1
  .travis.yml
Labels: PR: Approved, v1.9

#1916 Add min withdraw amount for currencies
  app/api/api_v2/entities/currency.rb
  app/controllers/admin/currencies_controller.rb
  app/models/currency.rb
  app/models/withdraw.rb
  app/views/admin/currencies/show.html.erb
  db/migrate/20181226164014_add_min_withdraw_sum_to_currencies.rb
  db/schema.rb
  spec/models/withdraw_spec.rb
Labels: PR: Approved, v1.8

#1938 Remove ActionDispatch Session. Disable CSRF
  .travis.yml
  Gemfile
  Gemfile.lock
  app/assets/javascripts/funds/config/http.js.coffee
  app/assets/javascripts/funds/funds.js.coffee
  app/controllers/application_controller.rb
  app/controllers/private/markets_controller.rb
  app/views/layouts/admin.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/funds.html.erb
  app/views/layouts/landing.html.erb
  config/application.rb
  config/environments/test.rb
  config/initializers/cookies_serializer.rb
Labels: PR: Approved, v2.0

#1978 ￼Public version API endpoint
  app/api/v2/entities/version.rb
  app/api/v2/public/tools.rb
  bin/gendocs
  config/initializers/versioning.rb
Labels: PR: Approved, v2.0

#1973 Return Forbidden in case of unpermitted actions
  app/api/v2/helpers.rb
  spec/api/v2/account/deposits_spec.rb
  spec/api/v2/account/withdraws_spec.rb
  spec/api/v2/market/orders_spec.rb
  spec/api/v2/market/trades_spec.rb
Labels: PR: Approved, v2.0

#1981 Add CONTRIBUTING guide [skip ci]
  CONTRIBUTING.md
  README.md
Labels: PR: Approved, v2.0

#1968 Event API serializers imporvements
  app/models/account.rb
  app/serializers/serializers/event_api/order_event.rb
  app/serializers/serializers/event_api/trade_completed.rb
  docs/api/event_api.md
  spec/serializers/serializers/event_api/order_canceled_spec.rb
  spec/serializers/serializers/event_api/order_completed_spec.rb
  spec/serializers/serializers/event_api/order_created_spec.rb
  spec/serializers/serializers/event_api/order_updated_spec.rb
  spec/serializers/serializers/event_api/trade_completed_spec.rb
Labels: PR: Approved, v1.9

#1967 Event API serializers imporvements
  app/models/account.rb
  app/serializers/serializers/event_api/order_event.rb
  app/serializers/serializers/event_api/trade_completed.rb
  docs/api/event_api.md
  spec/serializers/serializers/event_api/order_canceled_spec.rb
  spec/serializers/serializers/event_api/order_completed_spec.rb
  spec/serializers/serializers/event_api/order_created_spec.rb
  spec/serializers/serializers/event_api/order_updated_spec.rb
  spec/serializers/serializers/event_api/trade_completed_spec.rb
Labels: PR: Approved, v2.0

#1966 Add an ability to specify CORS headers
  Gemfile
  Gemfile.lock
  config.ru
  config/templates/application.yml.erb
  lib/cors/validations.rb
  spec/api/v2/cors/cors_spec.rb
  spec/api/v2/cors/validations_spec.rb
Labels: PR: Approved, v2.0

#1958 Rewrite api entities for docs and code polishing
  Gemfile
  Gemfile.lock
  app/api/v2/account/deposits.rb
  app/api/v2/account/withdraws.rb
  app/api/v2/entities/account.rb
  app/api/v2/entities/deposit.rb
  app/api/v2/entities/market.rb
  app/api/v2/entities/member.rb
  app/api/v2/entities/order.rb
  app/api/v2/entities/order_book.rb
  app/api/v2/entities/trade.rb
  app/api/v2/entities/withdraw.rb
  app/api/v2/management/mount.rb
  app/api/v2/market/orders.rb
  app/api/v2/market/trades.rb
  app/api/v2/mount.rb
  app/api/v2/public/currencies.rb
  app/api/v2/public/markets.rb
  bin/gendocs
  docs/api/management_api_v1.md
  docs/api/member_api_v2.md
  docs/api/peatio_api_v2.md
Labels: PR: Approved, v2.0

#1984 Add swagger.json in pretty-json format
  bin/gendocs
Labels: PR: Approved, v2.0

#1930 Expose Trade market maker and don't expose null side
  app/api/api_v2/entities/trade.rb
  spec/api/api_v2/entities/trade_spec.rb
Labels: PR: Approved, v1.8

#1985 Expose Trade market maker and don't expose null side
  app/api/v2/entities/trade.rb
  spec/api/v2/entities/trade_spec.rb
Labels: PR: Approved, v2.0

#1986 Expose Trade market maker and don't expose null side
  app/api/api_v2/entities/trade.rb
  spec/api/api_v2/entities/trade_spec.rb
Labels: PR: Approved, v1.9

#1994 Add Peatio UI removal alert
  app/views/layouts/funds.html.erb
Labels: PR: Approved, v2.0

#1996 Publish WS event on k-line updates. Improve k-daemon performance
  app/services/k_line_service.rb
  docs/api/websocket_api.md
  lib/daemons/k.rb
  spec/api/v2/public/markets_spec.rb
Labels: PR: Approved, v2.0

#1997 Publish WS event on k-line updates. Improve k-daemon performance
  app/services/k_line_service.rb
  docs/api/websocket_api.md
  lib/daemons/k.rb
  spec/api/api_v2/k_spec.rb
Labels: PR: Approved, v1.9

#2002 Add close, avg_price & price_change_percent to WS & REST API
  app/api/api_v2/helpers.rb
  app/trading/global.rb
  docs/api/websocket_api.md
  spec/api/api_v2/tickers_spec.rb
Labels: PR: Approved, v1.9

#1959 Withdraw API With OTP
  .travis.yml
  Gemfile
  Gemfile.lock
  app/api/v2/account/withdraws.rb
  app/api/v2/helpers.rb
  bin/init_vault
  bin/setup
  config.ru
  config/backend.yml
  config/initializers/vault.rb
  config/templates/application.yml.erb
  lib/vault/totp.rb
  spec/api/v2/account/withdraws_spec.rb
  spec/api/v2/cors/cors_spec.rb
  spec/lib/vault_totp_spec.rb
Labels: PR: Approved, v2.0

#1989 Improve markets and currencies API
  app/api/v2/entities/market.rb
  app/api/v2/public/currencies.rb
  app/api/v2/public/fees.rb
  app/controllers/admin/currencies_controller.rb
  app/controllers/admin/markets_controller.rb
  app/controllers/private/funds_controller.rb
  app/models/currency.rb
  app/models/market.rb
  app/models/order.rb
  app/models/order_ask.rb
  app/models/order_bid.rb
  app/views/admin/currencies/show.html.erb
  app/views/admin/markets/show.html.erb
  config/templates/seed/currencies.yml.erb
  config/templates/seed/markets.yml.erb
  db/migrate/20190116140939_add_position_to_currencies_and_rename_min_ask_min_bid_to_markets.rb
  db/schema.rb
  spec/api/v2/cors/validations_spec.rb
  spec/api/v2/public/currencies_spec.rb
  spec/api/v2/public/markets_spec.rb
  spec/controllers/admin/currencies_controller_spec.rb
  spec/factories/currencies.rb
  spec/factories/market.rb
  spec/models/order_ask_spec.rb
  spec/models/order_bid_spec.rb
Labels: PR: Approved, v2.0

#1894 Fix global state updating for asks and bids
  app/workers/worker/slave_book.rb
  spec/workers/slave_book_spec.rb
Labels: PR: Approved, v2.0

#1925 Improve deposit collection fees daemon
  app/controllers/admin/deposits/coins_controller.rb
  app/models/deposit.rb
  app/views/admin/deposits/coins/_table.html.erb
  app/workers/worker/deposit_collection_fees.rb
Labels: PR: Approved, v2.0

#2000 Add close, avg_price & price_change_percent to WS & REST API
  app/api/v2/helpers.rb
  app/api/v2/public/markets.rb
  app/models/market.rb
  app/trading/global.rb
  docs/api/websocket_api.md
  spec/api/v2/public/markets_spec.rb
Labels: PR: Approved, v2.0

#2007 Fix private order update event
  app/models/order.rb
  app/trading/matching/executor.rb
  spec/services/ordering_spec.rb
Labels: PR: Approved, v2.0

#2011 Documentation clean up [skip ci]
  CONTRIBUTING.md
  README.md
  config/application.rb
  docs/architecture.md
  docs/setup-osx.md
  docs/setup-ubuntu.md
Labels: PR: Approved, v2.0

#2013 Fix migration for currency position and market entity
  app/api/v2/entities/market.rb
  app/models/currency.rb
  db/migrate/20190116140939_add_position_to_currencies_and_rename_min_ask_min_bid_to_markets.rb
  db/schema.rb
Labels: PR: Approved, v2.0

#2016 Migrate to Ambassador 0.50.0 & peatio 0.4.5. Update Ranger WS API
  Gemfile
  Gemfile.lock
  config/backend.yml
  config/gateway/ambassador.yaml
  config/gateway/auth.yaml
  config/gateway/mapping-peatio.yaml
  docs/api/websocket_api.md
Labels: PR: Approved, v2.0

#2019 Average 24h price using VWAP ratio. Minor Global & Market refactor
  app/models/market.rb
  app/models/trade.rb
  app/trading/global.rb
  spec/api/v2/public/markets_spec.rb
  spec/models/global_spec.rb
  spec/models/market_spec.rb
  spec/models/trade_spec.rb
  spec/support/redis_helper.rb
Labels: PR: Approved, v2.0

#2023 Experimental Transfer table and Management API
  app/api/v2/management/entities/operation.rb
  app/api/v2/management/entities/transfer.rb
  app/api/v2/management/helpers.rb
  app/api/v2/management/mount.rb
  app/api/v2/management/operations.rb
  app/api/v2/management/transfers.rb
  app/models/deposit.rb
  app/models/member.rb
  app/models/operation.rb
  app/models/operations/account.rb
  app/models/operations/asset.rb
  app/models/operations/chart.rb
  app/models/operations/expense.rb
  app/models/operations/liability.rb
  app/models/operations/revenue.rb
  app/models/order.rb
  app/models/trade.rb
  app/models/transfer.rb
  app/models/withdraw.rb
  app/views/admin/operations/shared/_table.html.erb
  config/templates/management_api_v1.yml.erb
  config/templates/seed/accounts.yml.erb
  db/migrate/20181226170925_create_transfers.rb
  db/migrate/20190110164859_drop_liabilities_not_null_add_revenues_member_id.rb
  db/migrate/20190115165813_create_operations_accounts.rb
  db/schema.rb
  db/seeds.rb
  lib/tasks/seed.rake
  spec/api/v2/management/entities/operation_spec.rb
  spec/api/v2/management/entities/transfer_spec.rb
  spec/api/v2/management/operations_spec.rb
  spec/api/v2/management/transfers_spec.rb
  spec/factories/operations.rb
  spec/factories/operations_account.rb
  spec/factories/transfer.rb
  spec/models/deposit_spec.rb
  spec/models/trade_spec.rb
  spec/models/withdraw_spec.rb
  spec/spec_helper.rb
  spec/trading/accounting_spec.rb
Labels: PR: Review, v2.0

#2026 Fix specs for model Global
  spec/models/global_spec.rb
Labels: PR: Review, v2.0

#2021 Update api 1-9 docs
  app/api/api_v2/deposits.rb
  app/api/api_v2/entities/deposit.rb
  app/api/api_v2/entities/market.rb
  app/api/api_v2/entities/order.rb
  app/api/api_v2/markets.rb
  app/api/api_v2/members.rb
  app/api/api_v2/order_books.rb
  app/api/api_v2/orders.rb
  app/api/api_v2/trades.rb
  app/api/api_v2/withdraws.rb
Labels: PR: Approved, v1.9
