Repository openware/peatio, pull requests merged in 2019-03, with the labels that each got.

#2098 Update application.yml.erb
  config/templates/application.yml.erb
Labels: PR: Approved, v2.1

#2108 Implement Bitfinex order injector based on file with Order history
  config/bench/bitfinex.yml
  config/bench/neo-usd-data.csv
  lib/bench/injectors.rb
  lib/bench/injectors/bitfinex.rb
  lib/bench/injectors/dummy.rb
  lib/bench/matching.rb
  lib/tasks/bench.rake
Labels: PR: Changes needed, v1.8

#2114 [WIP] Add save_reports function
  config/bench/matching.yml
  lib/bench/matching.rb
  reports/.gitkeep
Labels: PR: WIP, v1.8

#2116 Get rid off grape_strip gem
  Gemfile
  Gemfile.lock
  spec/api/v2/market/orders_spec.rb
Labels: v2.0

#2127 Replace rabbitmq_http_api_client with Faraday. Revert Faraday 0.14
  Gemfile
  Gemfile.lock
  config/initializers/inflections.rb
  lib/bench/matching.rb
  lib/rabbit_mq_http.rb
Labels: PR: QA, v1.8

#2121 Unify trade `taker_type` with Ranger and REST API
  app/models/trade.rb
Labels: PR: Approved, v2.1

#2072 Remove Peatio.tech brand from admin panel
  app/assets/images/logo-icon-white.svg
  app/assets/images/logo-white.png
  app/views/layouts/_admin_sidebar.html.erb
Labels: PR: Approved, v2.1

#2094 Avoid "message" in API controllers by overriding Grape::AllowBlankValidator
  app/api/v2/account/deposits.rb
  app/api/v2/account/withdraws.rb
  app/api/v2/market/named_params.rb
  app/api/v2/market/orders.rb
  app/api/v2/public/markets.rb
  app/api/v2/validations.rb
Labels: PR: Approved, v2.1

#2125 Add ability to cancel all orders for specific market
  app/api/v2/market/orders.rb
  spec/api/v2/market/orders_spec.rb
Labels: PR: Approved, v2.1

#2145 Fix release:travis rake task
  lib/tasks/release.rake
Labels: PR: Approved, v2.1

#2138 Direct benchmarks for matching, trade_executor and order_processing
  lib/bench/helpers.rb
  lib/bench/injectors/dummy.rb
  lib/bench/matching.rb
  lib/bench/matching/amqp.rb
  lib/bench/matching/direct.rb
  lib/bench/order_processing.rb
  lib/bench/order_processing/amqp.rb
  lib/bench/order_processing/direct.rb
  lib/bench/trade_execution.rb
  lib/bench/trade_execution/amqp.rb
  lib/bench/trade_execution/direct.rb
  lib/tasks/bench.rake
Labels: PR: WIP, v2.1
