Repository openware/peatio, pull requests merged in 2019-07, with the labels that each got.

#2245 Replace Passgen gem with new password generator
  Gemfile
  Gemfile.lock
  lib/peatio/ethereum/wallet.rb
  lib/peatio/password_generator.rb
  spec/lib/ethereum/wallet_spec.rb
  spec/workers/deposit_coin_address_spec.rb
Labels: PR: Approved, v2.2

#2242 Reorganization ruby and amqp workers
  app/amqp/amqp_config.rb
  app/workers/amqp/deposit_coin_address.rb
  app/workers/amqp/deposit_collection.rb
  app/workers/amqp/deposit_collection_fees.rb
  app/workers/amqp/market_ticker.rb
  app/workers/amqp/matching.rb
  app/workers/amqp/order_processor.rb
  app/workers/amqp/pusher_market.rb
  app/workers/amqp/pusher_member.rb
  app/workers/amqp/slave_book.rb
  app/workers/amqp/trade_executor.rb
  app/workers/amqp/withdraw_coin.rb
  app/workers/daemons/base.rb
  app/workers/daemons/blockchain.rb
  app/workers/daemons/global_state.rb
  app/workers/daemons/k.rb
  app/workers/daemons/withdraw_audit.rb
  app/workers/worker/deposit_coin_address.rb
  app/workers/worker/deposit_collection.rb
  app/workers/worker/deposit_collection_fees.rb
  app/workers/worker/market_ticker.rb
  app/workers/worker/matching.rb
  app/workers/worker/order_processor.rb
  app/workers/worker/pusher_market.rb
  app/workers/worker/pusher_member.rb
  app/workers/worker/slave_book.rb
  app/workers/worker/stats.rb
  app/workers/worker/trade_executor.rb
  app/workers/worker/withdraw_coin.rb
  docs/workers.md
  lib/daemons/blockchain.rb
  lib/daemons/daemons.god
  lib/daemons/daemons.rb
  lib/daemons/global_state.rb
  lib/daemons/k.rb
  lib/daemons/withdraw_audit.rb
  lib/peatio/bench/matching/direct.rb
  lib/peatio/bench/order_processing/direct.rb
  lib/peatio/bench/trade_execution/direct.rb
  spec/api/v2/public/markets_spec.rb
  spec/models/amqp_config_spec.rb
  spec/workers/deposit_coin_address_spec.rb
  spec/workers/deposit_collection_fees_spec.rb
  spec/workers/deposit_collection_spec.rb
  spec/workers/matching_spec.rb
  spec/workers/slave_book_spec.rb
  spec/workers/withdraw_coin_spec.rb
Labels: PR: Approved, v2.2

#2248 Replace Passgen gem with new password generator
  Gemfile
  Gemfile.lock
  lib/peatio/password_generator.rb
  lib/peatio/wallet_client/ethereum.rb
  lib/peatio/wallet_client/rippled.rb
  spec/services/wallet_service/geth_spec.rb
  spec/services/wallet_service/parity_spec.rb
Labels: PR: Approved, v2.1

#2247 Replace Passgen gem with new password generator
  Gemfile
  Gemfile.lock
  lib/password_generator.rb
  lib/wallet_client/ethereum.rb
  lib/wallet_client/rippled.rb
  spec/services/wallet_service/geth_spec.rb
  spec/services/wallet_service/parity_spec.rb
Labels: PR: Approved, v2.0

#2246 Replace Passgen gem with new password generator
  Gemfile
  Gemfile.lock
  lib/password_generator.rb
  lib/wallet_client/geth.rb
  lib/wallet_client/rippled.rb
  spec/services/wallet_service/geth_spec.rb
Labels: PR: Approved, v1.9

#2241 Major Market model rework
  app/api/v2/entities/market.rb
  app/api/v2/market/named_params.rb
  app/api/v2/market/orders.rb
  app/api/v2/order_helpers.rb
  app/api/v2/public/markets.rb
  app/controllers/admin/markets_controller.rb
  app/models/currency.rb
  app/models/market.rb
  app/models/member.rb
  app/models/order.rb
  app/models/order_ask.rb
  app/models/order_bid.rb
  app/serializers/serializers/event_api/trade_completed.rb
  app/trading/matching/engine.rb
  app/trading/matching/executor.rb
  app/views/admin/markets/index.html.erb
  app/views/admin/markets/show.html.erb
  config/templates/seed/markets.yml.erb
  db/migrate/20190624102330_rename_market_fields.rb
  db/schema.rb
  docs/api/errors.md
  lib/peatio/bench/injectors.rb
  lib/tasks/seed.rake
  spec/api/v2/market/orders_spec.rb
  spec/api/v2/public/markets_spec.rb
  spec/controllers/admin/markets_controller_spec.rb
  spec/factories/market.rb
  spec/models/currency_spec.rb
  spec/models/market_spec.rb
  spec/models/order_ask_spec.rb
  spec/models/order_bid_spec.rb
Labels: PR: Approved, v2.2

#2236 Improve sentry-raven error reporting
  app/api/v2/account/mount.rb
  app/api/v2/helpers.rb
  app/api/v2/management/helpers.rb
  app/api/v2/management/mount.rb
  app/api/v2/market/mount.rb
  app/api/v2/public/mount.rb
  app/controllers/application_controller.rb
Labels: PR: Approved, v2.2

#2234 Update logs in withdraw_coin worker
  app/workers/amqp/withdraw_coin.rb
  config/environments/production.rb
  config/environments/test.rb
  lib/peatio/tagged_logger.rb
Labels: PR: Approved, v2.2

#2261 Disable colorize logging in production
  config/environments/production.rb
Labels: PR: Approved, v2.2

#2257 Refactor blockchain daemon
  Gemfile
  Gemfile.lock
  app/workers/daemons/blockchain.rb
  config/cryptonodes.yml
  lib/peatio/bitcoin/client.rb
  lib/peatio/ethereum/client.rb
  spec/lib/bitcoin/blockchain_spec.rb
  spec/lib/ethereum/blockchain_spec.rb
Labels: PR: Approved, v2.2

#2252 Update admin API
  app/api/v2/admin/blockchain_params.rb
  app/api/v2/admin/blockchains.rb
  app/api/v2/admin/currencies.rb
  app/api/v2/admin/currency_params.rb
  app/api/v2/admin/deposit_params.rb
  app/api/v2/admin/deposits.rb
  app/api/v2/admin/entities/blockchain.rb
  app/api/v2/admin/entities/currency.rb
  app/api/v2/admin/entities/deposit.rb
  app/api/v2/admin/entities/market.rb
  app/api/v2/admin/entities/order.rb
  app/api/v2/admin/entities/wallet.rb
  app/api/v2/admin/entities/withdraw.rb
  app/api/v2/admin/market_params.rb
  app/api/v2/admin/markets.rb
  app/api/v2/admin/mount.rb
  app/api/v2/admin/order_params.rb
  app/api/v2/admin/orders.rb
  app/api/v2/admin/params_helpers.rb
  app/api/v2/admin/wallet_params.rb
  app/api/v2/admin/wallets.rb
  app/api/v2/admin/withdraw_params.rb
  app/api/v2/admin/withdraws.rb
  app/api/v2/entities/deposit.rb
  app/api/v2/exception_handlers.rb
  app/api/v2/market/orders.rb
  spec/api/v2/account/deposits_spec.rb
  spec/api/v2/admin/blockchains_spec.rb
  spec/api/v2/admin/currencies_spec.rb
  spec/api/v2/admin/deposits_spec.rb
  spec/api/v2/admin/markets_spec.rb
  spec/api/v2/admin/orders_spec.rb
  spec/api/v2/admin/wallets_spec.rb
  spec/api/v2/admin/withdraws_spec.rb
  spec/models/order_ask_spec.rb
  spec/support/rspec_matchers.rb
Labels: Feature: Admin API, v2.3

#2262 Remove http request for confirmations method
  app/models/blockchain.rb
  app/models/concerns/has_one_blockchain_through_currency.rb
  app/views/admin/blockchains/show.html.erb
  app/views/shared/admin/_account.html.erb
  spec/services/blockchain_service_spec.rb
Labels: PR: Approved, v2.2

#2265 Remove JWT token from response payload
  app/api/v2/auth/middleware.rb
  app/api/v2/public/currencies.rb
  docs/api/authenticating_in_management_api_v1.md
  spec/api/v2/helpers_spec.rb
Labels: PR: Approved, v2.2

#2267 Move slave book from amqp to ruby daemons
  app/trading/matching/order_book.rb
  app/workers/amqp/slave_book.rb
  app/workers/daemons/slave_book.rb
  lib/daemons/daemons.god
  spec/trading/matching/order_book_spec.rb
  spec/workers/matching_spec.rb
  spec/workers/slave_book_spec.rb
Labels: PR: Review, v2.2

#2269 Reload blockchain from DB before sync
  app/workers/daemons/blockchain.rb
Labels: PR: Approved, v2.2

#2263 Update ruby version and gems
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
Labels: PR: Approved

#2272 Fix bin/gendocs
  bin/gendocs
Labels: PR: Approved, v2.3

#2258 Major trading engine and logic rework with precision, rounding and matching flow improvements
  app/api/v2/order_helpers.rb
  app/models/market.rb
  app/models/order.rb
  app/models/order_bid.rb
  app/trading/matching/base_order.rb
  app/trading/matching/constants.rb
  app/trading/matching/engine.rb
  app/trading/matching/limit_order.rb
  app/trading/matching/market_order.rb
  app/trading/matching/order_book.rb
  config/templates/seed/markets.yml.erb
  db/migrate/20190711114027_update_markets_min_amount_and_price.rb
  db/schema.rb
  lib/peatio/rabbit_mq_http.rb
  spec/api/v2/entities/order_spec.rb
  spec/api/v2/management/trades_spec.rb
  spec/api/v2/market/orders_spec.rb
  spec/api/v2/market/trades_spec.rb
  spec/api/v2/public/markets_spec.rb
  spec/controllers/admin/markets_controller_spec.rb
  spec/factories/market.rb
  spec/models/market_spec.rb
  spec/models/order_spec.rb
  spec/trading/matching/engine_spec.rb
  spec/trading/matching/limit_order_spec.rb
  spec/trading/matching/market_order_spec.rb
  spec/trading/matching/order_book_spec.rb
Labels: PR: Pre-approved, v2.2

#2275 Fix issue with rake task release.rake in travis
  bin/gendocs
Labels: v2.2

#2276 Add min_confirmations field to Currency model entity
  app/api/v2/entities/currency.rb
Labels: PR: Approved, v2.2

#2243 Multi coin support for altcoins
  app/services/blockchain_service.rb
Labels: PR: Approved, v2.2

#2281 Remove withdrawal attempts
  app/models/withdraw.rb
  app/models/withdraws/coin.rb
  app/models/withdraws/fiat.rb
  app/workers/amqp/withdraw_coin.rb
  db/migrate/20190723202251_drop_withdraw_attempts.rb
  db/schema.rb
  spec/models/withdraw_spec.rb
  spec/workers/withdraw_coin_spec.rb
Labels: PR: Approved, v2.2

#2222 Fix GET /withdraws to include both fiat and crypto
  app/api/v2/account/withdraws.rb
Labels: PR: Approved, v2.2

#2219 [ci skip] Prepare for 2.2.0 release
  CHANGELOG.md
  docs/coins/plugins.md
  docs/releases/2.2.0.md
Labels: PR: WIP

#2286 Add bitcoincash and ripple
  Gemfile.lock
  Gemfile.plugin
Labels: v2.2

#2280 Fix double spending issue on withdraw
  .travis.yml
  CHANGELOG.md
  app/controllers/admin/withdraws/coins_controller.rb
  app/models/withdraw.rb
  app/models/withdraws/coin.rb
  app/models/withdraws/fiat.rb
  app/views/admin/withdraws/coins/show.html.erb
  app/workers/amqp/withdraw_coin.rb
  db/migrate/20190725131843_add_error_to_withdraw.rb
  db/schema.rb
  docs/releases/2.2.0.md
  lib/peatio/bitcoin/client.rb
  lib/peatio/bitcoin/wallet.rb
  lib/peatio/ethereum/client.rb
  lib/peatio/ethereum/wallet.rb
  spec/models/withdraw_spec.rb
  spec/workers/withdraw_coin_spec.rb
Labels: PR: Approved, v2.2
