Repository openware/peatio, pull requests merged in 2019-04, with the labels that each got.

#2150 Fix bin/gendocs
  bin/gendocs
Labels: PR: Approved, v2.1

#2153 Limit number of returned data from ranger `global.update`
  lib/daemons/global_state.rb
Labels: PR: Approved, v2.1

#2146 Upgrade Ruby on Rails to 5.2
  Gemfile
  Gemfile.lock
  bin/bundle
  bin/rails
  bin/update
  config/application.rb
  config/boot.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/application_controller_renderer.rb
  config/initializers/content_security_policy.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/new_framework_defaults.rb
  config/puma.rb
  db/schema.rb
  spec/api/v2/account/deposits_spec.rb
  spec/api/v2/account/withdraws_spec.rb
  spec/api/v2/auth/middleware_spec.rb
  spec/api/v2/cors/cors_spec.rb
  spec/api/v2/helpers_spec.rb
  spec/api/v2/management/jwt_authentication_middleware_spec.rb
  spec/api/v2/management/tools_spec.rb
  spec/api/v2/market/orders_spec.rb
  spec/api/v2/market/trades_spec.rb
  spec/api/v2/public/currencies_spec.rb
  spec/api/v2/public/markets_spec.rb
  spec/api/v2/public/member_levels_spec.rb
  spec/api/v2/public/tools_spec.rb
Labels: PR: Approved, v2.1

#2113 Rewrite callbacks for avoid using redirect_to :back
  app/controllers/admin/blockchains_controller.rb
  app/controllers/admin/currencies_controller.rb
  app/controllers/admin/deposits/fiats_controller.rb
  app/controllers/admin/markets_controller.rb
  app/controllers/admin/wallets_controller.rb
  config/locales/server.en.yml
Labels: PR: Approved, v2.0

#2103 Update setup-ubuntu.md
  docs/setup-ubuntu.md
Labels: PR: Approved, v1.9

#2157 Add note to withdraw
  app/api/v2/account/withdraws.rb
  app/api/v2/entities/withdraw.rb
  app/models/withdraw.rb
  app/models/withdraws/coin.rb
  app/models/withdraws/fiat.rb
  db/migrate/20190402130148_add_note_to_withdraws.rb
  db/schema.rb
  docs/api/errors.md
  spec/api/v2/account/withdraws_spec.rb
  spec/models/withdraw_spec.rb
Labels: PR: Approved, v2.1

#2156 Add missing paginations for deposit & withdraw on admin panel
  app/controllers/admin/deposits/base_controller.rb
  app/controllers/admin/deposits/coins_controller.rb
  app/controllers/admin/deposits/fiats_controller.rb
  app/controllers/admin/withdraws/base_controller.rb
  app/controllers/admin/withdraws/coins_controller.rb
  app/controllers/admin/withdraws/fiats_controller.rb
  app/views/admin/deposits/fiats/index.html.erb
  app/views/admin/withdraws/coins/index.html.erb
  app/views/admin/withdraws/fiats/index.html.erb
Labels: PR: Approved, v2.1

#2147 Move order submit to order_processor and remove Ordering service
  app/api/v2/helpers.rb
  app/api/v2/market/mount.rb
  app/api/v2/market/orders.rb
  app/api/v2/order_helpers.rb
  app/api/v2/public/markets.rb
  app/models/concerns/fee_chargeable.rb
  app/models/order.rb
  app/services/ordering.rb
  app/trading/matching/executor.rb
  app/workers/worker/order_processor.rb
  db/migrate/20190401121727_update_order_state.rb
  spec/api/v2/market/orders_spec.rb
  spec/factories/trade.rb
  spec/models/order_spec.rb
  spec/models/trade_spec.rb
  spec/services/ordering_spec.rb
Labels: PR: Approved, v2.1

#2160 Upgrade ruby to 2.6.2
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
  spec/models/account_spec.rb
Labels: PR: Approved, v2.1

#2126 Add filter by date in market/trades REST API call
  app/api/v2/helpers.rb
  app/api/v2/market/named_params.rb
  app/api/v2/market/trades.rb
  docs/api/errors.md
  spec/api/v2/market/trades_spec.rb
Labels: PR: Approved, v2.1

#2162 Add missing end in Admin::Deposits::FiatsController
  app/controllers/admin/withdraws/fiats_controller.rb
Labels: PR: Approved, v2.1

#2164 Revert ability to deposit from admin panel
  README.md
  app/views/admin/deposits/fiats/index.html.erb
Labels: PR: Approved, v2.1

#2167 Filter orders by type and order_type
  app/api/v2/market/orders.rb
  docs/api/errors.md
  spec/api/v2/market/orders_spec.rb
Labels: PR: Approved, v2.1

#2140 Add optional fields for operations API
  app/api/v2/management/entities/operation.rb
  app/api/v2/management/operations.rb
  spec/api/v2/management/operations_spec.rb
  spec/factories/operations.rb
Labels: PR: Approved, v2.1

#2169 Rewrite callbacks for avoid using redirect_to :back
  app/controllers/admin/blockchains_controller.rb
  app/controllers/admin/currencies_controller.rb
  app/controllers/admin/deposits/coins_controller.rb
  app/controllers/admin/deposits/fiats_controller.rb
  app/controllers/admin/markets_controller.rb
  app/controllers/admin/wallets_controller.rb
  app/controllers/admin/withdraws/coins_controller.rb
  app/controllers/admin/withdraws/fiats_controller.rb
Labels: PR: Approved, v2.1

#2178 Skip withdrawal in case of insufficient balance on hot wallet
  app/api/v2/management/entities/withdraw.rb
  app/models/withdraw.rb
  app/workers/worker/withdraw_coin.rb
  spec/models/withdraw_spec.rb
Labels: PR: Approved, v2.0

#2179 Skip withdrawal in case of insufficient balance on hot wallet
  app/api/v2/management/entities/withdraw.rb
  app/models/withdraw.rb
  app/workers/worker/withdraw_coin.rb
  spec/models/withdraw_spec.rb
Labels: PR: Approved, v2.1

#2177 [ci skip] Prepare for 2.1.0 release
  CHANGELOG.md
  docs/releases/2.0.0.md
  docs/releases/2.1.0.md
Labels: PR: Approved, v2.1

#2174 Implement Ethereum::Blockchain & Ethereum::Client
  app/services/blockchain_service2.rb
  lib/peatio/bitcoin/blockchain.rb
  lib/peatio/ethereum1/blockchain.rb
  lib/peatio/ethereum1/client.rb
  lib/peatio/peatio/transaction.rb
  spec/lib/bitcoin/blockchain_spec.rb
  spec/lib/ethereum/ethereum_spec.rb
  spec/resources/ethereum-data/rinkeby/2621840-2621842.json
  spec/resources/ethereum-data/rinkeby/transaction-receipts/2621840-2621842.json
  spec/resources/ethereum-data/rinkeby/transactions/0x826555325cec51c4d39b327e563ce3e8ee87e27be5911383f528724a62f0da5d.json
  spec/resources/ethereum-data/rinkeby/transactions/0xb60e22c6eed3dc8cd7bc5c7e38c50aa355c55debddbff5c1c4837b995b8ee96d.json
  spec/services/blockchain_service2_spec.rb
Labels: PR: WIP, v2.1

#2183 Define Exception hierarchy for Blockchain & Wallet
  app/models/wallet.rb
  app/services/blockchain_service2.rb
  lib/peatio/bitcoin/blockchain.rb
  lib/peatio/bitcoin/client.rb
  lib/peatio/bitcoin/wallet.rb
  lib/peatio/ethereum1/blockchain.rb
  lib/peatio/ethereum1/client.rb
  lib/peatio/peatio/blockchain/abstract.rb
  lib/peatio/peatio/blockchain/error.rb
  lib/peatio/peatio/wallet/abstract.rb
  lib/peatio/peatio/wallet/error.rb
  spec/lib/bitcoin/blockchain_spec.rb
  spec/lib/bitcoin/wallet_spec.rb
  spec/lib/ethereum/ethereum_spec.rb
Labels: PR: QA

#2187 Move to Blockchain & Wallet API v2
  app/models/blockchain.rb
  config/initializers/blockchain_api.rb
  config/initializers/wallet_api.rb
  spec/api/v2/account/balances_spec.rb
  spec/api/v2/account/deposits_spec.rb
  spec/api/v2/entities/member_spec.rb
  spec/api/v2/market/orders_spec.rb
  spec/api/v2/market/trades_spec.rb
  spec/controllers/admin/markets_controller_spec.rb
  spec/models/account_spec.rb
  spec/models/currency_spec.rb
  spec/models/market_spec.rb
  spec/models/withdraw_spec.rb
  spec/services/blockchain_service/bitcoin_spec.rb
  spec/services/blockchain_service/bitcoincash_spec.rb
  spec/services/blockchain_service/dash_spec.rb
  spec/services/blockchain_service/geth_spec.rb
  spec/services/blockchain_service/litecoin_spec.rb
  spec/services/blockchain_service/parity_spec.rb
  spec/services/blockchain_service/ripple_spec.rb
  spec/services/wallet_service/bitcoincashd_spec.rb
  spec/services/wallet_service/bitcoind_spec.rb
  spec/services/wallet_service/bitgo_spec.rb
  spec/services/wallet_service/dashd_spec.rb
  spec/services/wallet_service/geth_spec.rb
  spec/services/wallet_service/litecoind_spec.rb
  spec/services/wallet_service/parity_spec.rb
  spec/services/wallet_service/rippled_spec.rb
  spec/spec_helper.rb
Labels: PR: WIP

#2188 Add Ethereum::Wallet specs
  app/services/wallet_service2.rb
  lib/peatio/bitcoin/wallet.rb
  lib/peatio/ethereum1/blockchain.rb
  lib/peatio/ethereum1/wallet.rb
  lib/peatio/peatio/wallet/abstract.rb
  spec/lib/ethereum/blockchain_spec.rb
  spec/lib/ethereum/wallet_spec.rb
  spec/services/wallet_service2_spec.rb
Labels: PR: WIP
