Repository openware/peatio, pull requests merged in 2020-08, with the labels that each got.

#2644 Update 2-6 version with latest 2-5 features
  app/api/v2/admin/deposits.rb
  app/api/v2/admin/orders.rb
  app/api/v2/entities/order.rb
  app/api/v2/helpers.rb
  app/api/v2/management/trades.rb
  app/api/v2/market/named_params.rb
  app/api/v2/market/orders.rb
  app/api/v2/market/trades.rb
  app/api/v2/public/currencies.rb
  app/api/v2/public/markets.rb
  app/api/v2/public/trading_fees.rb
  app/jobs/cron/k_line.rb
  app/jobs/cron/ticker.rb
  app/models/currency.rb
  app/models/deposit.rb
  app/models/market.rb
  app/models/trade.rb
  app/models/trading_fee.rb
  app/services/k_line_service.rb
  app/services/wallet_service.rb
  app/workers/amqp/deposit_collection.rb
  app/workers/amqp/deposit_collection_fees.rb
  app/workers/daemons/deposit.rb
  config/environments/shared/cache.rb
  config/influxdb.yml
  config/templates/application.yml.erb
  docs/images/peatio/legacy_deposits_flow.png
  docs/images/peatio/new_deposits_flow.png
  docs/peatio/deposits_flow.md
  docs/tasks/distribution.md
  lib/peatio/influxdb.rb
  lib/tasks/distribution.rake
  spec/api/v2/admin/deposits_spec.rb
  spec/api/v2/entities/order_spec.rb
  spec/api/v2/public/currencies_spec.rb
  spec/api/v2/public/markets_spec.rb
  spec/api/v2/public/trading_fees_spec.rb
  spec/lib/influxdb_spec.rb
  spec/models/currency_spec.rb
  spec/models/deposit_spec.rb
  spec/services/blockchain_service_spec.rb
  spec/workers/deposit_collection_fees_spec.rb
  spec/workers/deposit_collection_spec.rb
  spec/workers/deposit_spec.rb
Labels: PR: Review, v2.6

#2645 Add caching for the most used public endpoints
  app/api/v2/public/currencies.rb
  app/api/v2/public/markets.rb
  app/api/v2/public/trading_fees.rb
  app/models/currency.rb
  app/models/market.rb
  app/models/trading_fee.rb
  spec/api/v2/public/currencies_spec.rb
  spec/api/v2/public/markets_spec.rb
  spec/api/v2/public/trading_fees_spec.rb
  spec/models/currency_spec.rb
Labels: v2.3

#2624 Dockerfile need to add apt-get upgrade
  Dockerfile
Labels: cherry-pick

#2585 Feature: add filters for blockchains
  app/api/v2/admin/blockchains.rb
  spec/api/v2/admin/blockchains_spec.rb
Labels: PR: Ready, v2.6

#2649 Add jobs table
  app/models/job.rb
  db/migrate/20200504183201_change_market_data.rb
  db/migrate/20200804091304_create_jobs.rb
  db/schema.rb
Labels: PR: Review, v2.5

#2650 2-5-stable: bitcoin & ethereum json client: pass endpoint path if provided
  lib/peatio/bitcoin/client.rb
  lib/peatio/ethereum/client.rb
  spec/lib/bitcoin/wallet_spec.rb
  spec/lib/ethereum/wallet_spec.rb
Labels: PR: Ready, v2.5

#2651 Accounting: add member_id in platform revenues (#2607)
  app/api/v2/management/helpers.rb
Labels: PR: Ready, v2.5

#2611 Traders PnL calculation
  app/api/v2/account/mount.rb
  app/api/v2/account/portfolio.rb
  app/api/v2/account/stats.rb
  app/api/v2/entities/pnl.rb
  app/api/v2/entities/portfolio.rb
  app/jobs/cron/stats_member_pnl.rb
  app/models/member.rb
  app/models/stats_member_pnl.rb
  app/models/trade.rb
  app/workers/daemons/cron_job.rb
  db/migrate/20200805102000_create_stats_member_pnl.rb
  db/migrate/20200805102001_create_stats_member_pnl_idx.rb
  db/migrate/20200805102002_increase_timestamp_precision.rb
  db/schema.rb
  docs/peatio/pnl_calculation.md
  spec/api/v2/account/portfolio_spec.rb
  spec/api/v2/account/stats_spec.rb
  spec/factories/currencies.rb
  spec/factories/stats_member_pnl.rb
  spec/jobs/stats_member_pnl_spec.rb
  spec/models/trade_spec.rb
  spec/support/influx_helper.rb
Labels: PR: Review, v2.5

#2589 AML integration
  Gemfile
  Gemfile.lock
  Gemfile.plugin
  app/api/v2/admin/beneficiaries.rb
  app/api/v2/admin/deposits.rb
  app/api/v2/admin/entities/refund.rb
  app/api/v2/admin/helpers.rb
  app/api/v2/admin/mount.rb
  app/api/v2/entities/beneficiary.rb
  app/jobs/cron/aml.rb
  app/jobs/cron/refund.rb
  app/models/abilities/accountant.rb
  app/models/abilities/admin.rb
  app/models/abilities/compliance.rb
  app/models/abilities/manager.rb
  app/models/abilities/superadmin.rb
  app/models/abilities/technical.rb
  app/models/beneficiary.rb
  app/models/deposit.rb
  app/models/refund.rb
  app/services/blockchain_service.rb
  app/services/wallet_service.rb
  app/workers/daemons/cron_job.rb
  config/initializers/aml.rb
  config/initializers/inflections.rb
  db/migrate/20200622185615_add_refunds.rb
  db/migrate/20200805144308_add_from_addresses_to_deposit.rb
  db/schema.rb
  lib/peatio/aml.rb
  lib/peatio/bitcoin/blockchain.rb
  lib/peatio/ethereum/blockchain.rb
  spec/api/v2/admin/beneficiaries_spec.rb
  spec/api/v2/admin/blockchains_spec.rb
  spec/lib/bitcoin/blockchain_spec.rb
  spec/lib/ethereum/blockchain_spec.rb
  spec/resources/bitcoin-data/b3aa85765aa52cf7eb0a7f0eb7ac3447b9b1a82b9323bdd8d73fc305073a3711.json
  spec/resources/bitcoin-data/miner_transaction.json
  spec/resources/bitcoin-data/vin-1ec4bf89b77f0d72ee41f41c97a6d380bd69e0221bf182b993b64bb37d017b57.json
  spec/resources/bitcoin-data/vin-64a04cad438b64e260bc0b832bde79913d618d3206e834de66bbcb1304629d61.json
  spec/resources/bitcoin-data/vin-8bde1da3d2315e09f910cb9782018fe243740c56cd7ca78a19016b169e74180a.json
  spec/services/wallet_service_spec.rb
  spec/support/fake_blockchain.rb
Labels: PR: Review, v2.5

#2652 Update structure.sql
  db/structure.sql
Labels: PR: Review, v2.5

#2632 Move data from main database to archive database
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
  app/models/job.rb
  config/database.yml
  db/migrate/20200728143753_compact_liabilities.rb
  lib/peatio/uuid.rb
  lib/tasks/job.rake
  spec/api/v2/management/markets_spec.rb
  spec/lib/tasks/job_spec.rb
  spec/lib/tasks/revert_spec.rb
  spec/spec_helper.rb
Labels: Category: Database, PR: WIP, v2.5

#2653 Add wallet balances. Add cron job for wallet balances update
  app/api/v2/admin/entities/wallet.rb
  app/api/v2/admin/wallets.rb
  app/jobs/cron/wallet_balances.rb
  app/services/wallet_service.rb
  app/workers/daemons/cron_job.rb
  db/migrate/20200806143442_add_wallet_balance.rb
  db/schema.rb
  spec/api/v2/admin/wallets_spec.rb
Labels: PR: Ready, v2.5

#2640 Enhancement: Filter trade by type && expose received_amount
  app/api/v2/entities/trade.rb
  app/api/v2/market/named_params.rb
  app/api/v2/market/trades.rb
  spec/api/v2/market/trades_spec.rb
Labels: v2.5

#2657 Fix: Add from_addresses on deposit creation
  app/services/blockchain_service.rb
  spec/services/blockchain_service_spec.rb
Labels: PR: Ready, v2.5

#2656 Fix: Add from_addresses on deposit creation
  app/services/blockchain_service.rb
  spec/services/blockchain_service_spec.rb
Labels: PR: Ready, cherry-pick, v2.6

#2658 Enhancement: Skip pending ERC-20 transaction in blockchain daemon
  lib/peatio/ethereum/blockchain.rb
  spec/lib/ethereum/blockchain_spec.rb
  spec/resources/ethereum-data/rinkeby/transactions/0xb44861cb188356c67bec27a35abab1b7ef33fc402330faa9ac4d863ef621d7b1.json
Labels: PR: Ready, v2.4

#2659 Enhancement: Skip pending ERC-20 transaction in blockchain daemon
  lib/peatio/ethereum/blockchain.rb
  spec/lib/ethereum/blockchain_spec.rb
  spec/resources/ethereum-data/rinkeby/transactions/0xb44861cb188356c67bec27a35abab1b7ef33fc402330faa9ac4d863ef621d7b1.json
Labels: PR: Ready, v2.3

#2643 Feature: Introduce yaml base permissions in peatio
  app/api/v2/admin/abilities.rb
  app/api/v2/admin/adjustments.rb
  app/api/v2/admin/beneficiaries.rb
  app/api/v2/admin/blockchains.rb
  app/api/v2/admin/currencies.rb
  app/api/v2/admin/deposits.rb
  app/api/v2/admin/engines.rb
  app/api/v2/admin/markets.rb
  app/api/v2/admin/members.rb
  app/api/v2/admin/mount.rb
  app/api/v2/admin/operations.rb
  app/api/v2/admin/orders.rb
  app/api/v2/admin/trades.rb
  app/api/v2/admin/trading_fees.rb
  app/api/v2/admin/wallets.rb
  app/api/v2/admin/withdraws.rb
  app/api/v2/helpers.rb
  app/models/abilities.rb
  app/models/abilities/accountant.rb
  app/models/abilities/admin.rb
  app/models/abilities/compliance.rb
  app/models/abilities/manager.rb
  app/models/abilities/superadmin.rb
  app/models/abilities/support.rb
  app/models/abilities/technical.rb
  app/models/ability.rb
  app/models/admin_ability.rb
  app/models/member.rb
  config/abilities.yml
  spec/api/v2/admin/abilities_spec.rb
  spec/factories/beneficiaries.rb
  spec/models/abilities_spec.rb
  spec/models/admin_ability_spec.rb
Labels: PR: Ready, v2.6

#2660 feature: limit number of currencies/markets
  app/models/currency.rb
  app/models/market.rb
  config/templates/application.yml.erb
  spec/models/currency_spec.rb
  spec/models/market_spec.rb
Labels: PR: Review, v2.6

#2661 Speedup tests execution
  spec/api/v2/account/balances_spec.rb
  spec/api/v2/entities/account_spec.rb
  spec/api/v2/entities/member_spec.rb
  spec/api/v2/entities/order_spec.rb
  spec/api/v2/entities/trade_spec.rb
  spec/api/v2/management/entities/balance_spec.rb
  spec/api/v2/management/entities/deposit_spec.rb
  spec/api/v2/management/entities/operation_spec.rb
  spec/api/v2/management/entities/trade_spec.rb
  spec/api/v2/management/entities/transfer_spec.rb
  spec/api/v2/management/entities/withdraw_spec.rb
  spec/api/v2/management/operations_spec.rb
  spec/api/v2/management/transfers_spec.rb
  spec/lib/influxdb_spec.rb
  spec/models/adjustment_spec.rb
  spec/models/member_spec.rb
  spec/models/order_spec.rb
  spec/models/trade_spec.rb
  spec/models/tradinng_fee_spec.rb
  spec/services/blockchain_service_spec.rb
  spec/trading/matching/executor_spec.rb
Labels: PR: Review, v2.6

#2666 Fix wallet balance parse in the daemons
  app/models/wallet.rb
  app/services/wallet_service.rb
  app/workers/amqp/withdraw_coin.rb
  spec/api/v2/admin/wallets_spec.rb
  spec/services/wallet_service_spec.rb
Labels: PR: Review, v2.5

#2665 Improve Engines and Markets seed
  app/models/engine.rb
  config/templates/seed/engines.yml.erb
  config/templates/seed/markets.yml.erb
  lib/tasks/seed.rake
  spec/api/v2/admin/engines_spec.rb
  spec/factories/engine.rb
Labels: PR: Review, cherry-pick, v2.6

#2667 Fix wallet load_balance method. Update WalletBalances job
  app/jobs/cron/wallet_balances.rb
  app/services/wallet_service.rb
Labels: PR: Review, v2.6

#2668 Update peatio-bitgo version. Change rid length for withdraw
  Gemfile.lock
  Gemfile.plugin
  db/migrate/20200824172823_update_withdraw_rid.rb
  db/schema.rb
Labels: PR: Review, cherry-pick, v2.5

#2669 Update peatio-bitgo version. Change rid length for withdraw
  Gemfile.lock
  Gemfile.plugin
  db/migrate/20200824172823_update_withdraw_rid.rb
  db/schema.rb
Labels: PR: Review, v2.6

#2664 Feature: added transfer_type in deposit and withdraw
  app/api/v2/entities/deposit.rb
  app/api/v2/entities/withdraw.rb
  app/api/v2/management/deposits.rb
  app/api/v2/management/entities/deposit.rb
  app/api/v2/management/entities/withdraw.rb
  app/api/v2/management/withdraws.rb
  app/models/deposit.rb
  app/models/withdraw.rb
  config/initializers/transfer_types.rb
  config/transfer_types.yml
  db/migrate/20200826091118_add_transfer_type_in_depost_withdraw.rb
  db/schema.rb
  spec/api/v2/admin/deposits_spec.rb
  spec/api/v2/management/deposits_spec.rb
  spec/api/v2/management/withdraws_spec.rb
Labels: PR: Review, v2.6

#2671 Enhancement: Add ability to create market by engine name
  app/api/v2/admin/markets.rb
  app/models/market.rb
  spec/api/v2/admin/markets_spec.rb
Labels: PR: Review, v2.6
