Repository openware/peatio, pull requests merged in 2020-09, with the labels that each got.

#2675 Add rake task for load trades and build k-lines. Update 2-4 migration documentation
  docs/migrations/2_4_migration.md
  docs/migrations/vault_settings_migration.md
  lib/tasks/import.rake
Labels: PR: Review, v2.6

#2674 Update CI to build images for branches matching {fix,integration}/*
  .drone.yml
Labels: PR: Ready, v2.6

#2676 Enhancement: Delete symbol from currency table
  app/api/v2/admin/currencies.rb
  app/api/v2/entities/currency.rb
  app/models/currency.rb
  config/abilities.yml
  config/templates/seed/currencies.yml.erb
  db/migrate/20200902082403_delete_symbol_from_currency.rb
  db/schema.rb
  db/structure.sql
  spec/api/v2/admin/blockchains_spec.rb
  spec/api/v2/admin/currencies_spec.rb
  spec/api/v2/public/currencies_spec.rb
  spec/factories/currencies.rb
  spec/services/blockchain_service_spec.rb
Labels: PR: Ready, v2.6

#2672 Feature: Add token type to currency model
  app/api/v2/admin/currencies.rb
  app/api/v2/admin/entities/currency.rb
  app/models/currency.rb
  config/templates/seed/currencies.yml.erb
  db/migrate/20200903113109_add_parent_id_to_currency.rb
  db/schema.rb
  spec/api/v2/admin/currencies_spec.rb
  spec/factories/currencies.rb
  spec/models/currency_spec.rb
Labels: PR: Ready, v2.6

#2680 Feature: Add rake task to fetch currency current price
  lib/tasks/fetch.rake
Labels: PR: Ready, v2.6

#2682 Feature: Implement smart position changing for market and currencies
  app/api/v2/admin/currencies.rb
  app/api/v2/admin/markets.rb
  app/api/v2/management/currencies.rb
  app/api/v2/management/markets.rb
  app/models/currency.rb
  app/models/helpers/reorder_position.rb
  app/models/market.rb
  db/migrate/20200909083000_remove_default_position_value_from_currencies_and_markets.rb
  db/schema.rb
  spec/api/v2/admin/currencies_spec.rb
  spec/api/v2/admin/markets_spec.rb
  spec/api/v2/management/currencies_spec.rb
  spec/api/v2/management/markets_spec.rb
  spec/factories/currencies.rb
  spec/factories/market.rb
  spec/models/currency_spec.rb
  spec/models/market_spec.rb
  spec/spec_helper.rb
Labels: PR: Ready, v2.6

#2685 Enhancement: Update spread deposit with currency price
  app/models/currency.rb
  app/models/withdraw.rb
  app/services/wallet_service.rb
  spec/services/wallet_service_spec.rb
Labels: PR: Review, v2.6

#2684 Feature: Implement adaptive gas_price setting
  Gemfile
  Gemfile.lock
  app/services/wallet_service.rb
  lib/peatio/ethereum/wallet.rb
  spec/lib/ethereum/wallet_spec.rb
  spec/services/wallet_service_spec.rb
Labels: PR: Review, v2.6

#2687 Fix: Wallet links update. Deposit spread wallet recalculation
  app/models/currency.rb
  app/services/wallet_service.rb
  spec/models/currency_spec.rb
  spec/services/wallet_service_spec.rb
Labels: PR: Review, v2.6

#2688 Optimize PnL main query
  app/jobs/cron/stats_member_pnl.rb
Labels: v2.5

#2696 Feature: Add CMC integration
  app/api/v2/coin_market_cap/assets.rb
  app/api/v2/coin_market_cap/helpers.rb
  app/api/v2/coin_market_cap/mount.rb
  app/api/v2/coin_market_cap/orderbook.rb
  app/api/v2/coin_market_cap/summary.rb
  app/api/v2/coin_market_cap/ticker.rb
  app/api/v2/coin_market_cap/trades.rb
  app/api/v2/mount.rb
  app/models/market.rb
  config/initializers/jwt_rack.rb
  docs/peatio/coin_market_cap.md
  lib/peatio/coin_market_cap.rb
  spec/api/v2/coin_market_cap/assets_spec.rb
  spec/api/v2/coin_market_cap/orderbook_spec.rb
  spec/api/v2/coin_market_cap/summary_spec.rb
  spec/api/v2/coin_market_cap/ticker_spec.rb
  spec/api/v2/coin_market_cap/trades_spec.rb
Labels: PR: Ready, v2.6

#2699 Optimize PnL main query
  app/jobs/cron/stats_member_pnl.rb
Labels: v2.6
