Repository openware/peatio, pull requests merged in 2020-11, with the labels that each got.

#2705 Feature: Submit and cancel finex-spot orders via Peatio API
  app/api/v2/admin/orders.rb
  app/api/v2/entities/order.rb
  app/api/v2/market/orders.rb
  app/api/v2/order_helpers.rb
  app/models/engine.rb
  app/models/order.rb
  config/amqp.yml
  db/schema.rb
  lib/tasks/job.rake
  spec/api/v2/admin/orders_spec.rb
  spec/api/v2/market/orders_spec.rb
Labels: PR: Review, v2.5

#2689 Feature: Peatio orders Management API
  app/api/v2/admin/orders.rb
  app/api/v2/entities/order.rb
  app/api/v2/management/entities/order.rb
  app/api/v2/management/mount.rb
  app/api/v2/management/orders.rb
  app/api/v2/market/orders.rb
  app/api/v2/order_helpers.rb
  app/models/engine.rb
  app/models/order.rb
  config/amqp.yml
  lib/tasks/job.rake
  spec/api/v2/admin/orders_spec.rb
  spec/api/v2/management/orders_spec.rb
  spec/api/v2/market/orders_spec.rb
Labels: PR: Review, v2.6

#2733 Add matching exchange for trading daemons. Delete deprecated amqp configs
  config/amqp.yml
Labels: PR: Review, v2.6

#2736 Fix: Abilities for user permissions
  app/api/v2/account/balances.rb
  app/api/v2/account/beneficiaries.rb
  app/api/v2/account/deposits.rb
  app/api/v2/account/stats.rb
  app/api/v2/account/transactions.rb
  app/api/v2/account/withdraws.rb
  app/api/v2/market/orders.rb
  app/api/v2/market/trades.rb
  spec/api/v2/account/balances_spec.rb
  spec/api/v2/account/beneficiaries_spec.rb
  spec/api/v2/account/deposits_spec.rb
  spec/api/v2/account/stats_spec.rb
  spec/api/v2/account/transactions_spec.rb
  spec/api/v2/account/withdraws_spec.rb
  spec/api/v2/market/orders_spec.rb
  spec/api/v2/market/trades_spec.rb
Labels: PR: Ready, v2.6

#2738 Fix: Add ability to configure wallet features from settings
  app/services/wallet_service.rb
Labels: PR: Review, v2.6

#2740 Enhancement: Update withdraw limits logic
  app/jobs/cron/withdraw_audit.rb
  app/models/withdraw.rb
  docs/peatio/withdraw_limits.md
  spec/models/withdraw_spec.rb
Labels: PR: Review, v2.6

#2741 Enhancement: Generate wallet settings on creation
  app/api/v2/admin/wallets.rb
  app/models/wallet.rb
  spec/api/v2/admin/wallets_spec.rb
Labels: PR: Review, v2.6

#2742 Fix specs for PostgreSQL
  spec/api/v2/admin/deposits_spec.rb
  spec/api/v2/admin/engines_spec.rb
  spec/api/v2/admin/wallets_spec.rb
Labels: PR: Review, v2.6

#2744 Add Gnosis base plugin
  app/api/v2/account/withdraws.rb
  app/api/v2/admin/entities/withdraw.rb
  app/api/v2/admin/withdraws.rb
  app/models/withdraw.rb
  config/initializers/wallet_api.rb
  db/migrate/20201118151056_add_withdraw_metadata.rb
  db/schema.rb
  lib/peatio/gnosis/client.rb
  lib/peatio/gnosis/wallet.rb
  spec/api/v2/admin/withdraws_spec.rb
Labels: PR: Review, v2.6

#2735 Feature: Add Opendax wallet plugin
  .drone.yml
  app/services/wallet_service.rb
  config/initializers/wallet_api.rb
  config/templates/application.yml.erb
  docs/peatio/opendax_wallet_plugin.md
  lib/peatio/ethereum/blockchain.rb
  lib/peatio/opendax/client.rb
  lib/peatio/opendax/wallet.rb
  spec/lib/opendax/wallet_spec.rb
  spec/spec_helper.rb
Labels: PR: Review, v2.6

#2678 Feature: add admin currencies fetch filters
  app/api/v2/admin/currencies.rb
  spec/api/v2/admin/currencies_spec.rb
Labels: PR: QA, v2.6

#2710 Update dependencies
  .drone.yml
  Gemfile
  Gemfile.lock
Labels: PR: Review, v2.6

#2746 Fix: tx[input] fetch
  lib/peatio/ethereum/blockchain.rb
Labels: PR: Ready, v2.6
