Repository openware/peatio, pull requests merged in 2020-12, with the labels that each got.

#2750 Feature: allow user to change the email
  app/models/member.rb
  db/migrate/20201204134602_add_index_on_members_ui_d.rb
  db/schema.rb
  spec/api/v2/account/balances_spec.rb
Labels: PR: WIP, v2.6

#2755 Update API docs for 2-5-stable
  app/api/v2/admin/mount.rb
  app/api/v2/management/mount.rb
  app/api/v2/mount.rb
  config/initializers/versioning.rb
  docs/api/peatio_admin_api_v2.md
  docs/api/peatio_management_api_v2.md
  docs/api/peatio_user_api_v2.md
  docs/api/swagger/admin_api.json
  docs/api/swagger/management_api.json
  docs/api/swagger/user_api.json
Labels: Category: Documentation, PR: Ready, v2.5

#2754 Update API docs for 2-6-stable
  app/api/v2/admin/entities/wallet.rb
  app/api/v2/admin/mount.rb
  app/api/v2/entities/payment_address.rb
  app/api/v2/management/mount.rb
  app/api/v2/mount.rb
  config/initializers/versioning.rb
  docs/api/peatio_admin_api_v2.md
  docs/api/peatio_management_api_v2.md
  docs/api/peatio_user_api_v2.md
  docs/api/swagger/admin_api.json
  docs/api/swagger/management_api.json
  docs/api/swagger/user_api.json
Labels: Category: Documentation, PR: Ready, v2.6

#2753 Bump master with 2.7.0. Update API docs
  VERSION
  app/api/v2/admin/entities/wallet.rb
  app/api/v2/admin/mount.rb
  app/api/v2/entities/payment_address.rb
  app/api/v2/management/mount.rb
  app/api/v2/mount.rb
  config/initializers/versioning.rb
  docs/api/peatio_admin_api_v2.md
  docs/api/peatio_management_api_v2.md
  docs/api/peatio_user_api_v2.md
  docs/api/swagger/admin_api.json
  docs/api/swagger/management_api.json
  docs/api/swagger/user_api.json
Labels: 2.7, Category: Documentation, PR: Ready

#2757 Update currency price field
  app/api/v2/admin/currencies.rb
  app/api/v2/admin/entities/currency.rb
  db/migrate/20201206205429_change_currency_price.rb
  db/schema.rb
Labels: 2.7, PR: Review

#2756 Update currency price field
  app/api/v2/admin/currencies.rb
  app/api/v2/admin/entities/currency.rb
  db/migrate/20201206205429_change_currency_price.rb
  db/schema.rb
Labels: PR: Review, v2.6

#2758 Update drone config
  .drone.yml
Labels: v2.6

#2759 Update drone config
  .drone.yml
Labels: 2.7

#2760 Add the ability to exclude users by role from PnL calculation
  app/jobs/cron/stats_member_pnl.rb
  docs/peatio/pnl_calculation.md
  spec/jobs/stats_member_pnl_spec.rb
Labels: PR: Review, v2.6

#2751 Add the ability to exclude users by role from PnL calculation
  app/jobs/cron/stats_member_pnl.rb
  docs/peatio/pnl_calculation.md
  spec/jobs/stats_member_pnl_spec.rb
Labels: 2.7

#2761 Enhancement: Return deposit address in account entity
  app/api/v2/account/balances.rb
  app/api/v2/admin/entities/member.rb
  app/api/v2/entities/account.rb
  spec/api/v2/account/balances_spec.rb
  spec/api/v2/admin/withdraw_limts_spec.rb
Labels: PR: Ready, v2.6

#2747 Enhancement: Return deposit address in account entity
  app/api/v2/account/balances.rb
  app/api/v2/admin/entities/member.rb
  app/api/v2/entities/account.rb
  spec/api/v2/account/balances_spec.rb
  spec/api/v2/admin/withdraw_limts_spec.rb
Labels: 2.7, PR: Ready, cherry-pick

#2762 Skip deposit fee collection transaction
  app/models/account.rb
  app/models/beneficiary.rb
  app/models/blockchain.rb
  app/models/currency.rb
  app/models/currency_wallet.rb
  app/models/engine.rb
  app/models/member.rb
  app/models/operations/asset.rb
  app/models/operations/expense.rb
  app/models/operations/liability.rb
  app/models/operations/revenue.rb
  app/models/order.rb
  app/models/order_ask.rb
  app/models/order_bid.rb
  app/models/payment_address.rb
  app/models/refund.rb
  app/models/stats_member_pnl.rb
  app/models/trade.rb
  app/models/trading_fee.rb
  app/models/transaction.rb
  app/models/trigger.rb
  app/models/wallet.rb
  app/models/withdraw.rb
  app/models/withdraw_limit.rb
  app/models/withdraws/coin.rb
  app/models/withdraws/fiat.rb
  app/services/blockchain_service.rb
  app/services/wallet_service.rb
  app/workers/daemons/deposit.rb
  db/migrate/20201207134745_create_transactions.rb
  db/schema.rb
  lib/peatio/ethereum/wallet.rb
  lib/peatio/opendax/wallet.rb
  spec/factories/transaction.rb
  spec/lib/ethereum/wallet_spec.rb
  spec/lib/opendax/wallet_spec.rb
  spec/services/blockchain_service_spec.rb
  spec/services/wallet_service_spec.rb
Labels: PR: Review, v2.6

#2765 Remove market creation validation for unvisible market
  app/models/currency.rb
  app/models/market.rb
  spec/models/currency_spec.rb
  spec/models/market_spec.rb
Labels: PR: Review, v2.6

#2769 Fix: Update migration for currency field
  db/migrate/20201206205429_change_currency_price.rb
Labels: 2.7, PR: Review

#2770 Fix: Update migration for currency field
  db/migrate/20201206205429_change_currency_price.rb
Labels: PR: Review, v2.6

#2766 Add Release Notes for 2-4 version
  docs/releases/2.3.0.md
  docs/releases/2.4.0.md
Labels: Category: Documentation, PR: Review, v2.4

#2771 Add Release Notes for previous versions. Update CHANGELOG.md
  CHANGELOG.md
  docs/releases/2.3.0.md
  docs/releases/2.4.0.md
  docs/releases/2.5.0.md
  docs/releases/2.6.0.md
Labels: Category: Documentation, PR: Review, v2.6

#2768 Add Release Notes for previous versions. Update CHANGELOG.md
  CHANGELOG.md
  docs/releases/2.3.0.md
  docs/releases/2.4.0.md
  docs/releases/2.5.0.md
  docs/releases/2.6.0.md
Labels: 2.7, Category: Documentation, PR: Review

#2764 Update order:archive job. Add documentation
  app/models/member.rb
  app/models/order.rb
  docs/tasks/order_archive.md
  docs/tasks/order_close.md
  docs/tasks/order_liabilities_compact.md
  lib/tasks/job.rake
Labels: 2.7, PR: Review

#2772 Fix: Save skipped txs in deposit spread
  app/services/wallet_service.rb
  spec/services/wallet_service_spec.rb
Labels: PR: Review, v2.6

#2784 Fix: Add indexes on trade table
  db/migrate/20201222155655_add_indexes_on_trades.rb
  db/schema.rb
Labels: v2.6

#2773 Enhancement: Update opendax wallet plugin docs
  docs/peatio/opendax_wallet_plugin.md
Labels: Category: Documentation, PR: Review, cherry-pick, v2.6

#2788 Fix: Thread safe account creation
  app/models/member.rb
Labels: v2.6

#2789 Enhancement: Cleanup application.yml
  app/api/v2/account/withdraws.rb
  app/api/v2/helpers.rb
  config/application.rb
  config/templates/application.yml.erb
  spec/api/v2/account/withdraws_spec.rb
Labels: PR: Ready, v2.6

#2785 Feature: Add Airdrop api
  app/api/v2/admin/airdrops.rb
  app/api/v2/admin/mount.rb
  app/models/transfer.rb
  docs/airdrop.md
  lib/peatio/airdrop.rb
  spec/jobs/stats_member_pnl_spec.rb
  spec/lib/peatio/airdrop_spec.rb
  spec/resources/airdrops/1.csv
Labels: PR: Review, v2.6
