Repository openware/peatio, pull requests merged in 2020-04, with the labels that each got.

#2508 Fix: add ability to cancel order by uuid
  app/api/v2/market/orders.rb
  spec/api/v2/market/orders_spec.rb
Labels: PR: Ready, v2.4

#2513 Update export task with data field for market
  lib/tasks/export.rake
Labels: PR: Ready, v2.4

#2516 Add feature to search currency by code or name in /public/currencies
  app/api/v2/public/currencies.rb
  spec/api/v2/public/currencies_spec.rb
Labels: PR: Ready, v2.4

#2509 Experimental: Remove LOCKING_BUFFER_FACTOR from buy market order
  app/api/v2/order_helpers.rb
  app/models/order_bid.rb
  spec/api/v2/market/orders_spec.rb
  spec/models/order_ask_spec.rb
Labels: PR: QA Approved, PR: Ready, v2.4

#2524 Update sdk image to 2.4.5
  .drone.yml
  VERSION
Labels: PR: Ready, v2.5

#2522 Return wallet balance in admin api
  app/api/v2/admin/entities/wallet.rb
  app/api/v2/admin/wallets.rb
  app/models/wallet.rb
  spec/api/v2/admin/wallets_spec.rb
  spec/factories/wallet.rb
  spec/spec_helper.rb
  spec/workers/withdraw_coin_spec.rb
Labels: PR: Ready, v2.5

#2521 Feature: Alive check for a blockchain node to get the latest block
  app/api/v2/admin/blockchains.rb
  spec/api/v2/admin/blockchains_spec.rb
Labels: PR: Ready, v2.5

#2519 Enhancement: Add ability to fail withdraw from skipped state
  app/models/withdraw.rb
  spec/models/withdraw_spec.rb
Labels: PR: Ready, v2.5

#2518 Feature: Expose deposit address && beneficiaries for admin endpoints
  app/api/v2/admin/entities/account.rb
  app/api/v2/admin/entities/member.rb
  app/api/v2/admin/entities/withdraw.rb
  spec/api/v2/admin/members_spec.rb
  spec/api/v2/admin/withdraws_spec.rb
Labels: PR: Ready, v2.5

#2527 Enhancement: Add Engine model
  Gemfile.lock
  app/api/v2/admin/entities/market.rb
  app/api/v2/admin/markets.rb
  app/models/engine.rb
  app/models/market.rb
  app/models/order.rb
  app/models/order_ask.rb
  app/models/order_bid.rb
  config/templates/seed/engines.yml.erb
  config/templates/seed/markets.yml.erb
  db/migrate/20200414155144_create_engines.rb
  db/schema.rb
  db/seeds.rb
  lib/tasks/seed.rake
  spec/api/v2/admin/markets_spec.rb
  spec/factories/engine.rb
  spec/factories/market.rb
  spec/models/market_spec.rb
  spec/spec_helper.rb
Labels: PR: Ready, v2.5

#2528 Remove old helpers
  app/controllers/application_controller.rb
  app/helpers/application_helper.rb
Labels: PR: Ready, v2.5

#2530 Feature: Include post_only order in market/depth
  app/models/order.rb
  app/models/order_ask.rb
  app/models/order_bid.rb
  config/initializers/matching_engine.rb
Labels: PR: Review, v2.4

#2531 Feature: Include post_only order in market/depth
  app/models/order.rb
  app/models/order_ask.rb
  app/models/order_bid.rb
  config/initializers/matching_engine.rb
Labels: PR: Review, v2.5

#2532 Update irix and peatio-bitgo versions
  Gemfile
  Gemfile.lock
  Gemfile.plugin
Labels: PR: WIP, v2.5

#2533 Update irix and peatio-bitgo versions
  Gemfile
  Gemfile.lock
  Gemfile.plugin
Labels: PR: WIP, v2.4

#2534 Update column type for data engines
  db/migrate/20200420141636_change_data_engine.rb
  db/schema.rb
Labels: PR: Review, v2.5

#2536 Update peatio-core version
  Gemfile
  Gemfile.lock
Labels: PR: Ready, v2.5

#2537 Feature: Add user PnL API module
  app/api/v2/account/mount.rb
  app/api/v2/account/portfolio.rb
  app/api/v2/entities/portfolio.rb
  spec/api/v2/account/portfolio_spec.rb
Labels: PR: Review, v2.5

#2538 Add admin api for engines
  app/api/v2/admin/engines.rb
  app/api/v2/admin/entities/engine.rb
  app/api/v2/admin/entities/market.rb
  app/api/v2/admin/markets.rb
  app/api/v2/admin/mount.rb
  app/models/abilities/admin.rb
  app/models/abilities/superadmin.rb
  app/models/abilities/technical.rb
  spec/api/v2/admin/engines_spec.rb
Labels: PR: Ready, v2.5
