Repository openware/peatio, pull requests merged in 2020-07, with the labels that each got.

#2631 Add rake task for distribution
  docs/tasks/distribution.md
  lib/tasks/distribution.rake
Labels: PR: Review, v2.5

#2626 InfluxDB sharding
  app/models/trade.rb
  app/services/k_line_service.rb
  config/influxdb.yml
  lib/peatio/influxdb.rb
  spec/lib/influxdb_spec.rb
Labels: PR: Review, v2.5

#2633 Feature: Add redis cluster support
  config/environments/shared/cache.rb
  config/templates/application.yml.erb
Labels: PR: Review, v2.5

#2587 Feature: add ability to filter deposits by email
  app/api/v2/admin/deposits.rb
  spec/api/v2/admin/deposits_spec.rb
Labels: PR: Ready, v2.6

#2636 Rewrite deposit collection flow
  app/api/v2/admin/deposits.rb
  app/models/deposit.rb
  app/services/wallet_service.rb
  app/workers/amqp/deposit_collection.rb
  app/workers/amqp/deposit_collection_fees.rb
  app/workers/daemons/deposit.rb
  docs/images/peatio/legacy_deposits_flow.png
  docs/images/peatio/new_deposits_flow.png
  docs/peatio/deposits_flow.md
  spec/api/v2/admin/deposits_spec.rb
  spec/models/deposit_spec.rb
  spec/services/blockchain_service_spec.rb
  spec/workers/deposit_collection_fees_spec.rb
  spec/workers/deposit_collection_spec.rb
  spec/workers/deposit_spec.rb
Labels: PR: WIP, v2.5
