Repository openware/peatio, pull requests merged in 2020-02, with the labels that each got.

#2443 Improve errors messages in Account model. Add daemons locking by key
  Gemfile.lock
  app/models/account.rb
  app/workers/daemons/base.rb
  app/workers/daemons/blockchain.rb
  spec/models/account_spec.rb
Labels: v2.4

#2446 Add ability to select orders with different states
  app/api/v2/market/orders.rb
  spec/api/v2/market/orders_spec.rb
Labels: PR: Review, v2.4

#2437 Feature: Rake task for revert trading activity for a particular user
  app/models/member.rb
  app/models/trade.rb
  lib/tasks/revert.rake
  spec/lib/tasks/revert_spec.rb
Labels: PR: Approved, v2.4

#2426 Feature: rake tasks for drop accounting and extract configs
  lib/tasks/clear.rake
  lib/tasks/export.rake
Labels: PR: Approved, v2.4

#2447 Add ability to select orders with different states
  app/api/v2/market/orders.rb
  spec/api/v2/market/orders_spec.rb
Labels: PR: Approved, v2.3

#2429 Remove :touch_account after currency creation
  app/api/v2/account/deposits.rb
  app/api/v2/management/helpers.rb
  app/api/v2/order_helpers.rb
  app/models/currency.rb
  app/models/deposit.rb
  app/models/member.rb
  app/models/operations.rb
  app/models/withdraw.rb
  app/trading/matching/executor.rb
  spec/api/v2/account/deposits_spec.rb
  spec/api/v2/management/entities/balance_spec.rb
  spec/api/v2/management/operations_spec.rb
  spec/api/v2/management/transfers_spec.rb
  spec/factories/account.rb
  spec/factories/operations.rb
  spec/models/withdraw_spec.rb
  spec/serializers/serializers/event_api/order_canceled_spec.rb
  spec/serializers/serializers/event_api/order_completed_spec.rb
  spec/serializers/serializers/event_api/order_created_spec.rb
  spec/serializers/serializers/event_api/order_updated_spec.rb
  spec/serializers/serializers/event_api/trade_completed_spec.rb
  spec/services/wallet_service_spec.rb
  spec/workers/deposit_coin_address_spec.rb
Labels: PR: Approved, v2.4

#2445 Remove account_id from Withdraw model
  app/api/v2/admin/entities/withdraw.rb
  app/api/v2/admin/withdraws.rb
  app/models/withdraw.rb
  app/models/withdraws/coin.rb
  app/models/withdraws/fiat.rb
  db/migrate/20200211124707_remove_account_from_withdraws.rb
  db/schema.rb
  spec/api/v2/management/withdraws_spec.rb
  spec/models/withdraw_spec.rb
  spec/services/blockchain_service_spec.rb
Labels: PR: Ready, v2.4

#2449 Remove :touch account after user creation
  app/models/member.rb
  app/trading/matching/executor.rb
  spec/api/v2/account/balances_spec.rb
  spec/api/v2/account/transactions_spec.rb
  spec/api/v2/account/withdraws_spec.rb
  spec/api/v2/admin/adjustments_spec.rb
  spec/api/v2/admin/members_spec.rb
  spec/api/v2/admin/withdraws_spec.rb
  spec/api/v2/entities/member_spec.rb
  spec/api/v2/management/deposits_spec.rb
  spec/api/v2/management/withdraws_spec.rb
  spec/lib/tasks/revert_spec.rb
  spec/models/account_spec.rb
  spec/models/adjustment_spec.rb
  spec/models/member_spec.rb
  spec/models/transfer_spec.rb
  spec/serializers/serializers/event_api/trade_completed_spec.rb
  spec/services/blockchain_service_spec.rb
Labels: PR: Ready, v2.4

#2441 Record Trades and K-lines to InfluxDB
  .drone.yml
  Gemfile
  Gemfile.lock
  app/api/v2/entities/public_trade.rb
  app/api/v2/public/markets.rb
  app/models/trade.rb
  app/services/k_line_service.rb
  app/trading/global.rb
  app/trading/matching/executor.rb
  app/workers/amqp/influx_writer.rb
  app/workers/amqp/market_ticker.rb
  app/workers/daemons/k.rb
  bin/setup
  config/amqp.yml
  config/backend.yml
  config/influxdb.yml
  db/influxdb.sql
  docs/workers.md
  lib/daemons/daemons.god
  lib/peatio/influxdb.rb
  spec/api/v2/public/markets_spec.rb
  spec/support/influx_helper.rb
Labels: PR: Ready, v2.4

#2450 Replace legacy authentication with jwt-rack
  Gemfile
  Gemfile.lock
  app/api/v2/auth/jwt_authenticator.rb
  app/api/v2/auth/middleware.rb
  app/api/v2/auth/utils.rb
  app/api/v2/helpers.rb
  app/api/v2/mount.rb
  app/controllers/admin/base_controller.rb
  app/controllers/application_controller.rb
  bin/setup
  config/initializers/jwt.rb
  config/initializers/jwt_rack.rb
  lib/peatio/authorization/bearer.rb
  spec/api/v2/auth/jwt_authenticator_spec.rb
  spec/api/v2/auth/middleware_spec.rb
  spec/api/v2/mount_spec.rb
  spec/controllers/admin/currencies_controller_spec.rb
  spec/support/auth_helper.rb
Labels: PR: Review, v2.4

#2448 Rake task for import users and active accounts
  lib/tasks/export.rake
  lib/tasks/import.rake
Labels: v2.4

#2453 Fix: Add report exception to screen for OrderProcessor initialize
  app/workers/amqp/order_processor.rb
Labels: PR: Ready, v2.4

#2452 Fix: Add report exception to screen for OrderProcessor initialize
  app/workers/amqp/order_processor.rb
Labels: PR: Ready, v2.3

#2451 Remove deprecated amqp daemons
  app/amqp/amqp_config.rb
  app/amqp/amqp_queue.rb
  app/api/v2/order_helpers.rb
  app/models/deposit.rb
  app/models/market.rb
  app/models/member.rb
  app/models/operations/liability.rb
  app/models/order.rb
  app/models/payment_address.rb
  app/models/trade.rb
  app/models/withdraw.rb
  app/services/services/health_checker.rb
  app/trading/matching/engine.rb
  app/trading/matching/executor.rb
  app/workers/amqp/deposit_coin_address.rb
  app/workers/amqp/deposit_collection_fees.rb
  app/workers/amqp/matching.rb
  app/workers/amqp/order_processor.rb
  app/workers/amqp/pusher_market.rb
  app/workers/amqp/pusher_member.rb
  app/workers/daemons/global_state.rb
  app/workers/daemons/k.rb
  config/initializers/event_api.rb
  lib/daemons/amqp_daemon.rb
  lib/peatio/amqp/config.rb
  lib/peatio/amqp/event_api.rb
  lib/peatio/amqp/queue.rb
  lib/peatio/bench/matching/amqp.rb
  lib/peatio/bench/order_processing/amqp.rb
  lib/peatio/bench/trade_execution/amqp.rb
  lib/tasks/failures.rake
  spec/api/v2/admin/orders_spec.rb
  spec/api/v2/market/orders_spec.rb
  spec/models/amqp_config_spec.rb
  spec/models/amqp_queue_spec.rb
  spec/models/operations/liability_spec.rb
  spec/models/order_spec.rb
  spec/models/payment_address_spec.rb
  spec/services/blockchain_service_spec.rb
  spec/spec_helper.rb
  spec/trading/matching/engine_spec.rb
  spec/trading/matching/executor_spec.rb
  spec/trading/matching/order_book_spec.rb
  spec/workers/matching_spec.rb
Labels: v2.4

#2454 Add rake task for export and import PaymentAddresses
  lib/tasks/export.rake
  lib/tasks/import.rake
Labels: v2.4

#2455 Imrove Deposit and Withdraw filters
  app/api/v2/account/deposits.rb
  app/api/v2/account/withdraws.rb
  app/models/deposit.rb
  spec/api/v2/account/deposits_spec.rb
  spec/api/v2/account/withdraws_spec.rb
Labels: PR: Ready, v2.4

#2456 Imrove Deposit and Withdraw filters
  app/api/v2/account/deposits.rb
  app/api/v2/account/withdraws.rb
  app/models/deposit.rb
  spec/api/v2/account/deposits_spec.rb
  spec/api/v2/account/withdraws_spec.rb
Labels: PR: Ready, v2.3

#2457 Remove precision from order timestamps
  db/migrate/20200220133250_revert_order_timestamp_precision.rb
  db/schema.rb
Labels: PR: Ready, v2.3

#2459 Add finex as third party engine support. Add to_reject withdrawal state. Add maker role
  app/models/member.rb
  app/models/order.rb
  app/models/withdraw.rb
  app/workers/daemons/withdraw_audit.rb
  config/initializers/matching_engine.rb
  spec/models/withdraw_spec.rb
Labels: PR: Review, v2.4
