Repository openware/peatio, pull requests merged in 2020-05, with the labels that each got.

#2526 Feature: add POST admin/blockchain/process_block
  app/api/v2/admin/blockchains.rb
  app/services/blockchain_service.rb
  app/workers/daemons/blockchain.rb
  spec/api/v2/admin/blockchains_spec.rb
Labels: PR: Ready, v2.5

#2510 Enhancement: Improve deposit model. Add ability to collect through api
  app/api/v2/admin/deposits.rb
  app/api/v2/webhooks_helpers.rb
  app/models/account.rb
  app/models/deposit.rb
  app/services/blockchain_service.rb
  app/workers/amqp/deposit_collection.rb
  app/workers/amqp/deposit_collection_fees.rb
  spec/api/v2/account/balances_spec.rb
  spec/api/v2/admin/deposits_spec.rb
  spec/factories/orders.rb
  spec/factories/withdraw.rb
  spec/lib/tasks/revert_spec.rb
  spec/models/deposit_spec.rb
  spec/services/blockchain_service_spec.rb
  spec/trading/accounting_spec.rb
  spec/workers/deposit_collection_fees_spec.rb
  spec/workers/deposit_collection_spec.rb
Labels: PR: QA, PR: Review, v2.5

#2542 Add renew process to vault initializer
  config/initializers/vault.rb
Labels: PR: WIP, v2.5

#2545 Fix market entity for admin api
  app/api/v2/admin/entities/market.rb
  spec/api/v2/admin/markets_spec.rb
Labels: PR: Ready, v2.5

#2549 Update gems dependencies
  Gemfile.lock
  Gemfile.plugin
Labels: PR: WIP, v2.5

#2550 Use scheduling in blockchain daemon to reflect config changes in DB
  app/services/blockchain_service.rb
  app/workers/daemons/base.rb
  app/workers/daemons/blockchain.rb
Labels: PR: Ready, v2.5

#2543 Delete encrypt for market data. Update upstream daemon
  app/models/engine.rb
  app/models/market.rb
  app/workers/daemons/upstream.rb
  config/initializers/vault.rb
  config/templates/seed/engines.yml.erb
  config/templates/seed/markets.yml.erb
  db/migrate/20200504183201_change_market_data.rb
  db/schema.rb
  spec/models/market_spec.rb
  spec/workers/upstream_spec.rb
Labels: PR: Review, v2.5

#2505 Websocket documentation for peatio 2.4
  docs/api/websocket_api.md
Labels: PR: Ready, v2.4

#2548 Fix: Remove nested SQL transactions in blockchain daemon. Update deposit model
  app/models/deposit.rb
  app/workers/daemons/blockchain.rb
  spec/models/deposit_spec.rb
Labels: PR: QA, PR: Review, v2.5

#2552 Use scheduling in blockchain daemon to reflect config changes in DB
  app/services/blockchain_service.rb
  app/workers/daemons/base.rb
  app/workers/daemons/blockchain.rb
Labels: PR: Ready, v2.4

#2551 Fix: Avoid to use join in admin API for tables with a large amount of data. Change Kaminari usage in pagination
  app/api/v2/admin/operations.rb
  app/api/v2/admin/orders.rb
  app/api/v2/admin/trades.rb
  app/api/v2/helpers.rb
  app/models/order.rb
  app/models/order_ask.rb
  app/models/order_bid.rb
  db/migrate/20200513153429_add_uuid_index_for_orders.rb
  db/schema.rb
Labels: PR: Review, v2.5

#2553 Add default value for data market field
  app/models/market.rb
  spec/models/market_spec.rb
Labels: PR: Review, v2.5

#2555 Fix market migration with existing data
  bin/init_vault
  db/migrate/20200504183201_change_market_data.rb
  spec/factories/engine.rb
Labels: PR: Ready, v2.5

#2556 Misc improvements
  app/services/blockchain_service.rb
  spec/api/v2/admin/blockchains_spec.rb
  spec/services/blockchain_service_spec.rb
  spec/services/wallet_service_spec.rb
  spec/support/fake_blockchain.rb
Labels: v2.6

#2554 Add peatio electrum gem
  .drone.yml
  Dockerfile
  Gemfile
  Gemfile.lock
  Gemfile.plugin
Labels: v2.6

#2560 Update irix version
  Gemfile
  Gemfile.lock
  app/workers/daemons/upstream.rb
Labels: PR: Review, v2.5

#2561 Update irix version
  Gemfile
  Gemfile.lock
  app/workers/daemons/upstream.rb
Labels: PR: Review, v2.6

#2559 Feature: Add Management API for beneficiaries
  app/api/v2/management/beneficiaries.rb
  app/api/v2/management/mount.rb
  spec/api/v2/management/beneficiaries_spec.rb
Labels: PR: Review, v2.6

#2558 Feature: Add Management API for beneficiaries
  app/api/v2/management/beneficiaries.rb
  app/api/v2/management/mount.rb
  spec/api/v2/management/beneficiaries_spec.rb
Labels: PR: Review, v2.5

#2546 Add docs about engines
  docs/peatio/engine.md
Labels: PR: Review, v2.5

#2565 Improve orders and trades filtes. Add data field in engine admin API
  app/api/v2/admin/engines.rb
  app/api/v2/admin/entities/engine.rb
  app/api/v2/market/orders.rb
  app/api/v2/market/trades.rb
  spec/api/v2/admin/engines_spec.rb
  spec/api/v2/market/orders_spec.rb
  spec/api/v2/market/trades_spec.rb
Labels: PR: Review, v2.5

#2564 Improve orders and trades filtes. Add data field in engine admin API
  app/api/v2/admin/engines.rb
  app/api/v2/admin/entities/engine.rb
  app/api/v2/market/orders.rb
  app/api/v2/market/trades.rb
  spec/api/v2/admin/engines_spec.rb
  spec/api/v2/market/orders_spec.rb
  spec/api/v2/market/trades_spec.rb
Labels: PR: Review, v2.6

#2568 Renew of vault token with ENV. Remove sensitive data from admin entities
  app/api/v2/admin/blockchains.rb
  app/api/v2/admin/entities/blockchain.rb
  app/api/v2/admin/entities/wallet.rb
  app/api/v2/admin/wallets.rb
  config/initializers/vault.rb
  spec/api/v2/admin/wallets_spec.rb
Labels: PR: Review, v2.6

#2571 Add export rake task for engines
  lib/tasks/export.rake
Labels: PR: Review, v2.5

#2573 Change Influxdb configuration names
  .drone.yml
  config/influxdb.yml
Labels: PR: Review, v2.6

#2569 Add export rake task for engines
  lib/tasks/export.rake
Labels: PR: Review, v2.6

#2572 Improve market states for api
  app/api/v2/admin/orders.rb
  app/api/v2/helpers.rb
  app/api/v2/management/trades.rb
  app/api/v2/market/named_params.rb
  app/api/v2/market/orders.rb
  app/api/v2/market/trades.rb
  app/api/v2/public/markets.rb
  app/jobs/cron/k_line.rb
  app/jobs/cron/ticker.rb
  app/models/market.rb
  spec/api/v2/public/markets_spec.rb
Labels: PR: Review, v2.5

#2567 Feature: Add filters for currencies, markets and wallets
  app/api/v2/admin/currencies.rb
  app/api/v2/admin/markets.rb
  app/api/v2/admin/wallets.rb
  spec/api/v2/admin/currencies_spec.rb
  spec/api/v2/admin/markets_spec.rb
  spec/api/v2/admin/wallets_spec.rb
Labels: PR: Ready, v2.4

#2577 Add ability to set user rate limit via ENV variable
  app/api/v2/constraints.rb
Labels: PR: Review, v2.3

#2578 Add ability to set user rate limit
  app/api/v2/constraints.rb
Labels: PR: Review, v2.4

#2579 Add ability to set user rate limit
  app/api/v2/constraints.rb
Labels: PR: Review, v2.5

#2580 Add ability to set user rate limit
  app/api/v2/constraints.rb
Labels: PR: Review, v2.6

#2584 Do not expose engine data in admin api
  app/api/v2/admin/entities/engine.rb
  spec/api/v2/admin/engines_spec.rb
Labels: PR: Review, v2.6

#2562 Feature: Portfolio calculation
  app/api/v2/account/portfolio.rb
  app/api/v2/entities/portfolio.rb
  app/jobs/cron/portfolio.rb
  app/models/member.rb
  app/models/portfolio.rb
  app/models/trade.rb
  app/workers/daemons/cron_job.rb
  db/migrate/20200514132805_create_portfolios.rb
  db/schema.rb
  docs/peatio/portfolio_calculation.md
  spec/api/v2/account/portfolio_spec.rb
  spec/factories/currencies.rb
  spec/factories/portfolios.rb
  spec/jobs/portfolio_spec.rb
  spec/models/trade_spec.rb
Labels: PR: Review, v2.5
