Repository openware/peatio, pull requests merged in 2020-03, with the labels that each got.

#2462 Fix: Change beneficiary address validation
  app/models/beneficiary.rb
  spec/api/v2/account/beneficiaries_spec.rb
Labels: PR: Ready, v2.4

#2460 Feature: Add ability to create deposits and confirm withdrawals through Webhooks.
  Gemfile.lock
  Gemfile.plugin
  app/api/v2/public/mount.rb
  app/api/v2/public/webhooks.rb
  app/api/v2/webhooks_helpers.rb
  app/models/payment_address.rb
  app/models/wallet.rb
  app/services/wallet_service.rb
  app/workers/amqp/deposit_coin_address.rb
  lib/tasks/bitgo_webhooks.rake
  spec/api/v2/public/webhooks.rb
  spec/services/wallet_service_spec.rb
Labels: PR: Ready, v2.4

#2463 Feature: Add filters by deposit/withdraw states
  app/api/v2/account/transactions.rb
  spec/api/v2/account/transactions_spec.rb
Labels: PR: Ready, v2.4

#2471 Fix: Collect deposits after sql transaction
  app/api/v2/webhooks_helpers.rb
  spec/api/v2/public/webhooks.rb
Labels: PR: Ready, v2.4

#2444 Add ability to filter zero user balances
  app/api/v2/account/balances.rb
  spec/api/v2/account/balances_spec.rb
Labels: PR: Ready, v2.4

#2468 Enhancement: Delete total header from admin API endpoints
  Gemfile
  Gemfile.lock
  app/api/v2/admin/operations.rb
  app/api/v2/admin/orders.rb
  app/api/v2/admin/trades.rb
  app/api/v2/helpers.rb
  app/api/v2/market/orders.rb
  app/api/v2/market/trades.rb
  config/initializers/api_pagination.rb
  spec/api/v2/admin/orders_spec.rb
  spec/api/v2/market/orders_spec.rb
  spec/api/v2/market/trades_spec.rb
Labels: PR: Ready, v2.4

#2464 Enhancement: Add validation for trading fees, blockchains, transfers
  app/api/v2/account/withdraws.rb
  app/api/v2/admin/blockchains.rb
  app/api/v2/admin/members.rb
  app/api/v2/admin/trading_fees.rb
  app/api/v2/public/trading_fees.rb
  app/models/blockchain.rb
  app/models/member.rb
  app/models/trading_fee.rb
  app/models/transfer.rb
  spec/api/v2/admin/blockchains_spec.rb
  spec/api/v2/admin/members_spec.rb
  spec/api/v2/admin/trading_fees_spec.rb
  spec/api/v2/public/trading_fees_spec.rb
Labels: PR: Ready, v2.4

#2474 Initialize Blockchain and Wallet adapters in service creation. Updat…
  Gemfile.lock
  Gemfile.plugin
  app/services/blockchain_service.rb
  app/services/wallet_service.rb
  config/initializers/blockchain_api.rb
  config/initializers/wallet_api.rb
  spec/services/blockchain_service_spec.rb
  spec/services/wallet_service_spec.rb
Labels: v2.4

#2476 Improve API filtering for order history
  app/api/v2/market/orders.rb
  spec/api/v2/market/orders_spec.rb
  spec/factories/orders.rb
Labels: PR: Ready, v2.4

#2478 Add Trading docs
  docs/api/trading_api.md
Labels: PR: Review, v2.4

#2477 Update Peatio API documentation
  docs/api/peatio_admin_api_v2.md
  docs/api/peatio_management_api_v2.md
  docs/api/peatio_user_api_v2.md
  docs/api/swagger/admin_api.json
  docs/api/swagger/management_api.json
  docs/api/swagger/user_api.json
Labels: PR: Ready, v2.4

#2466 Update to Rails 5.2.4
  Gemfile
  Gemfile.lock
  app/api/v2/admin/withdraws.rb
  app/api/v2/validations.rb
  spec/api/v2/management/currencies_spec.rb
  spec/api/v2/management/deposits_spec.rb
  spec/api/v2/management/markets_spec.rb
  spec/api/v2/management/operations_spec.rb
  spec/api/v2/management/transfers_spec.rb
  spec/api/v2/management/withdraws_spec.rb
Labels: v2.4

#2483 Fix: Clean rails built in warnings
  app/api/v2/admin/currencies.rb
  app/api/v2/admin/markets.rb
  app/api/v2/admin/wallets.rb
  app/api/v2/validations.rb
  app/models/withdraw.rb
Labels: PR: Ready, v2.4

#2482 Fix ./bin/setup
  bin/setup
Labels: PR: Ready, v2.4

#2480 Add ability to read tickers from influx
  app/api/v2/public/markets.rb
  app/models/trade.rb
  db/migrate/20200316132213_add_taker_type_to_trade.rb
  db/schema.rb
  spec/api/v2/public/markets_spec.rb
  spec/models/trade_spec.rb
Labels: PR: Ready, v2.4

#2481 Fix: add ability to search order by uuid
  app/api/v2/market/named_params.rb
  app/api/v2/market/orders.rb
  lib/peatio/uuid.rb
  spec/api/v2/market/orders_spec.rb
  spec/lib/uuid_spec.rb
Labels: PR: Ready, v2.4

#2458 Add Peatio Upstream worker. Add Opendax Upstream
  Gemfile
  Gemfile.lock
  app/api/v2/admin/entities/market.rb
  app/api/v2/admin/markets.rb
  app/models/account.rb
  app/models/beneficiary.rb
  app/models/blockchain.rb
  app/models/currency.rb
  app/models/market.rb
  app/models/operations/asset.rb
  app/models/operations/expense.rb
  app/models/operations/liability.rb
  app/models/operations/revenue.rb
  app/models/order.rb
  app/models/order_ask.rb
  app/models/order_bid.rb
  app/models/trade.rb
  app/models/trading_fee.rb
  app/models/trigger.rb
  app/models/wallet.rb
  app/workers/amqp/influx_writer.rb
  app/workers/amqp/market_ticker.rb
  app/workers/daemons/upstream.rb
  config/initializers/upstreams.rb
  db/migrate/20200317080916_add_data_to_market.rb
  db/schema.rb
  lib/peatio/upstream/opendax.rb
  spec/api/v2/admin/markets_spec.rb
  spec/api/v2/public/markets_spec.rb
  spec/lib/peatio/opendax_spec.rb
  spec/models/market_spec.rb
  spec/workers/upstream_spec.rb
Labels: PR: Review, v2.4

#2486 Feature: add POST /management/markets/list API endpoint
  app/api/v2/management/markets.rb
  spec/api/v2/management/markets_spec.rb
Labels: PR: Ready, v2.4

#2487 Feature: add POST management/currencies/list API endpoint
  app/api/v2/management/currencies.rb
  spec/api/v2/management/currencies_spec.rb
Labels: PR: Ready, v2.4

#2475 Prepare doc for Peatio v2.4 migration
  docs/migrations/2_4_migration.md
Labels: v2.4

#2490 Features and improvements pack
  Dockerfile
  Gemfile.lock
  app/assets/stylesheets/layouts/_basic.scss
  app/models/operations.rb
  app/trading/matching/constants.rb
  app/trading/matching/executor.rb
  app/workers/amqp/deposit_coin_address.rb
  config/amqp.yml
  config/environments/production.rb
  lib/peatio/ethereum/wallet.rb
  lib/peatio/vault/totp.rb
  spec/lib/ethereum/wallet_spec.rb
  spec/models/operations_spec.rb
  spec/support/matching_helper.rb
Labels: PR: Ready, v2.4

#2395 Experimental: Tweak public markets endpoint
  app/api/v2/account/balances.rb
  app/api/v2/entities/ticker.rb
  app/api/v2/helpers.rb
  app/api/v2/public/markets.rb
  app/models/market.rb
  spec/api/v2/account/balances_spec.rb
  spec/api/v2/public/markets_spec.rb
  spec/factories/currencies.rb
  spec/factories/market.rb
Labels: PR: Ready, v2.4

#2492 Enhancement: Improve deposits, withdrawals and transactions filters
  app/api/v2/account/deposits.rb
  app/api/v2/account/transactions.rb
  app/api/v2/account/withdraws.rb
  spec/api/v2/account/deposits_spec.rb
  spec/api/v2/account/transactions_spec.rb
  spec/api/v2/account/withdraws_spec.rb
Labels: PR: Ready, v2.4

#2485 Add CronJob Daemon for K-lines and Tickers
  app/api/v2/entities/ticker.rb
  app/api/v2/helpers.rb
  app/api/v2/order_helpers.rb
  app/api/v2/public/markets.rb
  app/jobs/cron/k_line.rb
  app/jobs/cron/ticker.rb
  app/models/market.rb
  app/models/order_ask.rb
  app/models/order_bid.rb
  app/services/k_line_service.rb
  app/services/tickers_service.rb
  app/trading/global.rb
  app/workers/amqp/influx_writer.rb
  app/workers/amqp/market_ticker.rb
  app/workers/daemons/cron_job.rb
  app/workers/daemons/global_state.rb
  app/workers/daemons/k.rb
  app/workers/daemons/slave_book.rb
  config/templates/seed/markets.yml.erb
  spec/api/v2/market/orders_spec.rb
  spec/api/v2/public/markets_spec.rb
  spec/models/global_spec.rb
  spec/models/market_spec.rb
  spec/models/order_ask_spec.rb
  spec/models/order_bid_spec.rb
  spec/models/order_spec.rb
  spec/services/tickers_service_spec.rb
  spec/workers/slave_book_spec.rb
Labels: PR: Review, v2.4

#2501 Fix: Ability to save wallet secret on update
  app/api/v2/admin/wallets.rb
  spec/api/v2/admin/wallets_spec.rb
Labels: PR: Ready, v2.4

#2500 Fix: Ability to save wallet secret on update
  app/api/v2/admin/wallets.rb
  spec/api/v2/admin/wallets_spec.rb
Labels: PR: Ready, v2.5

#2497 Fix: Add created_at to transaction entity
  app/api/v2/account/transactions.rb
  app/api/v2/entities/transactions.rb
Labels: PR: Ready, v2.5

#2503 Update peatio plugins
  Gemfile.lock
  Gemfile.plugin
  app/services/wallet_service.rb
Labels: PR: Ready, v2.5

#2504 Update peatio plugins
  Gemfile.lock
  Gemfile.plugin
  app/services/wallet_service.rb
Labels: PR: Ready, v2.4

#2506 Update irix version
  Gemfile
  Gemfile.lock
Labels: PR: Ready, v2.4
