Repository openware/peatio, pull requests merged in 2020-01, with the labels that each got.

#2438 Fix: Add validations for crypto address in beneficiary
  app/api/v2/exception_handlers.rb
  app/models/beneficiary.rb
  spec/api/v2/account/beneficiaries_spec.rb
Labels: PR: Approved, v2.4

#2435 Enhauncement: update sdk version
  .drone.yml
Labels: Category: CI

#2436 Enhauncement: update sdk version
  .drone.yml
Labels: Category: CI

#2439 Fix: disable beneficiary validation on withdrawal failing
  app/models/withdraw.rb
  spec/models/withdraw_spec.rb
Labels: PR: Approved, v2.4

#2442 Fix: disable beneficiary validation on withdrawal failing
  app/models/withdraw.rb
  spec/models/withdraw_spec.rb
Labels: PR: Approved, v2.3
