Repository openware/peatio, pull requests merged in 2020-06, with the labels that each got.

#2582 Feature: Add ability to resend beneficiary pin
  app/api/v2/account/beneficiaries.rb
  app/api/v2/entities/beneficiary.rb
  app/models/beneficiary.rb
  db/migrate/20200527130534_add_sent_at_field_to_beneficiary.rb
  db/schema.rb
  spec/api/v2/account/beneficiaries_spec.rb
  spec/models/beneficiary_spec.rb
Labels: PR: Review, v2.4

#2570 Enhancement: add management api to retrieve non-zero balances
  app/api/v2/management/accounts.rb
  spec/api/v2/management/accounts_spec.rb
Labels: PR: Review, v2.4

#2595 Fix: Update error handling for trading_fee api
  app/api/v2/admin/deposits.rb
  app/api/v2/admin/trading_fees.rb
  spec/api/v2/admin/trading_fees_spec.rb
Labels: PR: Review, v2.6

#2594 Fix: Update error handling for trading_fee api
  app/api/v2/admin/deposits.rb
  app/api/v2/admin/trading_fees.rb
  spec/api/v2/admin/trading_fees_spec.rb
Labels: PR: Review, v2.4

#2593 Fix: Update error handling for trading_fee api
  app/api/v2/admin/deposits.rb
  app/api/v2/admin/trading_fees.rb
  spec/api/v2/admin/trading_fees_spec.rb
Labels: PR: Review, v2.5

#2602 Fix: Avoid to use join in admin API for tables with a large amount of data. Change Kaminari usage in pagination
  app/api/v2/admin/operations.rb
  app/api/v2/admin/orders.rb
  app/api/v2/admin/trades.rb
  app/api/v2/helpers.rb
  app/models/order.rb
  app/models/order_ask.rb
  app/models/order_bid.rb
  db/migrate/20200513153429_add_uuid_index_for_orders.rb
  db/schema.rb
Labels: PR: Review, v2.4

#2598 Enhancement: add management api to retrieve non-zero balances
  app/api/v2/management/accounts.rb
  spec/api/v2/management/accounts_spec.rb
Labels: v2.6

#2603 Enhancement: add pagination to POST management/accounts/balances
  app/api/v2/management/accounts.rb
  spec/api/v2/management/accounts_spec.rb
Labels: v2.4

#2597 Enhancement: add management api to retrieve non-zero balances
  app/api/v2/management/accounts.rb
  spec/api/v2/management/accounts_spec.rb
Labels: v2.5

#2606 Fix versionning generation in CI (#2604)
  .drone.yml
  bin/gendocs
  bin/genversion
Labels: PR: Ready, v2.5

#2605 Fix versionning generation in CI (#2604)
  .drone.yml
  bin/gendocs
  bin/genversion
Labels: PR: Ready, v2.4

#2599 Fix: Bitgo address generation
  Gemfile.lock
  Gemfile.plugin
  app/api/v2/account/deposits.rb
  app/api/v2/entities/payment_address.rb
  app/api/v2/public/webhooks.rb
  app/api/v2/webhooks_helpers.rb
  app/models/account.rb
  app/models/payment_address.rb
  app/workers/amqp/deposit_coin_address.rb
  spec/api/v2/account/deposits_spec.rb
  spec/api/v2/public/webhooks.rb
  spec/models/account_spec.rb
  spec/models/payment_address_spec.rb
  spec/workers/deposit_coin_address_spec.rb
Labels: PR: WIP, v2.5

#2610 Remove account_id from Withdraw model (#2445)
  app/api/v2/admin/entities/withdraw.rb
  app/api/v2/admin/withdraws.rb
  app/models/withdraw.rb
  app/models/withdraws/coin.rb
  app/models/withdraws/fiat.rb
  db/migrate/20200211124707_remove_account_from_withdraws.rb
  db/schema.rb
  spec/api/v2/management/withdraws_spec.rb
  spec/models/withdraw_spec.rb
  spec/services/blockchain_service_spec.rb
Labels: PR: Review, v2.3

#2612 Configurate wallet_service with pa_secret on deposit collection
  app/services/wallet_service.rb
Labels: PR: Review, v2.6

#2590 Feature: Add ability to resend beneficiary pin
  app/api/v2/account/beneficiaries.rb
  app/api/v2/entities/beneficiary.rb
  app/models/beneficiary.rb
  db/migrate/20200527130534_add_sent_at_field_to_beneficiary.rb
  db/schema.rb
  spec/api/v2/account/beneficiaries_spec.rb
  spec/models/beneficiary_spec.rb
Labels: PR: Review, v2.5

#2591 Feature: Add ability to resend beneficiary pin
  app/api/v2/account/beneficiaries.rb
  app/api/v2/entities/beneficiary.rb
  app/models/beneficiary.rb
  db/migrate/20200527130534_add_sent_at_field_to_beneficiary.rb
  db/schema.rb
  spec/api/v2/account/beneficiaries_spec.rb
  spec/models/beneficiary_spec.rb
Labels: PR: Review, v2.6

#2616 Add symbolize keys to WalletService init. Update wallet templates
  app/services/wallet_service.rb
  config/templates/seed/wallets.yml.erb
  spec/services/wallet_service_spec.rb
  spec/workers/deposit_collection_spec.rb
Labels: PR: Review, v2.6

#2617 Add ability to configure database pool size
  config/database.yml
Labels: PR: Review, v2.5

#2618 Update configuration for database pool
  config/database.yml
  config/puma.rb
Labels: PR: Review, v2.5

#2619 Update configuration for database pool
  config/database.yml
  config/puma.rb
Labels: PR: Review, v2.6

#2620 Fix secret replace in deposit collection
  app/services/wallet_service.rb
Labels: PR: Review, v2.6

#2601 Add to Currency model description, homepage and price
  app/api/v2/admin/currencies.rb
  app/api/v2/entities/currency.rb
  db/migrate/20200504183201_change_market_data.rb
  db/migrate/20200603164002_add_description_homepage_price_to_currency_model.rb
  db/schema.rb
Labels: PR: Review, v2.6

#2615 Enhancement: Skip pending ERC-20 transaction in blockchain daemon
  lib/peatio/ethereum/blockchain.rb
  spec/lib/ethereum/blockchain_spec.rb
  spec/resources/ethereum-data/rinkeby/transactions/0xb44861cb188356c67bec27a35abab1b7ef33fc402330faa9ac4d863ef621d7b1.json
Labels: PR: Review, v2.5

#2625 Add caching for the most used public endpoints
  app/api/v2/public/currencies.rb
  app/api/v2/public/markets.rb
  app/api/v2/public/trading_fees.rb
  app/jobs/cron/ticker.rb
  app/models/currency.rb
  app/models/market.rb
  app/models/trading_fee.rb
  spec/api/v2/public/currencies_spec.rb
  spec/api/v2/public/markets_spec.rb
  spec/api/v2/public/trading_fees_spec.rb
  spec/models/currency_spec.rb
Labels: PR: Review, v2.5

#2627 Feature: expose maker & taker fee for order entity
  app/api/v2/entities/order.rb
  spec/api/v2/entities/order_spec.rb
Labels: PR: Ready, Type: Enhancement, v2.5
