Repository openware/peatio, pull requests merged in 2020-10, with the labels that each got.

#2703 Fix: Update import/export rake tasks for payment_addresses
  lib/tasks/export.rake
  lib/tasks/import.rake
Labels: PR: Review, v2.6

#2700 Remove uri validation from wallet model
  app/api/v2/admin/wallets.rb
  app/models/wallet.rb
  spec/api/v2/admin/wallets_spec.rb
  spec/models/wallet_spec.rb
Labels: PR: Ready, v2.6

#2706 Feature: Add export:configs Rake task (#2693)
  lib/peatio/export.rb
  lib/peatio/import.rb
  lib/tasks/export.rake
  lib/tasks/import.rake
  lib/tasks/seed.rake
Labels: PR: Ready, v2.5

#2698 WIP: Introduce CoinGecko API Endpoints
  app/api/v2/coin_gecko/entities/orderbook.rb
  app/api/v2/coin_gecko/entities/pair.rb
  app/api/v2/coin_gecko/entities/ticker.rb
  app/api/v2/coin_gecko/helpers.rb
  app/api/v2/coin_gecko/historical_trades.rb
  app/api/v2/coin_gecko/mount.rb
  app/api/v2/coin_gecko/orderbook.rb
  app/api/v2/coin_gecko/pairs.rb
  app/api/v2/coin_gecko/tickers.rb
  app/api/v2/mount.rb
  app/models/trade.rb
  config/initializers/jwt_rack.rb
  spec/api/v2/coin_gecko/historical_trades.rb
  spec/api/v2/coin_gecko/orderbook_spec.rb
  spec/api/v2/coin_gecko/pairs_spec.rb
  spec/api/v2/coin_gecko/tickers_spec.rb
Labels: PR: WIP, v2.6

#2707 Update vault rails gem. Fix update wallet params
  Gemfile.lock
  app/api/v2/admin/wallets.rb
Labels: PR: Ready, v2.6

#2708 Feature: Mask beneficiary account_number on API level
  app/api/v2/admin/beneficiaries.rb
  app/api/v2/admin/entities/beneficiary.rb
  app/api/v2/entities/beneficiary.rb
  app/api/v2/management/beneficiaries.rb
  app/api/v2/management/entities/beneficiary.rb
  app/models/beneficiary.rb
  docs/api/mask.md
  spec/api/v2/account/beneficiaries_spec.rb
  spec/api/v2/admin/beneficiaries_spec.rb
  spec/api/v2/management/beneficiaries_spec.rb
  spec/models/beneficiary_spec.rb
Labels: PR: Review, v2.6

#2712 Update vault policies documentation
  docs/vault.md
Labels: PR: Ready, v2.6

#2716 Fix InfluxDB sharding spec
  spec/lib/influxdb_spec.rb
Labels: PR: Ready, v2.6

#2715 Enhancement: Add error message for adjustment creation if user balance is insufficient
  app/api/v2/admin/adjustments.rb
  spec/api/v2/admin/adjustments_spec.rb
Labels: PR: Ready, v2.6

#2711 Add separate user and password for archive DB
  config/database.yml
Labels: PR: Ready, v2.6

#2720 Feature: Add possibility to import and export Operation::Accounts
  lib/peatio/export.rb
  lib/peatio/import.rb
  lib/tasks/export.rake
  lib/tasks/import.rake
Labels: PR: Ready, cherry-pick, v2.6

#2721 Feature: Add possibility to import and export Operation::Accounts
  lib/peatio/export.rb
  lib/peatio/import.rb
  lib/tasks/export.rake
  lib/tasks/import.rake
Labels: PR: Review, v2.5

#2722 Fix: Remove partial wallet settings update
  app/api/v2/admin/wallets.rb
  spec/api/v2/admin/wallets_spec.rb
Labels: PR: Ready, v2.6

#2724 Enhancement: Disable WLs if there are no in DB or zero limits
  app/models/withdraw.rb
  spec/models/withdraw_spec.rb
Labels: PR: Ready, v2.6

#2725 Fix: Add ability to update wallet settings
  app/api/v2/admin/wallets.rb
  spec/api/v2/admin/wallets_spec.rb
Labels: PR: Ready, v2.6

#2727 Update WalletService trigger_webhook_event method
  app/api/v2/webhooks_helpers.rb
  app/services/wallet_service.rb
Labels: PR: Ready, v2.6

#2729 Fix: Dont mask beneficiary account number on admin endpoints
  app/api/v2/admin/entities/member.rb
  spec/api/v2/admin/members_spec.rb
Labels: PR: Ready, v2.6

#2730 Feature: Add user permissions
  app/api/v2/account/balances.rb
  app/api/v2/account/beneficiaries.rb
  app/api/v2/account/deposits.rb
  app/api/v2/account/stats.rb
  app/api/v2/account/transactions.rb
  app/api/v2/account/withdraws.rb
  app/api/v2/helpers.rb
  app/api/v2/market/orders.rb
  app/api/v2/market/trades.rb
  app/models/ability.rb
  app/models/user_ability.rb
  config/abilities.yml
  spec/api/v2/account/balances_spec.rb
  spec/api/v2/account/beneficiaries_spec.rb
  spec/api/v2/account/deposits_spec.rb
  spec/api/v2/account/stats_spec.rb
  spec/api/v2/account/transactions_spec.rb
  spec/api/v2/account/withdraws_spec.rb
  spec/api/v2/market/orders_spec.rb
  spec/api/v2/market/trades_spec.rb
  spec/models/user_ability_spec.rb
Labels: PR: Ready, v2.6

#2731 Fix: Allow dot in currency code for API endpoints
  app/api/v2/account/balances.rb
  app/api/v2/account/deposits.rb
  app/api/v2/admin/currencies.rb
  app/api/v2/admin/markets.rb
  app/api/v2/management/currencies.rb
  app/api/v2/public/currencies.rb
  app/api/v2/public/markets.rb
  spec/api/v2/account/balances_spec.rb
  spec/api/v2/account/deposits_spec.rb
  spec/api/v2/admin/currencies_spec.rb
  spec/api/v2/admin/markets_spec.rb
  spec/api/v2/management/currencies_spec.rb
  spec/api/v2/public/currencies_spec.rb
  spec/api/v2/public/markets_spec.rb
  spec/factories/currencies.rb
  spec/factories/market.rb
Labels: PR: Ready, v2.6
