Repository openware/peatio, pull requests merged in 2021-02, with the labels that each got.

#2795 Enhancement: Add filter by side for trades
  app/api/v2/entities/trade.rb
  app/api/v2/market/named_params.rb
  app/api/v2/market/trades.rb
  db/migrate/20210112063704_add_taker_type_index_on_trades.rb
  db/schema.rb
  spec/api/v2/market/trades_spec.rb
Labels: PR: Ready, v2.6

#2822 Enhancement: Add Kaigara version to the Dockerfile
  .drone.yml
  Dockerfile
Labels: PR: Ready, v2.6

#2821 Feature: date filters for /account/deposits, /account/withdraws
  app/api/v2/account/deposits.rb
  app/api/v2/account/withdraws.rb
  spec/api/v2/account/deposits_spec.rb
  spec/api/v2/account/withdraws_spec.rb
Labels: PR: Ready, v2.6

#2823 Fix: add ability to Accountant to read Currency
  app/models/abilities/accountant.rb
  spec/models/abilities_spec.rb
Labels: PR: Ready, v2.5

#2802 Feature: Internal transfers
  app/api/v2/account/internal_transfers.rb
  app/api/v2/account/mount.rb
  app/api/v2/admin/entities/internal_transfer.rb
  app/api/v2/admin/internal_transfers.rb
  app/api/v2/admin/mount.rb
  app/api/v2/entities/internal_transfer.rb
  app/models/internal_transfer.rb
  app/models/member.rb
  app/models/trade.rb
  config/abilities.yml
  db/migrate/20210120133912_create_internal_transfers.rb
  db/schema.rb
  spec/api/v2/account/internal_transfer_spec.rb
  spec/api/v2/admin/internal_transfer_spec.rb
  spec/factories/internal_transfer.rb
Labels: PR: Ready, v2.6

#2819 Fix missing fields from markets/list mng api
  app/api/v2/management/markets.rb
  spec/api/v2/management/markets_spec.rb
Labels: PR: Ready, v2.6

#2815 Feature: Whitelisted smart contracts implementation
  app/api/v2/admin/entities/whitelisted_smart_contract.rb
  app/api/v2/admin/mount.rb
  app/api/v2/admin/whitelisted_smart_contracts.rb
  app/models/blockchain.rb
  app/models/whitelisted_smart_contract.rb
  app/services/blockchain_service.rb
  config/abilities.yml
  config/templates/seed/whitelisted_smart_contracts.yml.erb
  db/migrate/20210210133912_create_internal_transfers.rb
  db/migrate/20210219144535_create_whitelisted_smart_contracts.rb
  db/schema.rb
  db/seeds.rb
  docs/images/peatio/tower_whitelisted_contracts.png
  docs/smart_contracts_whitelist.md
  lib/peatio/ethereum/blockchain.rb
  lib/peatio/import.rb
  lib/tasks/import.rake
  lib/tasks/seed.rake
  spec/api/v2/admin/abilities_spec.rb
  spec/api/v2/admin/trading_fees_spec.rb
  spec/api/v2/admin/whitelisted_smart_contracts_spec.rb
  spec/factories/currencies.rb
  spec/factories/whitelisted_smart_contracts.rb
  spec/lib/ethereum/blockchain_spec.rb
  spec/models/admin_ability_spec.rb
  spec/models/whitelisted_smart_contract_spec.rb
  spec/resources/ethereum-data/rinkeby/2621840-2621842.json
  spec/resources/ethereum-data/rinkeby/transaction-receipts/2621840-2621842.json
  spec/resources/ethereum-data/rinkeby/transactions/0xeb92797eb91f53ce7bb68abaf3fd3198980d971dd42f9fcb6eb1272ef3ef2a0e.json
  spec/resources/whitelisted_addresses/1.csv
Labels: PR: Changes needed, PR: QA, Priority: High, Type: Feature, v2.6

#2824 Feature: Add ability to configure locked funds on deposit
  app/models/deposit.rb
  config/initializers/config.rb
  docs/peatio/configuration.md
  lib/peatio/app.rb
  spec/models/deposit_spec.rb
Labels: PR: Ready, v2.6

#2811 Add internal transfer and deposit fiat abilities
  config/abilities.yml
Labels: v2.6

#2812 Feature: Add opendax-cloud client
  app/api/v2/management/withdraws.rb
  app/models/deposit.rb
  app/models/member.rb
  app/models/withdraws/coin.rb
  app/models/withdraws/fiat.rb
  app/services/wallet_service.rb
  config/initializers/inflections.rb
  config/initializers/wallet_api.rb
  lib/peatio/ethereum/wallet.rb
  lib/peatio/opendax_cloud/client.rb
  lib/peatio/opendax_cloud/wallet.rb
  lib/peatio/owhdwallet/client.rb
  lib/peatio/owhdwallet/wallet.rb
  spec/lib/opendax_cloud/wallet_spec.rb
  spec/lib/owhdwallet/wallet_spec.rb
Labels: PR: Changes needed, v2.6

#2831 Enhancement: Update taker_type migration. Improve trade_to_influx rake task
  db/migrate/20200316132213_add_taker_type_to_trade.rb
  lib/tasks/import.rake
  lib/tasks/trade_taker_type.rake
Labels: v2.6

#2832 Feature: Add management API endpoints to create/update engines
  app/api/v2/management/engines.rb
  app/api/v2/management/entities/engine.rb
  app/api/v2/management/mount.rb
  spec/api/v2/management/engines_spec.rb
Labels: PR: Ready, v2.6
