Repository openware/peatio, pull requests merged in 2021-08, with the labels that each got.

#2991 Fix blockchain model loading in Withdraw and Deposit validations
  app/models/deposits/coin.rb
  app/models/withdraws/coin.rb
Labels: v3.0

#2870 Feature: Add account type
  app/api/v2/account/balances.rb
  app/api/v2/entities/account.rb
  app/models/account.rb
  app/models/member.rb
  app/models/operations/account.rb
  config/initializers/config.rb
  config/templates/seed/accounts.yml.erb
  db/migrate/20210322134633_add_account_type.rb
  db/schema.rb
  lib/tasks/import.rake
  spec/api/v2/account/balances_spec.rb
  spec/models/operations/account_spec.rb
Labels: PR: Review, v3.1

#2999 Fix: Add id && status to public blockchain currency entity
  app/api/v2/admin/entities/blockchain_currency.rb
  app/api/v2/entities/blockchain_currency.rb
Labels: v3.1
