Repository openware/peatio, pull requests merged in 2021-05, with the labels that each got.

#2926 Feature: Add generic webhook event && Add remote_id to withdraw
  .drone.yml
  app/api/v2/public/webhooks.rb
  app/api/v2/webhooks_helpers.rb
  app/models/wallet.rb
  app/models/withdraw.rb
  app/services/wallet_service.rb
  app/workers/amqp/withdraw_coin.rb
  db/migrate/20210502125244_add_remote_id_field.rb
  db/schema.rb
  spec/api/v2/public/webhooks_spec.rb
  spec/models/withdraw_spec.rb
  spec/services/wallet_service_spec.rb
  spec/workers/withdraw_coin_spec.rb
Labels: PR: Review, v2.6

#2928 Feature: Add wallet plain settings
  app/models/wallet.rb
  app/services/wallet_service.rb
  db/migrate/20210512120717_add_plain_settings_to_wallets.rb
  db/schema.rb
  spec/services/wallet_service_spec.rb
Labels: PR: Ready, v2.6

#2921 Feature: Add wallet retired status
  app/api/v2/account/deposits.rb
  app/api/v2/admin/deposits.rb
  app/api/v2/admin/wallets.rb
  app/api/v2/entities/account.rb
  app/api/v2/entities/payment_address.rb
  app/api/v2/management/payment_address.rb
  app/api/v2/webhooks_helpers.rb
  app/models/deposit.rb
  app/models/payment_address.rb
  app/models/wallet.rb
  app/workers/daemons/deposit.rb
  lib/tasks/import.rake
  spec/api/v2/account/deposits_spec.rb
  spec/api/v2/admin/deposits_spec.rb
  spec/api/v2/public/webhooks_spec.rb
  spec/factories/deposits.rb
  spec/models/currency_spec.rb
  spec/models/payment_address_spec.rb
  spec/services/wallet_service_spec.rb
  spec/workers/deposit_coin_address_spec.rb
Labels: PR: Ready, v2.6

#2927 Enhancement: Dependencies update
  Gemfile.lock
Labels: v3.1

#2936 Fix: Failing specs && triger_webhook_event configuration
  Gemfile
  Gemfile.plugin
  app/api/v2/admin/wallets.rb
  app/models/wallet.rb
  app/services/wallet_service.rb
  spec/api/v2/admin/wallets_spec.rb
Labels: v3.0

#2923 Feature: Read JSON/YAML file to create blockchain wallets and currencies
  app/api/v2/admin/import_configs.rb
  app/api/v2/admin/mount.rb
  app/api/v2/admin/wallets.rb
  app/api/v2/import_configs_helper.rb
  docs/peatio/import_configuration.md
  spec/api/v2/admin/wallets_spec.rb
  spec/api/v2/import_configs_helper_spec.rb
  spec/resources/import_configs/data.json
Labels: PR: Ready, v2.6

#2925 Fix: Does not allow empty amount for adjustment
  app/api/v2/admin/adjustments.rb
  spec/api/v2/admin/adjustments_spec.rb
Labels: PR: Review, v3.0

#2943 Fix: Merge deposit options with transaction options
  app/services/wallet_service.rb
  spec/services/wallet_service_spec.rb
Labels: PR: Ready, v2.6
