Repository openware/peatio, pull requests merged in 2021-06, with the labels that each got.

#2939 Fix: validate currency sum by 'subunits' param
  app/models/concerns/fee_chargeable.rb
Labels: PR: Ready, v3.1

#2937 Feature: add new 'reporter' role
  config/abilities.yml
  docs/api/swagger/admin_api.json
  spec/models/admin_ability_spec.rb
  spec/models/user_ability_spec.rb
Labels: PR: Ready, v3.1

#2935 Fix: add 'state' to create engine params
  app/api/v2/admin/engines.rb
  spec/api/v2/admin/engines_spec.rb
Labels: PR: Ready, v3.1

#2948 Fix rspec for precision validations
  app/api/v2/admin/engines.rb
  app/models/concerns/fee_chargeable.rb
  spec/api/v2/management/withdraws_spec.rb
Labels: v3.1

#2944 Feature: Add WithdrawWatcher Job
  app/jobs/cron/withdraw_watcher.rb
  app/models/wallet.rb
  app/workers/daemons/cron_job.rb
  app/workers/daemons/deposit.rb
  spec/api/v2/admin/wallets_spec.rb
  spec/jobs/withdraw_watcher_spec.rb
Labels: v3.0

#2878 Feature: Add wallet get/create/update through management API
  app/api/v2/management/entities/wallet.rb
  app/api/v2/management/mount.rb
  app/api/v2/management/wallets.rb
  app/api/v2/param_helpers.rb
  spec/api/v2/management/wallets_spec.rb
Labels: PR: Review
