Repository openware/peatio, pull requests merged in 2021-01, with the labels that each got.

#2792 Fix: Thread safe account creation. Change account update on transfer creation
  app/models/member.rb
  app/models/transfer.rb
  spec/jobs/stats_member_pnl_spec.rb
Labels: PR: Review, v2.5

#2793 Fix: Thread safe account creation. Change account update on transfer creation
  app/models/member.rb
  app/models/transfer.rb
Labels: PR: Review, v2.4

#2791 Fix: Update abilities specs
  config/abilities.yml
  spec/api/v2/admin/abilities_spec.rb
  spec/api/v2/admin/blockchains_spec.rb
  spec/api/v2/admin/currencies_spec.rb
  spec/api/v2/admin/trading_fees_spec.rb
  spec/models/admin_ability_spec.rb
  spec/models/user_ability_spec.rb
Labels: PR: Review, v2.6

#2796 Enhancement: Update dependencies
  Gemfile.lock
Labels: PR: Review, v2.6

#2797 Enhancement: improve to_d method
  config/initializers/string.rb
  spec/lib/decimal_spec.rb
Labels: PR: Ready, v2.6

#2799 Enhancement: Add callback for fetch transaction on withdraw load
  app/models/withdraw.rb
  app/services/blockchain_service.rb
  lib/peatio/bitcoin/blockchain.rb
  lib/peatio/ethereum/blockchain.rb
  spec/api/v2/admin/withdraws_spec.rb
  spec/models/withdraw_spec.rb
Labels: PR: Review, v2.6

#2807 Feature: MNG Api endpoint for PaymentAddress generation
  app/api/v2/management/entities/payment_address.rb
  app/api/v2/management/mount.rb
  app/api/v2/management/payment_address.rb
  app/models/member.rb
  app/models/wallet.rb
  spec/api/v2/management/payment_address_spec.rb
Labels: PR: Review, v2.6

#2808 Feature: add remote field to PaymentAddress
  app/api/v2/entities/account.rb
  app/api/v2/entities/payment_address.rb
  app/api/v2/management/entities/payment_address.rb
  app/api/v2/management/payment_address.rb
  app/models/member.rb
  app/models/payment_address.rb
  app/models/trade.rb
  db/migrate/20210128083207_add_remote_to_payment_address.rb
  db/schema.rb
  spec/api/v2/account/deposits_spec.rb
  spec/api/v2/management/payment_address_spec.rb
Labels: PR: Review, v2.6
