Repository openware/peatio, pull requests merged in 2021-04, with the labels that each got.

#2879 Fix: Check min_deposit_amount on deposit creation only
  app/models/deposit.rb
Labels: PR: Review, v2.6

#2883 Fix: Add pagination to beneficiary
  app/api/v2/account/beneficiaries.rb
  spec/api/v2/account/beneficiaries_spec.rb
Labels: PR: Ready, v2.6

#2887 Fix: Error on adjustment creation without member
  app/api/v2/admin/adjustments.rb
  spec/api/v2/admin/adjustments_spec.rb
Labels: v2.6

#2888 Fix: Error on adjustment creation without member
  app/api/v2/admin/adjustments.rb
  spec/api/v2/admin/adjustments_spec.rb
Labels: v3.0

#2889 Fix: Error on adjustment creation without member
  app/api/v2/admin/adjustments.rb
  spec/api/v2/admin/adjustments_spec.rb
Labels: v3.1

#2900 Fix: Webhook bitgo support
  Gemfile.lock
  Gemfile.plugin
  app/api/v2/webhooks_helpers.rb
  spec/api/v2/public/webhooks_spec.rb
Labels: PR: Ready, v3.1

#2898 Fix: Webhook bitgo support
  Gemfile.lock
  Gemfile.plugin
  app/api/v2/webhooks_helpers.rb
  spec/api/v2/public/webhooks_spec.rb
Labels: PR: Ready, v2.6

#2899 Fix: Webhook bitgo support
  Gemfile.lock
  Gemfile.plugin
  app/api/v2/webhooks_helpers.rb
  spec/api/v2/public/webhooks_spec.rb
Labels: PR: Ready, v3.0

#2893 Enhancement: Migrate all primary keys to bigint
  Gemfile.lock
  config/application.rb
  db/migrate/20210412114831_change_primary_key_to_big_int.rb
  db/migrate/concerns/primary_key_migration.rb
  db/schema.rb
Labels: v2.4

#2894 Enhancement: Migrate all primary keys to bigint
  Gemfile.lock
  config/application.rb
  db/migrate/20210413105543_change_primary_key_to_big_int.rb
  db/migrate/concerns/primary_key_migration.rb
  db/schema.rb
Labels: v2.5

#2896 Enhancement: Migrate all primary keys to bigint
  Gemfile
  Gemfile.lock
  app/api/v2/management/accounts.rb
  app/models/account.rb
  app/trading/matching/executor.rb
  config/application.rb
  db/migrate/20210414105529_change_primary_key_to_big_int.rb
  db/migrate/concerns/primary_key_migration.rb
  db/schema.rb
  spec/api/v2/management/accounts_spec.rb
  spec/models/account_spec.rb
Labels: v3.0

#2912 Fix: Prevent loop in deposit_worker daemon
  app/models/currency.rb
  app/models/deposit.rb
  app/models/withdraw.rb
  app/services/wallet_service.rb
  app/workers/daemons/deposit.rb
  db/migrate/20210426083359_add_error_field_to_deposit.rb
  db/schema.rb
  lib/peatio/ethereum/wallet.rb
  spec/lib/ethereum/wallet_spec.rb
  spec/models/deposit_spec.rb
  spec/workers/deposit_spec.rb
Labels: Type: Bug, v2.6

#2914 Fix: Prevent loop in deposit_worker daemon
  app/models/currency.rb
  app/models/deposit.rb
  app/models/withdraw.rb
  app/services/wallet_service.rb
  app/workers/daemons/deposit.rb
  db/migrate/20210426083359_add_error_field_to_deposit.rb
  db/schema.rb
  lib/peatio/ethereum/wallet.rb
  spec/lib/ethereum/wallet_spec.rb
  spec/models/deposit_spec.rb
  spec/workers/deposit_spec.rb
Labels: v3.0

#2917 Enhancement: Fix mariadb tests
  app/models/deposit.rb
Labels: Type: Bug, v2.6
