Repository openware/peatio, pull requests merged in 2021-07, with the labels that each got.

#2972 Fix: add missing under_review state to list of Withdraw STATES
  app/models/withdraw.rb
  spec/api/v2/admin/withdraws_spec.rb
Labels: PR: QA Approved

#2988 Enhancement: Add seed for blockchain currencies
  config/templates/seed/currencies.yml.erb
  db/schema.rb
  lib/peatio/import.rb
  lib/tasks/seed.rake
Labels: PR: Ready

#2989 Enhancement: Member email as optional param
  app/models/member.rb
  config/templates/seed/currencies.yml.erb
  db/migrate/20210721093857_change_member_email_necessity.rb
  spec/api/v2/account/balances_spec.rb
Labels: PR: Ready

#2990 Feature: Add manual deposit approve
  app/api/v2/admin/deposits.rb
  app/models/deposit.rb
  app/models/refund.rb
  app/services/wallet_service.rb
  config/initializers/config.rb
  spec/models/deposit_spec.rb
  spec/services/wallet_service_spec.rb
Labels: v3.0
