Repository openware/peatio, pull requests merged in 2021-03, with the labels that each got.

#2835 Enhancement: Add from_id param to deposit MNG api
  app/api/v2/management/deposits.rb
  spec/api/v2/management/deposits_spec.rb
Labels: PR: Review, v2.6

#2837 Enhancement: Add ID in deposit management API response
  app/api/v2/management/entities/deposit.rb
Labels: PR: Ready, v2.6

#2841 Enhancement: Add job:order:delete rake task
  lib/tasks/job.rake
Labels: PR: Review, v2.6

#2854 Enhancement: Update rails to 5.2.4.5
  Gemfile
  Gemfile.lock
  lib/tasks/seed.rake
Labels: PR: Review, v2.6

#2853 Enhancement: Update rails to 5.2.4.5
  Gemfile
  Gemfile.lock
  lib/tasks/seed.rake
Labels: PR: Review

#2850 Fix: increase capacity of 'from_address' column
  db/migrate/20210302120855_from_address_increase_capacity.rb
  db/schema.rb
  db/structure.sql
Labels: PR: Ready, v2.6

#2839 Prevent dead links on openware.com/sdk
  README.md
Labels: PR: Ready, v2.6

#2849 Enhancement: update engine upstream docs
  docs/peatio/engine.md
Labels: PR: Ready, v2.6

#2855 Enhancement: Add address entity in Deposit MNG api
  app/api/v2/management/entities/deposit.rb
Labels: PR: Review, v2.6

#2848 Fix: Add search by name on engines mng API
  app/api/v2/management/engines.rb
  app/api/v2/management/entities/engine.rb
  app/api/v2/management/entities/market.rb
  app/api/v2/management/markets.rb
  spec/api/v2/management/engines_spec.rb
  spec/api/v2/management/markets_spec.rb
Labels: PR: Review, v2.6

#2861 Fix: Update withdraws/deposits downcase policy
  app/models/deposits/coin.rb
  app/models/withdraws/coin.rb
Labels: PR: Review, v2.6

#2829 Feature: Pluggable webhook endpoint
  Gemfile
  Gemfile.lock
  app/api/v2/management/entities/deposit.rb
  app/api/v2/public/webhooks.rb
  app/api/v2/webhooks_helpers.rb
  app/services/wallet_service.rb
  docs/airdrop.md
  docs/peatio/opendax_cloud_plugin.md
  lib/peatio/opendax_cloud/wallet.rb
  spec/api/v2/public/webhooks.rb
  spec/api/v2/public/webhooks_spec.rb
  spec/factories/wallet.rb
  spec/factories/withdraw.rb
  spec/lib/opendax_cloud/wallet_spec.rb
  spec/services/wallet_service_spec.rb
Labels: PR: Review, v2.6

#2867 Feature: Add management API endpoints to get/create markets
  app/api/v2/management/markets.rb
  spec/api/v2/management/markets_spec.rb
Labels: PR: Ready, v2.6

#2868 Fix: Tests for public webhook API call
  spec/api/v2/public/webhooks_spec.rb
Labels: PR: Review, v2.6

#2869 Feature: Add management API to create currency
  app/api/v2/entities/currency.rb
  app/api/v2/management/currencies.rb
  spec/api/v2/management/currencies_spec.rb
Labels: PR: Ready

#2871 Add the support for ERB in management_api.yml
  config/initializers/jwt.rb
  config/initializers/mng_api.rb
  config/management_api.yml
  config/templates/management_api_v1.yml.erb
Labels: PR: Review, v2.6

#2873 Fix: Admin ability models
  Gemfile.lock
  app/api/v2/admin/adjustments.rb
  app/api/v2/admin/beneficiaries.rb
  app/api/v2/admin/blockchains.rb
  app/api/v2/admin/currencies.rb
  app/api/v2/admin/deposits.rb
  app/api/v2/admin/internal_transfers.rb
  app/api/v2/admin/members.rb
  app/api/v2/admin/orders.rb
  app/api/v2/admin/trades.rb
  app/api/v2/admin/trading_fees.rb
  app/api/v2/admin/wallets.rb
  app/api/v2/admin/whitelisted_smart_contracts.rb
  app/api/v2/admin/withdraw_limits.rb
  app/api/v2/admin/withdraws.rb
Labels: PR: Review
